//
//  SeedQuestions.swift
//  Travel Trivia
//
//  The bundled starter packs: Riddle Realm, Would You Rather, and Movie
//  Quote Mashup. The same content is seeded into the Supabase `questions`
//  table (see supabase/migrations); these local copies keep every seeded
//  genre fully playable offline.
//

import Foundation

nonisolated enum SeedQuestions {
    /// Every genre with bundled content, by slug — the single source for
    /// "does this genre have questions yet".
    static let packs: [String: [TriviaQuestion]] = [
        "riddle-realm": riddleRealm,
        "would-you-rather": wouldYouRather,
        "movie-quote-mashup": movieQuoteMashup,
    ]

    /// First authored option is the correct one (shuffled at deal time);
    /// prediction packs pass `fixedAnswer: false` and leave correctness to
    /// the party's majority vote.
    private static func build(prefix: String, fixedAnswer: Bool,
                              _ entries: [(Difficulty, String, [String])]) -> [TriviaQuestion] {
        entries.enumerated().map { index, entry in
            let number = index + 1
            let options = entry.2.enumerated().map { optionIndex, text in
                AnswerOption(id: "\(prefix)-\(number)-\(optionIndex)", text: text)
            }
            return TriviaQuestion(
                id: "\(prefix)-\(number)",
                difficulty: entry.0,
                prompt: entry.1,
                options: options,
                correctOptionID: fixedAnswer ? options[0].id : nil
            )
        }
    }
    static let riddleRealm: [TriviaQuestion] = {
        func question(_ number: Int, _ difficulty: Difficulty, _ prompt: String,
                      _ optionTexts: [String]) -> TriviaQuestion {
            // First authored option is always the correct one; display order
            // is shuffled at game start.
            let options = optionTexts.enumerated().map { index, text in
                AnswerOption(id: "riddle-\(number)-\(index)", text: text)
            }
            return TriviaQuestion(
                id: "riddle-\(number)",
                difficulty: difficulty,
                prompt: prompt,
                options: options,
                correctOptionID: options[0].id
            )
        }

        return [
            question(1, .easy, "I have keys but no locks, space but no room — you can enter, but not go outside. What am I?",
                     ["Keyboard", "House", "Piano", "Map", "Wallet", "Elevator"]),
            question(2, .easy, "What has hands but can't clap?",
                     ["Clock", "Glove", "Statue", "Robot", "Watch", "Mannequin"]),
            question(3, .easy, "What has a neck but no head?",
                     ["Bottle", "Shirt", "Guitar", "Turtle", "Violin", "Sweater"]),
            question(4, .easy, "What gets wetter the more it dries?",
                     ["Towel", "Sponge", "Rain", "Ocean", "Washcloth", "Umbrella"]),
            question(5, .easy, "What has to be broken before you can use it?",
                     ["Egg", "Promise", "Record", "Seal", "Piggy Bank", "Code"]),
            question(6, .easy, "What has one eye but can't see?",
                     ["Needle", "Storm", "Potato", "Cat", "Hurricane", "Button"]),
            question(7, .medium, "I speak without a mouth, hear without ears, and come alive with the wind. What am I?",
                     ["Echo", "Ghost", "Shadow", "Whisper", "Wind", "Radio"]),
            question(8, .medium, "What comes once in a minute, twice in a moment, but never in a thousand years?",
                     ["Letter M", "Heartbeat", "Blink", "Second", "Letter N", "Minute Hand"]),
            question(9, .medium, "I'm tall when I'm young and short when I'm old. What am I?",
                     ["Candle", "Tree", "Person", "Pencil", "Match", "Crayon"]),
            question(10, .medium, "What can travel around the world while staying in a corner?",
                     ["Stamp", "Map", "Globe", "Coin", "Postcard", "Sticker"]),
            question(11, .medium, "What building has the most stories?",
                     ["Library", "Skyscraper", "Museum", "School", "Bookstore", "Apartment"]),
            question(12, .medium, "What's full of holes but still holds water?",
                     ["Sponge", "Net", "Colander", "Cloud", "Sieve", "Screen"]),
            question(13, .hard, "I'm not alive, but I grow. I don't have lungs, but I need air. I don't have a mouth, but water kills me. What am I?",
                     ["Fire", "Plant", "Cloud", "Ice", "Smoke", "Steam"]),
            question(14, .hard, "What has many teeth but cannot bite?",
                     ["Comb", "Saw", "Zipper", "Gear", "Rake", "Fork"]),
            question(15, .hard, "I shave every day, but my beard stays the same. What am I?",
                     ["Barber", "Werewolf", "Goat", "Father Time", "Lumberjack", "Santa"]),
            question(16, .hard, "The more you take, the more you leave behind. What am I?",
                     ["Footsteps", "Time", "Memories", "Breath", "Shadow", "Age"]),
        ]
    }()

    // MARK: - Would You Rather (prediction: majority vote becomes correct)

    static let wouldYouRather: [TriviaQuestion] = build(prefix: "wyr", fixedAnswer: false, [
        (.easy, "Which car mishap would be the WORST right now?",
         ["AC breaks in July", "Fries in every seat crack", "GPS stuck \"recalculating\" for 3 hours",
          "Carsick sibling in the back", "Every phone charger dies", "Flat tire 50 miles from town"]),
        (.easy, "Which power would help this trip the most?",
         ["Teleport past traffic", "X-ray vision for rest stops", "Talk to animals",
          "Control the weather", "Super speed", "Turn invisible to skip gas station lines"]),
        (.medium, "If the car transformed into one of these for the rest of the trip...",
         ["Hot air balloon", "Submarine", "Monster truck",
          "Go-kart", "Rocket ship", "Horse-drawn carriage"]),
        (.easy, "Which snack disaster would ruin the car fastest?",
         ["Melted chocolate on seats", "Spilled milkshake in the cupholder", "Exploding popcorn",
          "Burst ketchup packet", "Melted gummy bears in the carpet", "Crushed chip bag underfoot"]),
        (.medium, "Which surprise stop would you most want the driver to make?",
         ["Roadside dinosaur statue", "Giant ball of twine", "Drive-in movie theater",
          "Ice cream stand", "Petting zoo", "Fireworks store"]),
        (.easy, "Which road trip soundtrack would you be stuck with for 6 hours?",
         ["Polka music", "Whale sounds", "One song on repeat",
          "A podcast about tax law", "Bagpipes", "Elevator music"]),
        (.medium, "Which unexpected passenger would make the trip the most interesting?",
         ["A talking parrot", "A magician", "A famous chef",
          "A ghost", "A stand-up comedian", "A fortune teller"]),
        (.easy, "Which weather would you least want to drive through?",
         ["A hailstorm", "Thick fog", "A sandstorm",
          "A heat wave with no AC", "A sudden blizzard", "A swarm of bugs on the windshield"]),
        (.medium, "Which roadside attraction detour would be worth the extra hour?",
         ["World's largest ball of yarn", "A haunted motel", "A UFO museum",
          "A cheese factory tour", "An alligator farm", "A mirror maze"]),
        (.medium, "Which car game would you be forced to play for the next 2 hours?",
         ["I Spy with zero good options", "20 Questions with a cheater", "Punch Buggy but everyone's aggressive",
          "License plate bingo", "Would You Rather (very meta)", "Silent staring contest"]),
        (.medium, "Which pit stop food would you actually be excited to eat?",
         ["Gas station sushi", "A giant turkey leg", "Mystery gas station hot dog",
          "A questionable burrito", "Truck stop pancakes", "A whole rotisserie chicken"]),
        (.hard, "Which navigator mistake would send you the most off course?",
         ["Reading the map upside down", "Trusting a psychic instead of GPS", "Following a \"shortcut\" through a cornfield",
          "Arguing with the GPS voice", "Using a map from 1998", "Following another car that looked \"confident\""]),
        (.easy, "Which animal would you least want to spot crossing the road ahead?",
         ["A moose", "An escaped zoo lion", "A herd of turtles",
          "A giant tumbleweed monster", "A peacock", "A confused ostrich"]),
        (.easy, "Which car smell would be hardest to survive for 6 hours?",
         ["Wet dog", "Old gym socks", "Durian fruit",
          "Burnt popcorn", "Gas station coffee gone bad", "A skunk that got a little too close"]),
        (.hard, "Which vacation would you rather accidentally end up on?",
         ["A cruise full of clowns", "A silent meditation retreat", "A haunted castle tour",
          "A competitive cheese-rolling festival", "A week at a llama farm", "A convention for people who love traffic cones"]),
        (.medium, "Which \"are we there yet\" answer would be the most annoying?",
         ["\"Ask me again in an hour\"", "A random riddle instead of an answer", "Complete silence",
          "\"We'll never get there\" (joking, hopefully)", "A math problem you have to solve first", "The GPS voice answering instead"]),
        (.medium, "Which emergency kit item would you actually need most on this trip?",
         ["A tiny umbrella", "An inflatable raft", "A whistle",
          "A disguise kit", "A magic 8-ball", "A portable karaoke machine"]),
        (.easy, "Which car temperature disaster would you rather deal with?",
         ["So hot the seats are lava", "So cold you can see your breath", "Only the driver's seat has AC",
          "Heated seats stuck on in summer", "One window stuck wide open", "The AC only blows at your feet"]),
        (.medium, "Which unexpected road trip companion sound would drive you craziest?",
         ["Someone humming off-key nonstop", "A squeaky seat that won't stop", "Someone narrating everything they see",
          "A phone stuck on the lowest possible volume ringtone", "Someone cracking their knuckles constantly", "A GPS that mispronounces every street name"]),
        (.medium, "Which type of rest stop bathroom would you dread most?",
         ["One with no soap", "One that's a 10-minute walk from the car", "One with a line around the building",
          "One that's suspiciously spotless (too clean, feels like a trap)", "One with only cold water", "One where the door doesn't lock"]),
        (.hard, "Which time period would you least want this road trip to take place in?",
         ["The 1800s (horse and wagon)", "The Stone Age", "The far future with flying cars you can't drive",
          "Medieval times", "The Ice Age", "A world with no roads at all yet"]),
        (.medium, "Which car breakdown would be the most inconvenient?",
         ["Dead battery at a scenic overlook", "Flat tire in a thunderstorm", "Out of gas in the middle of nowhere",
          "Engine trouble right before a big stop", "A door that won't open", "The trunk popping open on the highway"]),
        (.hard, "Which mythical creature would you least want to see out the car window?",
         ["A dragon circling overhead", "A troll blocking a bridge", "A sea monster in a lake you're passing",
          "A werewolf at a rest stop", "A giant spider web across the road", "A ghost hitchhiker"]),
        (.easy, "Which car chore would you least want to be stuck doing at the next stop?",
         ["Cleaning out the trash bag", "Untangling all the charging cables", "Refilling everyone's water bottles",
          "Wiping bug guts off the windshield", "Reorganizing the trunk", "Finding the one shoe that rolled under a seat"]),
        (.hard, "Which map mishap would send you the most off course?",
         ["Following an outdated paper map", "Trusting a GPS with a dead battery", "Taking directions from a stranger at a gas station",
          "Misreading \"north\" as \"south\"", "A GPS voice that keeps changing languages", "Following a bird because it \"looked confident\""]),
        (.medium, "Which car playlist would you be forced to listen to on repeat?",
         ["Nothing but car alarm sounds", "A single 45-minute song", "Whale songs",
          "A playlist of just sneezes", "An audiobook read in a monotone", "Dial-up internet sounds"]),
        (.hard, "Which unplanned overnight stop would be the most memorable?",
         ["A haunted-looking motel", "Sleeping in the car at a rest stop", "A campsite with no bathrooms nearby",
          "A tiny inn run by a very chatty owner", "A stranger's guest room after their kind offer", "A 24-hour diner booth"]),
        (.medium, "Which co-pilot mistake would cause the most chaos?",
         ["Falling asleep mid-directions", "Confidently giving wrong directions", "Spilling the entire snack bag",
          "Losing the phone charger", "Accidentally locking the doors while parked", "Turning on the hazard lights instead of the blinker"]),
        (.medium, "Which car superstition would you actually follow on this trip?",
         ["Holding your breath through every tunnel", "Touching the roof when you pass a yellow car", "Not saying \"flat tire\" out loud",
          "Making a wish at every state line", "Waving at every trucker", "Counting cows until you pass a graveyard"]),
        (.easy, "Which sudden detour sign would make you the most curious?",
         ["\"World's Smallest Church, 2 Miles\"", "\"Free Kittens\"", "\"Mystery Spot Ahead\"",
          "\"Home of the Giant Rubber Duck\"", "\"Haunted Bridge, Proceed with Caution\"", "\"Best Pie in 3 States\""]),
        (.easy, "Which car snack would you regret bringing the most?",
         ["Extra garlicky chips", "A whole durian", "Warm milk in a thermos",
          "Crumbly crackers everywhere", "Gum that lost its flavor in 2 minutes", "A soda that's mostly foam"]),
        (.medium, "Which family road trip tradition would you keep forever?",
         ["A \"first one to see the ocean\" shout", "A silly nickname for every gas station", "A road trip photo at every state sign",
          "A car karaoke hour", "A snack rotation system", "A \"guess the mileage\" game"]),
        (.hard, "Which unexpected road hazard would slow you down the most?",
         ["A parade crossing the highway", "A herd of cows on the road", "A marching band rehearsal",
          "A film crew blocking one lane", "A hot air balloon landing in the road", "A runaway inflatable bounce house"]),
        (.easy, "Which car nap position would you be stuck with for hours?",
         ["Head against the window (every bump)", "Neck at a painful angle", "Sitting bolt upright",
          "Squished in the middle seat", "Feet up on the dashboard", "Using a sibling's shoulder (against their will)"]),
        (.medium, "Which \"we're lost\" moment would be the most stressful?",
         ["No cell signal and no map", "A GPS that keeps rerouting in circles", "Running low on gas while lost",
          "It's getting dark and you're still lost", "Everyone in the car has a different opinion on where to go", "The one person who knows the way is asleep"]),
        (.medium, "Which travel-sized version of something would you be most annoyed to be stuck with?",
         ["A travel pillow that deflates", "A phone charger that barely reaches", "A tiny bag of chips that's mostly air",
          "A pocket-sized umbrella in a downpour", "A mini flashlight with a dying battery", "A sample-sized bottle of sunscreen for a whole beach day"]),
        (.easy, "Which type of traffic jam would test your patience the most?",
         ["One caused by nothing you can see", "One next to a very slow ice cream truck", "One where everyone's honking for no reason",
          "One caused by a spilled truckload of something silly", "One where your exit is juuust ahead", "One caused by a very confused goose"]),
        (.medium, "Which car repair would you be least equipped to handle yourselves?",
         ["A flat tire with no spare", "A dead battery with no jumper cables", "A check engine light with no manual",
          "A cracked windshield mid-drive", "An overheating engine", "A broken AC in the middle of summer"]),
        (.medium, "Which \"roughing it\" camping surprise would you handle worst?",
         ["No cell signal for 3 days", "A raccoon raiding the snacks", "Rain on the one night you forgot the tarp",
          "A tent that's suspiciously smaller than advertised", "Bugs everywhere at sunset", "Realizing you forgot the marshmallows"]),
        (.hard, "Which final stretch of the trip would drag the most?",
         ["The last hour with everyone asleep but you", "The last hour stuck behind a slow truck", "The last hour with a full bladder and no exit",
          "The last hour of a sibling asking \"are we there yet\"", "The last hour in bumper-to-bumper traffic", "The last hour realizing you're going the wrong way"]),
    ])

    // MARK: - Movie Quote Mashup (first authored option is the answer)

    static let movieQuoteMashup: [TriviaQuestion] = build(prefix: "mqm", fixedAnswer: true, [
        (.easy, "Which movie is this from? \"To infinity and beyond!\"",
         ["Toy Story", "Cars", "The Incredibles", "Monsters, Inc.", "Finding Nemo", "Shrek"]),
        (.easy, "Which movie is this from? \"Just keep swimming.\"",
         ["Finding Nemo", "Moana", "The Little Mermaid", "Shark Tale", "Free Willy", "Finding Dory"]),
        (.easy, "Which movie is this from? \"Hakuna Matata, what a wonderful phrase.\"",
         ["The Lion King", "Madagascar", "Zootopia", "Tarzan", "The Jungle Book", "Ice Age"]),
        (.easy, "Which movie is this from? \"There's no place like home.\"",
         ["The Wizard of Oz", "Alice in Wonderland", "Peter Pan", "Mary Poppins",
          "Charlie and the Chocolate Factory", "The Chronicles of Narnia"]),
        (.easy, "Which movie is this from? \"You're a wizard, Harry.\"",
         ["Harry Potter and the Sorcerer's Stone", "The Chronicles of Narnia", "The Hobbit",
          "Percy Jackson & the Olympians", "Fantastic Beasts and Where to Find Them", "Shrek"]),
        (.easy, "Which movie is this from? \"It's so fluffy I'm gonna die!\"",
         ["Despicable Me", "Minions", "The Secret Life of Pets", "Hop", "Sing", "Trolls"]),
        (.easy, "Which movie is this from? \"Bibbidi-Bobbidi-Boo.\"",
         ["Cinderella", "Sleeping Beauty", "Snow White and the Seven Dwarfs", "Frozen", "Enchanted", "Tangled"]),
        (.easy, "Which movie is this from? \"E.T. phone home.\"",
         ["E.T. the Extra-Terrestrial", "Close Encounters of the Third Kind", "Lilo & Stitch",
          "Flight of the Navigator", "Mars Attacks", "Paul"]),
        (.easy, "Which movie is this from? \"With great power comes great responsibility.\"",
         ["Spider-Man", "Batman Begins", "Iron Man", "Superman", "The Incredibles", "Big Hero 6"]),
        (.easy, "Which movie is this from? \"Ogres are like onions.\"",
         ["Shrek", "Puss in Boots", "Trolls", "Hotel Transylvania", "The Princess Bride", "Ella Enchanted"]),
        (.easy, "Which movie is this from? \"Some people are worth melting for.\"",
         ["Frozen", "Frozen II", "Ice Age", "Happy Feet", "The Snowman", "Klaus"]),
        (.easy, "Which movie is this from? \"The ocean chose you.\"",
         ["Moana", "Aquaman", "The Little Mermaid", "Finding Nemo", "Pirates of the Caribbean", "Life of Pi"]),
        (.easy, "Which movie is this from? \"No capes!\"",
         ["The Incredibles", "Sky High", "Big Hero 6", "Megamind", "Despicable Me", "The Boy and the Heron"]),
        (.easy, "Which movie is this from? \"Adventure is out there!\"",
         ["Up", "The Secret Life of Walter Mitty", "Onward", "Brave", "The Jungle Book", "Coco"]),
        (.easy, "Which movie is this from? \"Anyone can cook.\"",
         ["Ratatouille", "Cloudy with a Chance of Meatballs", "Kung Fu Panda", "Chef",
          "The Grand Budapest Hotel", "Julie & Julia"]),
        (.medium, "Which movie is this from? \"May the Force be with you.\"",
         ["Star Wars: Episode IV – A New Hope", "Star Trek", "Guardians of the Galaxy",
          "Men in Black", "The Fifth Element", "Interstellar"]),
        (.medium, "Which movie is this from? \"Life finds a way.\"",
         ["Jurassic Park", "Jurassic World", "King Kong", "Godzilla", "The Land Before Time", "Rio"]),
        (.medium, "Which movie is this from? \"Great Scott!\"",
         ["Back to the Future", "Doctor Strange", "Sherlock Holmes", "The Time Machine",
          "A Wrinkle in Time", "Hugo"]),
        (.medium, "Which movie is this from? \"Life is like a box of chocolates.\"",
         ["Forrest Gump", "Big", "The Sandlot", "Charlie and the Chocolate Factory", "Cast Away", "The Terminal"]),
        (.medium, "Which movie is this from? \"I feel the need... the need for speed.\"",
         ["Top Gun", "Cars", "Speed Racer", "The Fast and the Furious", "Rush", "Days of Thunder"]),
        (.medium, "Which movie is this from? \"Houston, we have a problem.\"",
         ["Apollo 13", "Gravity", "The Martian", "Interstellar", "Armageddon", "First Man"]),
        (.medium, "Which movie is this from? \"You shall not pass!\"",
         ["The Lord of the Rings: The Fellowship of the Ring", "The Hobbit: An Unexpected Journey",
          "Harry Potter and the Goblet of Fire", "Willow", "The Chronicles of Narnia", "Eragon"]),
        (.medium, "Which movie is this from? \"Not all treasure is silver and gold, mate.\"",
         ["Pirates of the Caribbean: The Curse of the Black Pearl", "Treasure Planet", "Hook",
          "Peter Pan", "The Goonies", "Moana"]),
        (.medium, "Which movie is this from? \"To boldly go where no man has gone before.\"",
         ["Star Trek", "Star Wars: Episode IV – A New Hope", "Interstellar",
          "Guardians of the Galaxy", "Lost in Space", "The Martian"]),
        (.medium, "Which movie is this from? \"I'm the king of the world!\"",
         ["Titanic", "Pearl Harbor", "The Aviator", "Master and Commander", "Gladiator", "Braveheart"]),
        (.medium, "Which movie is this from? \"Hasta la vista, baby.\"",
         ["Terminator 2: Judgment Day", "The Terminator", "RoboCop", "Predator", "Total Recall", "Commando"]),
        (.medium, "Which movie is this from? \"I'll be back.\"",
         ["The Terminator", "Terminator 2: Judgment Day", "RoboCop", "Predator", "Total Recall", "True Lies"]),
        (.medium, "Which movie is this from? \"Keep the change, ya filthy animal.\"",
         ["Home Alone", "Home Alone 2: Lost in New York", "The Sandlot", "Uncle Buck",
          "Angels in the Outfield", "Richie Rich"]),
        (.medium, "Which movie is this from? \"The best way to spread Christmas cheer is singing loud for all to hear.\"",
         ["Elf", "The Santa Clause", "How the Grinch Stole Christmas", "The Polar Express",
          "A Christmas Story", "Home Alone"]),
        (.hard, "Which movie is this from? \"It is our choices, Harry, that show what we truly are.\"",
         ["Harry Potter and the Chamber of Secrets", "Harry Potter and the Sorcerer's Stone",
          "The Chronicles of Narnia", "Star Wars: Episode V – The Empire Strikes Back",
          "The Hobbit", "Percy Jackson & the Olympians"]),
        (.hard, "Which movie is this from? \"I am inevitable.\"",
         ["Avengers: Endgame", "Avengers: Infinity War", "The Avengers", "Iron Man",
          "Guardians of the Galaxy", "Thor: Ragnarok"]),
        (.hard, "Which movie is this from? \"I see dead people.\"",
         ["The Sixth Sense", "Ghost", "Poltergeist", "Coco", "The Others", "Beetlejuice"]),
        (.hard, "Which movie is this from? \"You can't handle the truth!\"",
         ["A Few Good Men", "Twelve Angry Men", "My Cousin Vinny", "Erin Brockovich",
          "The Verdict", "Philadelphia"]),
        (.hard, "Which movie is this from? \"You had me at hello.\"",
         ["Jerry Maguire", "Notting Hill", "You've Got Mail", "Sleepless in Seattle",
          "While You Were Sleeping", "27 Dresses"]),
        (.hard, "Which movie is this from? \"Nobody puts Baby in a corner.\"",
         ["Dirty Dancing", "Footloose", "Flashdance", "Grease", "Save the Last Dance", "Step Up"]),
        (.hard, "Which movie is this from? \"Bueller? Bueller?\"",
         ["Ferris Bueller's Day Off", "Fast Times at Ridgemont High", "The Breakfast Club",
          "Sixteen Candles", "Clueless", "Napoleon Dynamite"]),
        (.hard, "Which movie is this from? \"Here's looking at you, kid.\"",
         ["Casablanca", "Gone with the Wind", "Roman Holiday", "An Affair to Remember",
          "Breakfast at Tiffany's", "North by Northwest"]),
        (.hard, "Which movie is this from? \"I'll have what she's having.\"",
         ["When Harry Met Sally", "Sleepless in Seattle", "Annie Hall", "You've Got Mail",
          "The Princess Bride", "Groundhog Day"]),
        (.hard, "Which movie is this from? \"You're gonna need a bigger boat.\"",
         ["Jaws", "Jaws 2", "The Perfect Storm", "Deep Blue Sea", "The Meg", "Moby Dick"]),
        (.hard, "Which movie is this from? \"Yippee-ki-yay!\"",
         ["Die Hard", "Die Hard 2", "Lethal Weapon", "RoboCop", "The Fifth Element", "Speed"]),
    ])
}
