//
//  SeedQuestions.swift
//  Travel Trivia
//
//  The bundled starter packs: Riddle Realm, Would You Rather, and Movie
//  Quote Mashup. The same content is seeded into the Supabase `questions`
//  table (see supabase/migrations); these local copies keep every seeded
//  genre fully playable offline.
//

import Foundation

nonisolated enum SeedQuestions {
    /// Every genre with bundled content, by slug — the single source for
    /// "does this genre have questions yet".
    static let packs: [String: [TriviaQuestion]] = [
        "riddle-realm": riddleRealm,
        "would-you-rather": wouldYouRather,
        "movie-quote-mashup": movieQuoteMashup,
        "globe-trotter-clues": globeTrotterClues,
        "mythical-creatures-legends": mythicalCreaturesLegends,
        "random-acts-of-weird-facts": randomActsOfWeirdFacts,
        "superlative-showdown": superlativeShowdown,
        "time-machine": timeMachine,
        "pop-culture-time-capsule": popCultureTimeCapsule,
    ]

    /// First authored option is the correct one (shuffled at deal time);
    /// prediction packs pass `fixedAnswer: false` and leave correctness to
    /// the party's majority vote.
    private static func build(prefix: String, fixedAnswer: Bool,
                              _ entries: [(Difficulty, String, [String])]) -> [TriviaQuestion] {
        entries.enumerated().map { index, entry in
            let number = index + 1
            let options = entry.2.enumerated().map { optionIndex, text in
                AnswerOption(id: "\(prefix)-\(number)-\(optionIndex)", text: text)
            }
            return TriviaQuestion(
                id: "\(prefix)-\(number)",
                difficulty: entry.0,
                prompt: entry.1,
                options: options,
                correctOptionID: fixedAnswer ? options[0].id : nil
            )
        }
    }
    static let riddleRealm: [TriviaQuestion] = {
        func question(_ number: Int, _ difficulty: Difficulty, _ prompt: String,
                      _ optionTexts: [String]) -> TriviaQuestion {
            // First authored option is always the correct one; display order
            // is shuffled at game start.
            let options = optionTexts.enumerated().map { index, text in
                AnswerOption(id: "riddle-\(number)-\(index)", text: text)
            }
            return TriviaQuestion(
                id: "riddle-\(number)",
                difficulty: difficulty,
                prompt: prompt,
                options: options,
                correctOptionID: options[0].id
            )
        }

        return [
            question(1, .easy, "I have keys but no locks, space but no room — you can enter, but not go outside. What am I?",
                     ["Keyboard", "House", "Piano", "Map", "Wallet", "Elevator"]),
            question(2, .easy, "What has hands but can't clap?",
                     ["Clock", "Glove", "Statue", "Robot", "Watch", "Mannequin"]),
            question(3, .easy, "What has a neck but no head?",
                     ["Bottle", "Shirt", "Guitar", "Turtle", "Violin", "Sweater"]),
            question(4, .easy, "What gets wetter the more it dries?",
                     ["Towel", "Sponge", "Rain", "Ocean", "Washcloth", "Umbrella"]),
            question(5, .easy, "What has to be broken before you can use it?",
                     ["Egg", "Promise", "Record", "Seal", "Piggy Bank", "Code"]),
            question(6, .easy, "What has one eye but can't see?",
                     ["Needle", "Storm", "Potato", "Cat", "Hurricane", "Button"]),
            question(7, .medium, "I speak without a mouth, hear without ears, and come alive with the wind. What am I?",
                     ["Echo", "Ghost", "Shadow", "Whisper", "Wind", "Radio"]),
            question(8, .medium, "What comes once in a minute, twice in a moment, but never in a thousand years?",
                     ["Letter M", "Heartbeat", "Blink", "Second", "Letter N", "Minute Hand"]),
            question(9, .medium, "I'm tall when I'm young and short when I'm old. What am I?",
                     ["Candle", "Tree", "Person", "Pencil", "Match", "Crayon"]),
            question(10, .medium, "What can travel around the world while staying in a corner?",
                     ["Stamp", "Map", "Globe", "Coin", "Postcard", "Sticker"]),
            question(11, .medium, "What building has the most stories?",
                     ["Library", "Skyscraper", "Museum", "School", "Bookstore", "Apartment"]),
            question(12, .medium, "What's full of holes but still holds water?",
                     ["Sponge", "Net", "Colander", "Cloud", "Sieve", "Screen"]),
            question(13, .hard, "I'm not alive, but I grow. I don't have lungs, but I need air. I don't have a mouth, but water kills me. What am I?",
                     ["Fire", "Plant", "Cloud", "Ice", "Smoke", "Steam"]),
            question(14, .hard, "What has many teeth but cannot bite?",
                     ["Comb", "Saw", "Zipper", "Gear", "Rake", "Fork"]),
            question(15, .hard, "I shave every day, but my beard stays the same. What am I?",
                     ["Barber", "Werewolf", "Goat", "Father Time", "Lumberjack", "Santa"]),
            question(16, .hard, "The more you take, the more you leave behind. What am I?",
                     ["Footsteps", "Time", "Memories", "Breath", "Shadow", "Age"]),
        ]
    }()

    // MARK: - Would You Rather (prediction: majority vote becomes correct)

    static let wouldYouRather: [TriviaQuestion] = build(prefix: "wyr", fixedAnswer: false, [
        (.easy, "Which car mishap would be the WORST right now?",
         ["AC breaks in July", "Fries in every seat crack", "GPS stuck \"recalculating\" for 3 hours",
          "Carsick sibling in the back", "Every phone charger dies", "Flat tire 50 miles from town"]),
        (.easy, "Which power would help this trip the most?",
         ["Teleport past traffic", "X-ray vision for rest stops", "Talk to animals",
          "Control the weather", "Super speed", "Turn invisible to skip gas station lines"]),
        (.medium, "If the car transformed into one of these for the rest of the trip...",
         ["Hot air balloon", "Submarine", "Monster truck",
          "Go-kart", "Rocket ship", "Horse-drawn carriage"]),
        (.easy, "Which snack disaster would ruin the car fastest?",
         ["Melted chocolate on seats", "Spilled milkshake in the cupholder", "Exploding popcorn",
          "Burst ketchup packet", "Melted gummy bears in the carpet", "Crushed chip bag underfoot"]),
        (.medium, "Which surprise stop would you most want the driver to make?",
         ["Roadside dinosaur statue", "Giant ball of twine", "Drive-in movie theater",
          "Ice cream stand", "Petting zoo", "Fireworks store"]),
        (.easy, "Which road trip soundtrack would you be stuck with for 6 hours?",
         ["Polka music", "Whale sounds", "One song on repeat",
          "A podcast about tax law", "Bagpipes", "Elevator music"]),
        (.medium, "Which unexpected passenger would make the trip the most interesting?",
         ["A talking parrot", "A magician", "A famous chef",
          "A ghost", "A stand-up comedian", "A fortune teller"]),
        (.easy, "Which weather would you least want to drive through?",
         ["A hailstorm", "Thick fog", "A sandstorm",
          "A heat wave with no AC", "A sudden blizzard", "A swarm of bugs on the windshield"]),
        (.medium, "Which roadside attraction detour would be worth the extra hour?",
         ["World's largest ball of yarn", "A haunted motel", "A UFO museum",
          "A cheese factory tour", "An alligator farm", "A mirror maze"]),
        (.medium, "Which car game would you be forced to play for the next 2 hours?",
         ["I Spy with zero good options", "20 Questions with a cheater", "Punch Buggy but everyone's aggressive",
          "License plate bingo", "Would You Rather (very meta)", "Silent staring contest"]),
        (.medium, "Which pit stop food would you actually be excited to eat?",
         ["Gas station sushi", "A giant turkey leg", "Mystery gas station hot dog",
          "A questionable burrito", "Truck stop pancakes", "A whole rotisserie chicken"]),
        (.hard, "Which navigator mistake would send you the most off course?",
         ["Reading the map upside down", "Trusting a psychic instead of GPS", "Following a \"shortcut\" through a cornfield",
          "Arguing with the GPS voice", "Using a map from 1998", "Following another car that looked \"confident\""]),
        (.easy, "Which animal would you least want to spot crossing the road ahead?",
         ["A moose", "An escaped zoo lion", "A herd of turtles",
          "A giant tumbleweed monster", "A peacock", "A confused ostrich"]),
        (.easy, "Which car smell would be hardest to survive for 6 hours?",
         ["Wet dog", "Old gym socks", "Durian fruit",
          "Burnt popcorn", "Gas station coffee gone bad", "A skunk that got a little too close"]),
        (.hard, "Which vacation would you rather accidentally end up on?",
         ["A cruise full of clowns", "A silent meditation retreat", "A haunted castle tour",
          "A competitive cheese-rolling festival", "A week at a llama farm", "A convention for people who love traffic cones"]),
        (.medium, "Which \"are we there yet\" answer would be the most annoying?",
         ["\"Ask me again in an hour\"", "A random riddle instead of an answer", "Complete silence",
          "\"We'll never get there\" (joking, hopefully)", "A math problem you have to solve first", "The GPS voice answering instead"]),
        (.medium, "Which emergency kit item would you actually need most on this trip?",
         ["A tiny umbrella", "An inflatable raft", "A whistle",
          "A disguise kit", "A magic 8-ball", "A portable karaoke machine"]),
        (.easy, "Which car temperature disaster would you rather deal with?",
         ["So hot the seats are lava", "So cold you can see your breath", "Only the driver's seat has AC",
          "Heated seats stuck on in summer", "One window stuck wide open", "The AC only blows at your feet"]),
        (.medium, "Which unexpected road trip companion sound would drive you craziest?",
         ["Someone humming off-key nonstop", "A squeaky seat that won't stop", "Someone narrating everything they see",
          "A phone stuck on the lowest possible volume ringtone", "Someone cracking their knuckles constantly", "A GPS that mispronounces every street name"]),
        (.medium, "Which type of rest stop bathroom would you dread most?",
         ["One with no soap", "One that's a 10-minute walk from the car", "One with a line around the building",
          "One that's suspiciously spotless (too clean, feels like a trap)", "One with only cold water", "One where the door doesn't lock"]),
        (.hard, "Which time period would you least want this road trip to take place in?",
         ["The 1800s (horse and wagon)", "The Stone Age", "The far future with flying cars you can't drive",
          "Medieval times", "The Ice Age", "A world with no roads at all yet"]),
        (.medium, "Which car breakdown would be the most inconvenient?",
         ["Dead battery at a scenic overlook", "Flat tire in a thunderstorm", "Out of gas in the middle of nowhere",
          "Engine trouble right before a big stop", "A door that won't open", "The trunk popping open on the highway"]),
        (.hard, "Which mythical creature would you least want to see out the car window?",
         ["A dragon circling overhead", "A troll blocking a bridge", "A sea monster in a lake you're passing",
          "A werewolf at a rest stop", "A giant spider web across the road", "A ghost hitchhiker"]),
        (.easy, "Which car chore would you least want to be stuck doing at the next stop?",
         ["Cleaning out the trash bag", "Untangling all the charging cables", "Refilling everyone's water bottles",
          "Wiping bug guts off the windshield", "Reorganizing the trunk", "Finding the one shoe that rolled under a seat"]),
        (.hard, "Which map mishap would send you the most off course?",
         ["Following an outdated paper map", "Trusting a GPS with a dead battery", "Taking directions from a stranger at a gas station",
          "Misreading \"north\" as \"south\"", "A GPS voice that keeps changing languages", "Following a bird because it \"looked confident\""]),
        (.medium, "Which car playlist would you be forced to listen to on repeat?",
         ["Nothing but car alarm sounds", "A single 45-minute song", "Whale songs",
          "A playlist of just sneezes", "An audiobook read in a monotone", "Dial-up internet sounds"]),
        (.hard, "Which unplanned overnight stop would be the most memorable?",
         ["A haunted-looking motel", "Sleeping in the car at a rest stop", "A campsite with no bathrooms nearby",
          "A tiny inn run by a very chatty owner", "A stranger's guest room after their kind offer", "A 24-hour diner booth"]),
        (.medium, "Which co-pilot mistake would cause the most chaos?",
         ["Falling asleep mid-directions", "Confidently giving wrong directions", "Spilling the entire snack bag",
          "Losing the phone charger", "Accidentally locking the doors while parked", "Turning on the hazard lights instead of the blinker"]),
        (.medium, "Which car superstition would you actually follow on this trip?",
         ["Holding your breath through every tunnel", "Touching the roof when you pass a yellow car", "Not saying \"flat tire\" out loud",
          "Making a wish at every state line", "Waving at every trucker", "Counting cows until you pass a graveyard"]),
        (.easy, "Which sudden detour sign would make you the most curious?",
         ["\"World's Smallest Church, 2 Miles\"", "\"Free Kittens\"", "\"Mystery Spot Ahead\"",
          "\"Home of the Giant Rubber Duck\"", "\"Haunted Bridge, Proceed with Caution\"", "\"Best Pie in 3 States\""]),
        (.easy, "Which car snack would you regret bringing the most?",
         ["Extra garlicky chips", "A whole durian", "Warm milk in a thermos",
          "Crumbly crackers everywhere", "Gum that lost its flavor in 2 minutes", "A soda that's mostly foam"]),
        (.medium, "Which family road trip tradition would you keep forever?",
         ["A \"first one to see the ocean\" shout", "A silly nickname for every gas station", "A road trip photo at every state sign",
          "A car karaoke hour", "A snack rotation system", "A \"guess the mileage\" game"]),
        (.hard, "Which unexpected road hazard would slow you down the most?",
         ["A parade crossing the highway", "A herd of cows on the road", "A marching band rehearsal",
          "A film crew blocking one lane", "A hot air balloon landing in the road", "A runaway inflatable bounce house"]),
        (.easy, "Which car nap position would you be stuck with for hours?",
         ["Head against the window (every bump)", "Neck at a painful angle", "Sitting bolt upright",
          "Squished in the middle seat", "Feet up on the dashboard", "Using a sibling's shoulder (against their will)"]),
        (.medium, "Which \"we're lost\" moment would be the most stressful?",
         ["No cell signal and no map", "A GPS that keeps rerouting in circles", "Running low on gas while lost",
          "It's getting dark and you're still lost", "Everyone in the car has a different opinion on where to go", "The one person who knows the way is asleep"]),
        (.medium, "Which travel-sized version of something would you be most annoyed to be stuck with?",
         ["A travel pillow that deflates", "A phone charger that barely reaches", "A tiny bag of chips that's mostly air",
          "A pocket-sized umbrella in a downpour", "A mini flashlight with a dying battery", "A sample-sized bottle of sunscreen for a whole beach day"]),
        (.easy, "Which type of traffic jam would test your patience the most?",
         ["One caused by nothing you can see", "One next to a very slow ice cream truck", "One where everyone's honking for no reason",
          "One caused by a spilled truckload of something silly", "One where your exit is juuust ahead", "One caused by a very confused goose"]),
        (.medium, "Which car repair would you be least equipped to handle yourselves?",
         ["A flat tire with no spare", "A dead battery with no jumper cables", "A check engine light with no manual",
          "A cracked windshield mid-drive", "An overheating engine", "A broken AC in the middle of summer"]),
        (.medium, "Which \"roughing it\" camping surprise would you handle worst?",
         ["No cell signal for 3 days", "A raccoon raiding the snacks", "Rain on the one night you forgot the tarp",
          "A tent that's suspiciously smaller than advertised", "Bugs everywhere at sunset", "Realizing you forgot the marshmallows"]),
        (.hard, "Which final stretch of the trip would drag the most?",
         ["The last hour with everyone asleep but you", "The last hour stuck behind a slow truck", "The last hour with a full bladder and no exit",
          "The last hour of a sibling asking \"are we there yet\"", "The last hour in bumper-to-bumper traffic", "The last hour realizing you're going the wrong way"]),
    ])

    // MARK: - Movie Quote Mashup (first authored option is the answer)

    static let movieQuoteMashup: [TriviaQuestion] = build(prefix: "mqm", fixedAnswer: true, [
        (.easy, "Which movie is this from? \"To infinity and beyond!\"",
         ["Toy Story", "Cars", "The Incredibles", "Monsters, Inc.", "Finding Nemo", "Shrek"]),
        (.easy, "Which movie is this from? \"Just keep swimming.\"",
         ["Finding Nemo", "Moana", "The Little Mermaid", "Shark Tale", "Free Willy", "Finding Dory"]),
        (.easy, "Which movie is this from? \"Hakuna Matata, what a wonderful phrase.\"",
         ["The Lion King", "Madagascar", "Zootopia", "Tarzan", "The Jungle Book", "Ice Age"]),
        (.easy, "Which movie is this from? \"There's no place like home.\"",
         ["The Wizard of Oz", "Alice in Wonderland", "Peter Pan", "Mary Poppins",
          "Charlie and the Chocolate Factory", "The Chronicles of Narnia"]),
        (.easy, "Which movie is this from? \"You're a wizard, Harry.\"",
         ["Harry Potter and the Sorcerer's Stone", "The Chronicles of Narnia", "The Hobbit",
          "Percy Jackson & the Olympians", "Fantastic Beasts and Where to Find Them", "Shrek"]),
        (.easy, "Which movie is this from? \"It's so fluffy I'm gonna die!\"",
         ["Despicable Me", "Minions", "The Secret Life of Pets", "Hop", "Sing", "Trolls"]),
        (.easy, "Which movie is this from? \"Bibbidi-Bobbidi-Boo.\"",
         ["Cinderella", "Sleeping Beauty", "Snow White and the Seven Dwarfs", "Frozen", "Enchanted", "Tangled"]),
        (.easy, "Which movie is this from? \"E.T. phone home.\"",
         ["E.T. the Extra-Terrestrial", "Close Encounters of the Third Kind", "Lilo & Stitch",
          "Flight of the Navigator", "Mars Attacks", "Paul"]),
        (.easy, "Which movie is this from? \"With great power comes great responsibility.\"",
         ["Spider-Man", "Batman Begins", "Iron Man", "Superman", "The Incredibles", "Big Hero 6"]),
        (.easy, "Which movie is this from? \"Ogres are like onions.\"",
         ["Shrek", "Puss in Boots", "Trolls", "Hotel Transylvania", "The Princess Bride", "Ella Enchanted"]),
        (.easy, "Which movie is this from? \"Some people are worth melting for.\"",
         ["Frozen", "Frozen II", "Ice Age", "Happy Feet", "The Snowman", "Klaus"]),
        (.easy, "Which movie is this from? \"The ocean chose you.\"",
         ["Moana", "Aquaman", "The Little Mermaid", "Finding Nemo", "Pirates of the Caribbean", "Life of Pi"]),
        (.easy, "Which movie is this from? \"No capes!\"",
         ["The Incredibles", "Sky High", "Big Hero 6", "Megamind", "Despicable Me", "The Boy and the Heron"]),
        (.easy, "Which movie is this from? \"Adventure is out there!\"",
         ["Up", "The Secret Life of Walter Mitty", "Onward", "Brave", "The Jungle Book", "Coco"]),
        (.easy, "Which movie is this from? \"Anyone can cook.\"",
         ["Ratatouille", "Cloudy with a Chance of Meatballs", "Kung Fu Panda", "Chef",
          "The Grand Budapest Hotel", "Julie & Julia"]),
        (.medium, "Which movie is this from? \"May the Force be with you.\"",
         ["Star Wars: Episode IV – A New Hope", "Star Trek", "Guardians of the Galaxy",
          "Men in Black", "The Fifth Element", "Interstellar"]),
        (.medium, "Which movie is this from? \"Life finds a way.\"",
         ["Jurassic Park", "Jurassic World", "King Kong", "Godzilla", "The Land Before Time", "Rio"]),
        (.medium, "Which movie is this from? \"Great Scott!\"",
         ["Back to the Future", "Doctor Strange", "Sherlock Holmes", "The Time Machine",
          "A Wrinkle in Time", "Hugo"]),
        (.medium, "Which movie is this from? \"Life is like a box of chocolates.\"",
         ["Forrest Gump", "Big", "The Sandlot", "Charlie and the Chocolate Factory", "Cast Away", "The Terminal"]),
        (.medium, "Which movie is this from? \"I feel the need... the need for speed.\"",
         ["Top Gun", "Cars", "Speed Racer", "The Fast and the Furious", "Rush", "Days of Thunder"]),
        (.medium, "Which movie is this from? \"Houston, we have a problem.\"",
         ["Apollo 13", "Gravity", "The Martian", "Interstellar", "Armageddon", "First Man"]),
        (.medium, "Which movie is this from? \"You shall not pass!\"",
         ["The Lord of the Rings: The Fellowship of the Ring", "The Hobbit: An Unexpected Journey",
          "Harry Potter and the Goblet of Fire", "Willow", "The Chronicles of Narnia", "Eragon"]),
        (.medium, "Which movie is this from? \"Not all treasure is silver and gold, mate.\"",
         ["Pirates of the Caribbean: The Curse of the Black Pearl", "Treasure Planet", "Hook",
          "Peter Pan", "The Goonies", "Moana"]),
        (.medium, "Which movie is this from? \"To boldly go where no man has gone before.\"",
         ["Star Trek", "Star Wars: Episode IV – A New Hope", "Interstellar",
          "Guardians of the Galaxy", "Lost in Space", "The Martian"]),
        (.medium, "Which movie is this from? \"I'm the king of the world!\"",
         ["Titanic", "Pearl Harbor", "The Aviator", "Master and Commander", "Gladiator", "Braveheart"]),
        (.medium, "Which movie is this from? \"Hasta la vista, baby.\"",
         ["Terminator 2: Judgment Day", "The Terminator", "RoboCop", "Predator", "Total Recall", "Commando"]),
        (.medium, "Which movie is this from? \"I'll be back.\"",
         ["The Terminator", "Terminator 2: Judgment Day", "RoboCop", "Predator", "Total Recall", "True Lies"]),
        (.medium, "Which movie is this from? \"Keep the change, ya filthy animal.\"",
         ["Home Alone", "Home Alone 2: Lost in New York", "The Sandlot", "Uncle Buck",
          "Angels in the Outfield", "Richie Rich"]),
        (.medium, "Which movie is this from? \"The best way to spread Christmas cheer is singing loud for all to hear.\"",
         ["Elf", "The Santa Clause", "How the Grinch Stole Christmas", "The Polar Express",
          "A Christmas Story", "Home Alone"]),
        (.hard, "Which movie is this from? \"It is our choices, Harry, that show what we truly are.\"",
         ["Harry Potter and the Chamber of Secrets", "Harry Potter and the Sorcerer's Stone",
          "The Chronicles of Narnia", "Star Wars: Episode V – The Empire Strikes Back",
          "The Hobbit", "Percy Jackson & the Olympians"]),
        (.hard, "Which movie is this from? \"I am inevitable.\"",
         ["Avengers: Endgame", "Avengers: Infinity War", "The Avengers", "Iron Man",
          "Guardians of the Galaxy", "Thor: Ragnarok"]),
        (.hard, "Which movie is this from? \"I see dead people.\"",
         ["The Sixth Sense", "Ghost", "Poltergeist", "Coco", "The Others", "Beetlejuice"]),
        (.hard, "Which movie is this from? \"You can't handle the truth!\"",
         ["A Few Good Men", "Twelve Angry Men", "My Cousin Vinny", "Erin Brockovich",
          "The Verdict", "Philadelphia"]),
        (.hard, "Which movie is this from? \"You had me at hello.\"",
         ["Jerry Maguire", "Notting Hill", "You've Got Mail", "Sleepless in Seattle",
          "While You Were Sleeping", "27 Dresses"]),
        (.hard, "Which movie is this from? \"Nobody puts Baby in a corner.\"",
         ["Dirty Dancing", "Footloose", "Flashdance", "Grease", "Save the Last Dance", "Step Up"]),
        (.hard, "Which movie is this from? \"Bueller? Bueller?\"",
         ["Ferris Bueller's Day Off", "Fast Times at Ridgemont High", "The Breakfast Club",
          "Sixteen Candles", "Clueless", "Napoleon Dynamite"]),
        (.hard, "Which movie is this from? \"Here's looking at you, kid.\"",
         ["Casablanca", "Gone with the Wind", "Roman Holiday", "An Affair to Remember",
          "Breakfast at Tiffany's", "North by Northwest"]),
        (.hard, "Which movie is this from? \"I'll have what she's having.\"",
         ["When Harry Met Sally", "Sleepless in Seattle", "Annie Hall", "You've Got Mail",
          "The Princess Bride", "Groundhog Day"]),
        (.hard, "Which movie is this from? \"You're gonna need a bigger boat.\"",
         ["Jaws", "Jaws 2", "The Perfect Storm", "Deep Blue Sea", "The Meg", "Moby Dick"]),
        (.hard, "Which movie is this from? \"Yippee-ki-yay!\"",
         ["Die Hard", "Die Hard 2", "Lethal Weapon", "RoboCop", "The Fifth Element", "Speed"]),
    ])

    // MARK: - Globe-Trotter Clues (3 escalating clues joined into one prompt, then 6 location options)

    static let globeTrotterClues: [TriviaQuestion] = build(prefix: "gtc", fixedAnswer: true, [
        (.hard, "I'm home to more pyramids than Egypt.\nMy capital sits along the Nile, way south of Cairo.\nMy ancient kingdom was called Kush.",
         ["Sudan", "Egypt", "Ethiopia", "Kenya", "Libya", "Chad"]),
        (.easy, "I'm shaped like a boot's little cousin.\nI'm famous for volcanoes, ancient ruins, and incredible pasta.\nMy capital is Rome.",
         ["Italy", "Greece", "Spain", "Portugal", "Croatia", "Turkey"]),
        (.easy, "I'm the world's largest country by area.\nI span 11 time zones.\nMy capital is Moscow.",
         ["Russia", "Canada", "China", "USA", "Brazil", "Australia"]),
        (.easy, "I'm a country entirely on one continent that's also my name.\nI'm home to kangaroos and the Great Barrier Reef.\nMy capital is Canberra, not Sydney.",
         ["Australia", "New Zealand", "South Africa", "Brazil", "Indonesia", "Fiji"]),
        (.easy, "I'm known as the Land of the Rising Sun.\nI have more vending machines per person than almost anywhere else.\nMy capital is Tokyo.",
         ["Japan", "South Korea", "China", "Thailand", "Vietnam", "Taiwan"]),
        (.medium, "I'm home to the tallest mountain on Earth.\nI sit between India and China.\nMy capital is Kathmandu.",
         ["Nepal", "Bhutan", "Tibet", "Pakistan", "Mongolia", "Myanmar"]),
        (.easy, "I'm famous for a giant clock tower people often call by the wrong name.\nI drive on the left side of the road.\nMy capital is London.",
         ["United Kingdom", "Ireland", "Australia", "Canada", "South Africa", "New Zealand"]),
        (.easy, "A maple leaf describes me well.\nI'm the second-largest country in the world by area.\nMy capital is Ottawa, not Toronto.",
         ["Canada", "USA", "Russia", "Greenland", "Mexico", "Norway"]),
        (.medium, "I'm home to the largest rainforest on Earth.\nSoccer is basically a religion here.\nMy capital is Brasília, not Rio de Janeiro.",
         ["Brazil", "Argentina", "Peru", "Colombia", "Venezuela", "Ecuador"]),
        (.hard, "I'm a chain of over 17,000 islands.\nI'm the largest Muslim-majority country in the world.\nMy capital is Jakarta.",
         ["Indonesia", "Philippines", "Malaysia", "Thailand", "Vietnam", "India"]),
        (.easy, "I'm famous for the Eiffel Tower and croissants.\nI'm shaped roughly like a hexagon.\nMy capital is Paris.",
         ["France", "Belgium", "Switzerland", "Spain", "Germany", "Italy"]),
        (.medium, "I'm the only country that's also an entire continent.\nI'm home to more sheep than people.\nMy capital is Canberra.",
         ["Australia", "New Zealand", "Antarctica", "Greenland", "Iceland", "Madagascar"]),
        (.easy, "I'm known for the Great Wall.\nI have the world's largest population.\nMy capital is Beijing.",
         ["China", "India", "Mongolia", "Japan", "South Korea", "Vietnam"]),
        (.hard, "I'm home to the Sahara, the world's largest hot desert.\nI'm the largest country in Africa by area.\nMy capital is Algiers.",
         ["Algeria", "Libya", "Egypt", "Morocco", "Sudan", "Chad"]),
        (.medium, "I'm a small European country famous for chocolate, waffles, and beer.\nI host the headquarters of the EU.\nMy capital is Brussels.",
         ["Belgium", "Netherlands", "Switzerland", "Luxembourg", "Austria", "Germany"]),
        (.hard, "I'm the world's largest island that isn't also a continent.\nMost of me is covered in ice.\nI'm technically part of the Kingdom of Denmark.",
         ["Greenland", "Iceland", "Svalbard", "Antarctica", "Baffin Island", "Madagascar"]),
        (.medium, "I'm home to the Great Barrier Reef.\nI have more venomous animals than anywhere else on Earth.\nMy capital is Canberra.",
         ["Australia", "Indonesia", "Papua New Guinea", "Philippines", "Fiji", "New Zealand"]),
        (.easy, "I'm a country famous for the Taj Mahal.\nI have the second-largest population in the world.\nMy capital is New Delhi.",
         ["India", "Pakistan", "Bangladesh", "Nepal", "Sri Lanka", "China"]),
        (.medium, "I'm home to Machu Picchu, high in the Andes.\nThe ancient Inca Empire was centered here.\nMy capital is Lima.",
         ["Peru", "Bolivia", "Ecuador", "Chile", "Colombia", "Argentina"]),
        (.easy, "I'm made up of over 5,000 named islands.\nI'm known for cherry blossoms and bullet trains.\nMy capital is Tokyo.",
         ["Japan", "Philippines", "Indonesia", "South Korea", "Taiwan", "Greece"]),
        (.hard, "I'm home to the world's tallest building.\nI'm a desert country known for indoor ski slopes.\nMy capital is Abu Dhabi, not Dubai.",
         ["United Arab Emirates", "Qatar", "Saudi Arabia", "Kuwait", "Oman", "Bahrain"]),
        (.hard, "I'm a landlocked country in the Alps famous for chocolate and watches.\nI have four official languages.\nMy capital is Bern, not Zurich.",
         ["Switzerland", "Austria", "Liechtenstein", "Germany", "Belgium", "Slovenia"]),
        (.easy, "I'm the birthplace of the Olympic Games.\nI'm known for ancient ruins and thousands of islands.\nMy capital is Athens.",
         ["Greece", "Italy", "Turkey", "Cyprus", "Egypt", "Malta"]),
        (.easy, "I'm famous for tacos, mariachi music, and ancient pyramids.\nI share a long border with the United States.\nMy capital is Mexico City.",
         ["Mexico", "Guatemala", "Belize", "Cuba", "Colombia", "Honduras"]),
        (.hard, "I'm home to Mount Kilimanjaro, Africa's tallest peak.\nThe Serengeti and its wildebeest migration are here.\nMy capital is Dodoma, not Dar es Salaam.",
         ["Tanzania", "Kenya", "Uganda", "Zambia", "Mozambique", "Ethiopia"]),
        (.medium, "I'm known for Vikings, fjords, and the Northern Lights.\nI'm one of the happiest countries in the world, year after year.\nMy capital is Oslo.",
         ["Norway", "Sweden", "Finland", "Denmark", "Iceland", "Greenland"]),
        (.medium, "I'm split almost exactly in half by a famous wall that came down in 1989.\nI'm known for sausages, beer, and precision engineering.\nMy capital is Berlin.",
         ["Germany", "Austria", "Poland", "Czech Republic", "Switzerland", "Netherlands"]),
        (.hard, "I'm home to the world's driest non-polar desert.\nI'm an incredibly long, narrow country running down South America's west coast.\nMy capital is Santiago.",
         ["Chile", "Peru", "Argentina", "Bolivia", "Ecuador", "Uruguay"]),
        (.hard, "I'm a small country entirely surrounded by South Africa.\nMy name is almost a common English word.\nMy capital is Maseru.",
         ["Lesotho", "Eswatini", "Botswana", "Namibia", "Zimbabwe", "Malawi"]),
        (.medium, "I'm famous for the Northern Lights, hot dogs, and being one of the happiest places on Earth.\nI'm not actually that icy despite my name.\nMy capital is Reykjavik.",
         ["Iceland", "Greenland", "Norway", "Finland", "Denmark", "Sweden"]),
    ])

    // MARK: - Mythical Creatures & Legends

    static let mythicalCreaturesLegends: [TriviaQuestion] = build(prefix: "myth", fixedAnswer: true, [
        (.medium, "Which creature is said to turn people to stone with its gaze?",
         ["Basilisk", "Griffin", "Chimera", "Sphinx", "Kraken", "Cerberus"]),
        (.easy, "In Greek mythology, what is the three-headed dog guarding the underworld?",
         ["Cerberus", "Hydra", "Chimera", "Minotaur", "Cyclops", "Pegasus"]),
        (.easy, "What legendary creature is half-man, half-horse?",
         ["Centaur", "Minotaur", "Satyr", "Faun", "Griffin", "Sphinx"]),
        (.easy, "What flying horse sprang from Medusa's blood?",
         ["Pegasus", "Chiron", "Bucephalus", "Sleipnir", "Unicorn", "Griffin"]),
        (.easy, "Which legendary creature is said to live in Loch Ness?",
         ["The Loch Ness Monster", "The Kraken", "Leviathan", "Jörmungandr", "Bunyip", "Mokele-mbembe"]),
        (.medium, "What giant sea monster attacks ships in Scandinavian folklore?",
         ["The Kraken", "Leviathan", "Jörmungandr", "Charybdis", "Scylla", "Cthulhu"]),
        (.easy, "In Egyptian mythology, what creature has a lion's body and human head?",
         ["Sphinx", "Griffin", "Chimera", "Anubis", "Ammit", "Bastet"]),
        (.easy, "What mythical bird bursts into flames and is reborn from its ashes?",
         ["Phoenix", "Roc", "Thunderbird", "Griffin", "Simurgh", "Harpy"]),
        (.hard, "In Norse mythology, what giant wolf is destined to kill Odin?",
         ["Fenrir", "Jörmungandr", "Sleipnir", "Garm", "Hati", "Skoll"]),
        (.hard, "What shape-shifting Scottish water horse lures people into lakes?",
         ["Kelpie", "Selkie", "Banshee", "Nix", "Bunyip", "Naiad"]),
        (.easy, "What legendary giant ape is said to live in the Himalayas?",
         ["Yeti", "Sasquatch", "Bigfoot", "Wendigo", "Chupacabra", "Skunk Ape"]),
        (.easy, "What's the North American legendary creature also known as Bigfoot?",
         ["Sasquatch", "Yeti", "Wendigo", "Jackalope", "Chupacabra", "Mothman"]),
        (.medium, "In Greek mythology, what creature is part lion, part goat, part serpent?",
         ["Chimera", "Sphinx", "Hydra", "Griffin", "Cerberus", "Minotaur"]),
        (.easy, "What creature has a lion's body and an eagle's head and wings?",
         ["Griffin", "Sphinx", "Chimera", "Phoenix", "Hippogriff", "Roc"]),
        (.easy, "Which horned horse-like creature is a symbol of purity in legend?",
         ["Unicorn", "Pegasus", "Kirin", "Centaur", "Hippocampus", "Alicorn"]),
        (.easy, "What man-eating half-bull, half-man creature is trapped in a labyrinth?",
         ["Minotaur", "Centaur", "Satyr", "Chimera", "Cyclops", "Cerberus"]),
        (.easy, "What legendary sea creatures lure sailors with their songs?",
         ["Sirens", "Mermaids", "Nymphs", "Naiads", "Selkies", "Nereids"]),
        (.medium, "What multi-headed serpent grows two heads for every one cut off?",
         ["The Hydra", "The Chimera", "Jörmungandr", "The Basilisk", "Typhon", "Ladon"]),
        (.medium, "In Japanese folklore, what fox spirit has shapeshifting powers?",
         ["Kitsune", "Tanuki", "Oni", "Tengu", "Yokai", "Kappa"]),
        (.hard, "What trickster water spirit in Japanese folklore lures people into rivers?",
         ["Kappa", "Kitsune", "Oni", "Tengu", "Yurei", "Baku"]),
        (.easy, "In Slavic folklore, what undead being rises from the grave to drink blood?",
         ["Vampire", "Ghoul", "Wraith", "Banshee", "Lich", "Zombie"]),
        (.medium, "What Irish fairy woman's wailing is said to predict death?",
         ["Banshee", "Leprechaun", "Pooka", "Selkie", "Kelpie", "Changeling"]),
        (.easy, "What small, treasure-hoarding fairy is tied to Irish folklore and rainbows?",
         ["Leprechaun", "Banshee", "Pixie", "Gnome", "Brownie", "Sprite"]),
        (.hard, "What creature is a seal that can shed its skin to become human?",
         ["Selkie", "Kelpie", "Mermaid", "Naiad", "Siren", "Nix"]),
        (.easy, "In Chinese mythology, what powerful creature symbolizes luck and the emperor?",
         ["The Dragon", "The Phoenix", "The Qilin", "The Kirin", "The Tiger", "The Turtle"]),
        (.hard, "What single-horned creature appears only during times of peace in Chinese/Japanese myth?",
         ["Qilin", "Kirin", "Dragon", "Phoenix", "Unicorn", "Kitsune"]),
        (.hard, "What giant bird in Middle Eastern folklore can carry off elephants?",
         ["Roc", "Simurgh", "Phoenix", "Thunderbird", "Griffin", "Harpy"]),
        (.medium, "What creature has a woman's upper body and a bird's lower body?",
         ["Harpy", "Siren", "Sphinx", "Sphinx-bird", "Valkyrie", "Fury"]),
        (.hard, "What's Canada's version of the Loch Ness Monster?",
         ["Ogopogo", "Champ", "Cadborosaurus", "Nessie", "Bessie", "Memphre"]),
        (.medium, "In Mexican folklore, what creature drains livestock blood, especially goats?",
         ["Chupacabra", "Wendigo", "La Llorona", "Nagual", "Duende", "El Cucuy"]),
    ])

    // MARK: - Random Acts of Weird Facts

    static let randomActsOfWeirdFacts: [TriviaQuestion] = build(prefix: "weird", fixedAnswer: true, [
        (.easy, "Which animal sleeps up to 22 hours a day?",
         ["Koala", "Sloth", "Cat", "Panda", "Hedgehog", "Bat"]),
        (.medium, "What's the only mammal capable of true flight?",
         ["Bat", "Flying squirrel", "Sugar glider", "Colugo", "Flying fox", "Pterosaur"]),
        (.medium, "Which planet spins on its side compared to the others?",
         ["Uranus", "Venus", "Neptune", "Saturn", "Mars", "Jupiter"]),
        (.easy, "What's the fastest land animal in the world?",
         ["Cheetah", "Lion", "Pronghorn", "Greyhound", "Ostrich", "Gazelle"]),
        (.hard, "Which country has the most time zones?",
         ["France", "Russia", "United States", "China", "Canada", "Australia"]),
        (.medium, "What is a group of flamingos called?",
         ["A flamboyance", "A flock", "A gaggle", "A pod", "A parliament", "A murder"]),
        (.medium, "How many hearts does an octopus have?",
         ["Three", "One", "Two", "Four", "Five", "Eight"]),
        (.medium, "What color is a polar bear's skin under its fur?",
         ["Black", "White", "Pink", "Brown", "Gray", "Blue"]),
        (.medium, "What food never spoils if stored properly?",
         ["Honey", "Rice", "Salt", "Sugar", "Vinegar", "Maple syrup"]),
        (.hard, "Which country invented modern bungee jumping?",
         ["New Zealand", "Australia", "United States", "United Kingdom", "France", "South Africa"]),
        (.medium, "What's the tallest species of grass in the world?",
         ["Bamboo", "Wheat", "Sugarcane", "Papyrus", "Corn", "Elephant grass"]),
        (.hard, "How many bones does a shark have?",
         ["Zero — sharks are cartilage", "100", "206", "300", "50", "1,000"]),
        (.hard, "What's the loudest animal on Earth relative to its size?",
         ["The pistol shrimp", "The blue whale", "The howler monkey", "The elephant", "The lion", "The cicada"]),
        (.medium, "Which US state has the most lakes?",
         ["Alaska", "Minnesota", "Michigan", "Wisconsin", "Florida", "Maine"]),
        (.medium, "What's widely credited as the first video game?",
         ["Pong", "Tetris", "Pac-Man", "Space Invaders", "Asteroids", "Spacewar!"]),
        (.hard, "Which animal has the strongest bite force of any land animal?",
         ["Saltwater crocodile", "Hippopotamus", "Grizzly bear", "Lion", "Gorilla", "Hyena"]),
        (.medium, "What's the only continent with no active volcanoes?",
         ["Australia", "Antarctica", "Europe", "Asia", "Africa", "South America"]),
        (.hard, "How long can a snail sleep in one stretch?",
         ["Up to 3 years", "A few hours", "One week", "One month", "6 months", "A full year"]),
        (.hard, "Which fruit is technically a berry, but strawberries aren't?",
         ["Bananas", "Apples", "Watermelons", "Oranges", "Grapes", "Pineapples"]),
        (.medium, "What's the most consumed beverage in the world after water?",
         ["Tea", "Coffee", "Soda", "Juice", "Milk", "Beer"]),
        (.medium, "Which animal can rotate its head almost 270 degrees?",
         ["Owl", "Cat", "Snake", "Chameleon", "Falcon", "Parrot"]),
        (.hard, "Roughly what percentage of Earth's oxygen comes from the ocean?",
         ["Around 50%", "Around 5%", "Around 20%", "Around 80%", "Around 35%", "Around 65%"]),
        (.hard, "Which mammal can't jump at all?",
         ["Elephant", "Rhinoceros", "Hippopotamus", "Sloth", "Whale", "Giraffe"]),
        (.hard, "What's the smallest bone in the human body?",
         ["The stapes (in the ear)", "The femur", "The radius", "The patella", "The clavicle", "The malleus"]),
        (.hard, "Which US president appeared on a Wheaties box despite not being an athlete?",
         ["Ronald Reagan", "George Washington", "Abraham Lincoln", "John F. Kennedy", "Theodore Roosevelt", "Dwight Eisenhower"]),
        (.medium, "What's the only letter that doesn't appear in any US state name?",
         ["Q", "X", "Z", "J", "W", "V"]),
        (.medium, "Which animal reportedly never forgets a face?",
         ["Elephant", "Dolphin", "Crow", "Dog", "Horse", "Parrot"]),
        (.hard, "What's the world's largest desert by area (hint: it's cold)?",
         ["Antarctica", "Sahara", "Arabian Desert", "Gobi Desert", "Kalahari", "Sonoran Desert"]),
        (.hard, "Which toy was originally invented as a wallpaper cleaner?",
         ["Play-Doh", "Silly Putty", "Slinky", "Etch A Sketch", "Legos", "Rubik's Cube"]),
        (.hard, "What's the loudest thing an octopus can't do (trick question flavor: pick the true weird fact)?",
         ["Octopuses have blue blood", "Octopuses have red blood", "Octopuses can't change color", "Octopuses have bones", "Octopuses sleep standing up", "Octopuses live over 50 years"]),
    ])

    // MARK: - Superlative Showdown (world records/extremes)

    static let superlativeShowdown: [TriviaQuestion] = build(prefix: "super", fixedAnswer: true, [
        (.easy, "What's the tallest mountain in the world?",
         ["Mount Everest", "K2", "Kilimanjaro", "Denali", "Mont Blanc", "Matterhorn"]),
        (.easy, "What's the longest river in the world?",
         ["The Nile", "The Amazon", "The Yangtze", "The Mississippi", "The Congo", "The Danube"]),
        (.easy, "What's the largest ocean on Earth?",
         ["The Pacific", "The Atlantic", "The Indian", "The Arctic", "The Southern", "The Mediterranean"]),
        (.medium, "What's the smallest country in the world by area?",
         ["Vatican City", "Monaco", "San Marino", "Liechtenstein", "Malta", "Nauru"]),
        (.easy, "What's the largest land animal on Earth?",
         ["African elephant", "Blue whale", "Giraffe", "Rhinoceros", "Hippopotamus", "Polar bear"]),
        (.medium, "What's the largest animal to have ever lived?",
         ["The blue whale", "The African elephant", "The T. rex", "The giant squid", "The sperm whale", "The Argentinosaurus"]),
        (.medium, "What's the fastest bird in the world (in a dive)?",
         ["Peregrine falcon", "Golden eagle", "Ostrich", "Hummingbird", "Swift", "Albatross"]),
        (.hard, "What's the largest desert in the world overall?",
         ["Antarctic Desert", "Sahara Desert", "Arabian Desert", "Gobi Desert", "Kalahari Desert", "Sonoran Desert"]),
        (.medium, "What's the deepest point in all of Earth's oceans?",
         ["The Mariana Trench", "The Puerto Rico Trench", "The Java Trench", "The Tonga Trench", "The Sunda Trench", "The Kermadec Trench"]),
        (.easy, "What's the largest country in the world by area?",
         ["Russia", "Canada", "China", "United States", "Brazil", "Australia"]),
        (.medium, "What's the hottest planet in our solar system?",
         ["Venus", "Mercury", "Mars", "Jupiter", "Saturn", "Earth"]),
        (.easy, "What's the largest planet in our solar system?",
         ["Jupiter", "Saturn", "Neptune", "Uranus", "Earth", "Mars"]),
        (.easy, "What's the smallest planet in our solar system?",
         ["Mercury", "Mars", "Venus", "Pluto", "Earth", "Neptune"]),
        (.hard, "What's the largest lake in the world by surface area?",
         ["The Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal", "Lake Michigan", "The Dead Sea"]),
        (.hard, "What's the tallest waterfall in the world?",
         ["Angel Falls", "Niagara Falls", "Victoria Falls", "Yosemite Falls", "Iguazu Falls", "Tugela Falls"]),
        (.medium, "What's the largest species of shark in the world?",
         ["Whale shark", "Great white shark", "Tiger shark", "Hammerhead shark", "Megalodon", "Basking shark"]),
        (.medium, "What's the smallest bird in the world?",
         ["Bee hummingbird", "Goldfinch", "Wren", "Sparrow", "Kinglet", "Chickadee"]),
        (.medium, "What's the largest rodent in the world?",
         ["Capybara", "Beaver", "Groundhog", "Porcupine", "Muskrat", "Nutria"]),
        (.easy, "What's the tallest animal in the world?",
         ["Giraffe", "African elephant", "Ostrich", "Camel", "Moose", "Polar bear"]),
        (.medium, "What's the coldest place ever recorded on Earth?",
         ["Antarctica", "Siberia", "Greenland", "Alaska", "Northern Canada", "Mount Everest"]),
        (.medium, "What's the largest island in the world (not counting continents)?",
         ["Greenland", "Madagascar", "Borneo", "New Guinea", "Iceland", "Great Britain"]),
        (.easy, "What's the largest coral reef system in the world?",
         ["The Great Barrier Reef", "The Belize Barrier Reef", "The Red Sea Coral Reef", "The Florida Reef", "The New Caledonia Barrier Reef", "The Mesoamerican Reef"]),
        (.easy, "What's the longest wall ever built by humans?",
         ["The Great Wall of China", "Hadrian's Wall", "The Berlin Wall", "The Great Zimbabwe Wall", "The Western Wall", "The Great Green Wall"]),
        (.easy, "What's the largest rainforest in the world?",
         ["The Amazon Rainforest", "The Congo Rainforest", "The Daintree Rainforest", "The Southeast Asian Rainforest", "The Valdivian Rainforest", "The Sundarbans"]),
        (.hard, "What's the most venomous animal in the world by toxicity?",
         ["The box jellyfish", "The king cobra", "The black mamba", "The inland taipan", "The poison dart frog", "The stonefish"]),
        (.medium, "What's the largest species of penguin?",
         ["Emperor penguin", "King penguin", "Gentoo penguin", "Adelie penguin", "Chinstrap penguin", "Rockhopper penguin"]),
        (.hard, "What's the busiest airport in the world by passenger traffic?",
         ["Hartsfield-Jackson Atlanta", "Beijing Capital", "Dubai International", "LAX", "Heathrow", "O'Hare"]),
        (.hard, "What's the largest freshwater lake in the world by volume?",
         ["Lake Baikal", "Lake Superior", "Lake Victoria", "Lake Tanganyika", "The Caspian Sea", "Lake Michigan"]),
        (.medium, "What's the most populous country in the world?",
         ["India", "China", "United States", "Indonesia", "Pakistan", "Brazil"]),
        (.medium, "What's the tallest building in the world?",
         ["Burj Khalifa", "Shanghai Tower", "Empire State Building", "Willis Tower", "Taipei 101", "Petronas Towers"]),
    ])

    // MARK: - Time Machine (which decade did X happen)

    static let timeMachine: [TriviaQuestion] = build(prefix: "time", fixedAnswer: true, [
        (.easy, "In which decade did the first iPhone release?",
         ["2000s", "1990s", "2010s", "1980s", "2020s", "1970s"]),
        (.medium, "In which decade did the Titanic sink?",
         ["1910s", "1900s", "1920s", "1890s", "1930s", "1880s"]),
        (.easy, "In which decade did the first man walk on the moon?",
         ["1960s", "1950s", "1970s", "1940s", "1980s", "1990s"]),
        (.medium, "In which decade did the World Wide Web become publicly available?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "1960s"]),
        (.medium, "In which decade did Walt Disney World open?",
         ["1970s", "1960s", "1980s", "1950s", "1990s", "2000s"]),
        (.medium, "In which decade did the Berlin Wall fall?",
         ["1980s", "1970s", "1990s", "1960s", "2000s", "1950s"]),
        (.medium, "In which decade did home video game consoles first go on sale?",
         ["1970s", "1960s", "1980s", "1950s", "1990s", "2000s"]),
        (.hard, "In which decade did color television become common in American homes?",
         ["1960s", "1950s", "1970s", "1940s", "1980s", "1930s"]),
        (.medium, "In which decade did the first Star Wars movie release?",
         ["1970s", "1960s", "1980s", "1990s", "1950s", "2000s"]),
        (.medium, "In which decade did the Wright brothers achieve powered flight?",
         ["1900s", "1890s", "1910s", "1880s", "1920s", "1870s"]),
        (.easy, "In which decade did Disney release \"The Lion King\"?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "1960s"]),
        (.medium, "In which decade did the first Harry Potter book publish?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "2020s"]),
        (.medium, "In which decade did the Great Depression begin?",
         ["1920s", "1910s", "1930s", "1900s", "1940s", "1890s"]),
        (.medium, "In which decade did rock and roll first become popular?",
         ["1950s", "1940s", "1960s", "1930s", "1970s", "1920s"]),
        (.medium, "In which decade did the first Super Mario Bros. release?",
         ["1980s", "1970s", "1990s", "1960s", "2000s", "1950s"]),
        (.medium, "In which decade did the Cold War officially end?",
         ["1990s", "1980s", "2000s", "1970s", "1960s", "2010s"]),
        (.easy, "In which decade did the first Pixar movie (\"Toy Story\") release?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "1960s"]),
        (.medium, "In which decade did the internet become a household word?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "1960s"]),
        (.hard, "In which decade was the first email ever sent?",
         ["1970s", "1960s", "1980s", "1950s", "1990s", "2000s"]),
        (.hard, "In which decade did seatbelt laws first become widespread in the US?",
         ["1980s", "1970s", "1990s", "1960s", "2000s", "1950s"]),
        (.hard, "In which decade did the first Toyota Prius go on sale?",
         ["1990s", "1980s", "2000s", "1970s", "2010s", "1960s"]),
        (.hard, "In which decade did the first McDonald's restaurant open?",
         ["1940s", "1930s", "1950s", "1920s", "1960s", "1970s"]),
        (.medium, "In which decade did Elvis Presley become famous?",
         ["1950s", "1940s", "1960s", "1930s", "1970s", "1920s"]),
        (.medium, "In which decade did the first Nintendo Game Boy release?",
         ["1980s", "1970s", "1990s", "1960s", "2000s", "1950s"]),
        (.medium, "In which decade did the real Apollo 13 mission take place?",
         ["1970s", "1960s", "1980s", "1950s", "1990s", "2000s"]),
        (.hard, "In which decade did drive-in movie theaters peak in the US?",
         ["1950s", "1940s", "1960s", "1930s", "1970s", "1920s"]),
        (.hard, "In which decade did the first Ford Model T roll off the line?",
         ["1900s", "1890s", "1910s", "1880s", "1920s", "1870s"]),
        (.medium, "In which decade did the first Star Trek series premiere?",
         ["1960s", "1950s", "1970s", "1940s", "1980s", "1990s"]),
        (.hard, "In which decade did commercial airline flights begin?",
         ["1910s", "1900s", "1920s", "1890s", "1930s", "1880s"]),
        (.medium, "In which decade did DVDs overtake VHS in popularity?",
         ["2000s", "1990s", "2010s", "1980s", "1970s", "2020s"]),
    ])

    // MARK: - Pop Culture Time Capsule (recognition trivia, distinct from Time Machine's decade-guessing format)

    static let popCultureTimeCapsule: [TriviaQuestion] = build(prefix: "pop", fixedAnswer: true, [
        (.easy, "What was the digital pet toy of the 1990s you had to feed and care for?",
         ["Tamagotchi", "Furby", "Beanie Babies", "Pokémon cards", "Polly Pocket", "Nintendo Game Boy"]),
        (.medium, "Which boy band sang \"I Want It That Way\"?",
         ["Backstreet Boys", "NSYNC", "Boyz II Men", "New Kids on the Block", "Jonas Brothers", "One Direction"]),
        (.easy, "What's the fictional coffee shop the \"Friends\" characters hang out at?",
         ["Central Perk", "The Grind", "Java Joe's", "Cheers", "MacLaren's", "The Bean"]),
        (.easy, "What toy line features small dolls living in tiny compact cases?",
         ["Polly Pocket", "Barbie", "Bratz", "American Girl", "My Little Pony", "Littlest Pet Shop"]),
        (.easy, "What 2016 dance craze involves a floss-like arm motion?",
         ["The Floss", "The Dab", "The Whip", "The Nae Nae", "The Renegade", "The Cha Cha Slide"]),
        (.easy, "Which video game plumber rescues a princess from a turtle-like villain?",
         ["Super Mario", "Sonic the Hedgehog", "Donkey Kong", "Zelda", "Kirby", "Mega Man"]),
        (.easy, "What handheld toy spins between your fingers, huge in the late 2010s?",
         ["Fidget spinner", "Yo-yo", "Pog", "Tamagotchi", "Slap bracelet", "Silly Putty"]),
        (.medium, "Which show is known for the phrase \"Winter is Coming\"?",
         ["Game of Thrones", "The Witcher", "Lord of the Rings", "Vikings", "House of the Dragon", "Outlander"]),
        (.easy, "What collectible card game features Pikachu and Charizard?",
         ["Pokémon", "Yu-Gi-Oh!", "Magic: The Gathering", "Digimon", "Bakugan", "Skylanders"]),
        (.medium, "Which singing competition launched Kelly Clarkson and Carrie Underwood?",
         ["American Idol", "The Voice", "America's Got Talent", "X Factor", "The Masked Singer", "So You Think You Can Dance"]),
        (.easy, "What battle royale game took over school playgrounds in 2018?",
         ["Fortnite", "Minecraft", "Roblox", "Call of Duty", "Apex Legends", "PUBG"]),
        (.medium, "What six-second looping video app shut down in 2017?",
         ["Vine", "Musical.ly", "TikTok", "Snapchat", "Instagram", "YouTube Shorts"]),
        (.easy, "Which classic board game involves buying properties like Boardwalk?",
         ["Monopoly", "The Game of Life", "Clue", "Risk", "Sorry!", "Trouble"]),
        (.medium, "What egg-shaped-container putty toy became a classic?",
         ["Silly Putty", "Slime", "Gak", "Flarp", "Play-Doh", "Moon Sand"]),
        (.easy, "Which cartoon sponge works at the Krusty Krab in Bikini Bottom?",
         ["SpongeBob SquarePants", "The Fairly OddParents", "Rugrats", "CatDog", "Hey Arnold", "Doug"]),
        (.medium, "What rubber bracelet trend of the mid-2000s came shaped like animals or words?",
         ["Silly Bandz", "Jelly bracelets", "Livestrong bracelets", "Friendship bracelets", "Slap bracelets", "Pura Vida"]),
        (.easy, "Which app made disappearing photo messages popular in the early 2010s?",
         ["Snapchat", "Instagram", "WhatsApp", "TikTok", "BeReal", "Facebook Messenger"]),
        (.medium, "What dance/exercise game series used a plastic remote-shaped controller?",
         ["Wii Sports", "Dance Dance Revolution", "Just Dance", "Guitar Hero", "Kinect Sports", "Ring Fit Adventure"]),
        (.easy, "Which animated movie about a lost clownfish became a massive hit?",
         ["Finding Nemo", "Finding Dory", "The Little Mermaid", "Shark Tale", "Moana", "Luca"]),
        (.easy, "What building/survival game lets players build whole worlds out of blocks?",
         ["Minecraft", "Roblox", "Fortnite", "Terraria", "Lego Worlds", "Animal Crossing"]),
        (.medium, "What toy craze wove tiny rubber bands into bracelets on a small loom?",
         ["Rainbow Loom", "Silly Bandz", "Friendship bracelets", "Perler beads", "Pony beads", "Shrinky Dinks"]),
        (.easy, "Which life-simulation game lets players build a virtual family's house and life?",
         ["The Sims", "Animal Crossing", "Stardew Valley", "Second Life", "RollerCoaster Tycoon", "Harvest Moon"]),
        (.medium, "What smart speaker device became a common \"ask it anything\" household gadget?",
         ["Amazon Echo (Alexa)", "Google Home", "Apple HomePod", "Siri", "Cortana", "Bixby"]),
        (.easy, "Which app applies silly AR face filters, popular for \"stories\"?",
         ["Snapchat", "Instagram", "TikTok", "Facebook", "BeReal", "VSCO"]),
        (.medium, "What blind-box collectible fad involves \"hatching\" or unboxing a surprise figure?",
         ["L.O.L. Surprise! dolls", "Beanie Babies", "Squishmallows", "Shopkins", "Hatchimals", "Funko Pops"]),
        (.easy, "Which mobile game involves flinging birds at pig-fortified structures?",
         ["Angry Birds", "Candy Crush", "Fruit Ninja", "Temple Run", "Subway Surfers", "Cut the Rope"]),
        (.medium, "What 2014 viral fundraiser challenge involved dumping ice water on yourself?",
         ["The Ice Bucket Challenge", "The Cinnamon Challenge", "The Mannequin Challenge", "The Harlem Shake", "The Tide Pod Challenge", "The Bottle Cap Challenge"]),
        (.easy, "What early-2020s squishy toy trend features soft, oversized plush animals?",
         ["Squishmallows", "Beanie Babies", "Webkinz", "Jellycats", "Build-A-Bear", "Pillow Pets"]),
        (.medium, "What YouTube channel became famous for unboxing/reviewing toys for a huge young audience?",
         ["Ryan's World", "Cocomelon", "PewDiePie", "MrBeast", "Blippi", "SpongeBob"]),
        (.hard, "What app turned 15-second lip-sync videos into a trend before TikTok took over?",
         ["Musical.ly", "Vine", "Snapchat", "Instagram", "Dubsmash", "YouTube Shorts"]),
    ])
}
