-- Travel Trivia — audio genre content expansion (2026-07-28).
-- Adds more real, CC-licensed clips to the 3 audio genres (Animal Sounds
-- Safari, Sound FX Guess, Name That Tune) on top of the initial set from
-- 20260727100000_audio_genres_content.sql. Mirrors the app's bundled
-- AudioSeedQuestions.swift (see Travel Trivia/Models/AudioSeedQuestions.swift
-- for full sourcing rationale, including this pass's notes).
--
-- Sourcing: re-attempted Freesound and Jamendo API signup this pass, per
-- request. Both still require completing an interactive account creation
-- (email verification; Freesound additionally gates its "apply for API
-- access" page behind login) that a headless session cannot complete —
-- same fundamental blocker as the original session, not a temporary
-- outage. Every clip below is again sourced live from the Wikimedia
-- Commons API, CC-licensed, with real per-clip attribution. One originally
-- planned tune (Barber of Seville Overture) was dropped: the only usable
-- CC0/CC-BY clip found was a different aria from the same opera, which
-- would have mismatched the "Barber of Seville Overture" answer text.
-- Two originally planned SFX (popcorn popping, zipper) were dropped for
-- the same reason — no real sound-effect recording existed on Commons,
-- only word-pronunciation or unrelated music files.
--
-- The 'wikimedia_commons' source value and its check constraint were
-- already added by 20260727100000_audio_genres_content.sql — no schema
-- change needed here, just more rows using that existing source value.

-- animal-sounds-safari (+12 questions)
with genre as (
    select id from public.genres where slug = 'animal-sounds-safari'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('medium', 'Which animal made this sound?', '[{"id":"asf-14-0","text":"Pig"},{"id":"asf-14-1","text":"Goat"},{"id":"asf-14-2","text":"Donkey"},{"id":"asf-14-3","text":"Turkey"},{"id":"asf-14-4","text":"Bee"},{"id":"asf-14-5","text":"Seagull"}]'::jsonb, 'asf-14-0', 'animal-sounds-safari/pig.m4a', '"Mudchute pig 1.ogg" by Secretlondon (CC BY-SA 3.0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-15-0","text":"Goat"},{"id":"asf-15-1","text":"Donkey"},{"id":"asf-15-2","text":"Turkey"},{"id":"asf-15-3","text":"Bee"},{"id":"asf-15-4","text":"Seagull"},{"id":"asf-15-5","text":"Peacock"}]'::jsonb, 'asf-15-0', 'animal-sounds-safari/goat.m4a', '"Herd of goats bleating.ogg" by stephan (Public domain), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-16-0","text":"Donkey"},{"id":"asf-16-1","text":"Turkey"},{"id":"asf-16-2","text":"Bee"},{"id":"asf-16-3","text":"Seagull"},{"id":"asf-16-4","text":"Peacock"},{"id":"asf-16-5","text":"Parakeet"}]'::jsonb, 'asf-16-0', 'animal-sounds-safari/donkey.m4a', '"157763 felix-blume a-donkey-is-braying-in-his-enclosure-in-south-of-france.wav" by felix-blume (CC0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-17-0","text":"Turkey"},{"id":"asf-17-1","text":"Bee"},{"id":"asf-17-2","text":"Seagull"},{"id":"asf-17-3","text":"Peacock"},{"id":"asf-17-4","text":"Parakeet"},{"id":"asf-17-5","text":"Penguin"}]'::jsonb, 'asf-17-0', 'animal-sounds-safari/turkey.m4a', '"Meleagris gallopavo - Wild Turkey XC134155.ogg" by Jonathon Jongsma (CC BY-SA 3.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-18-0","text":"Bee"},{"id":"asf-18-1","text":"Seagull"},{"id":"asf-18-2","text":"Peacock"},{"id":"asf-18-3","text":"Parakeet"},{"id":"asf-18-4","text":"Penguin"},{"id":"asf-18-5","text":"Flamingo"}]'::jsonb, 'asf-18-0', 'animal-sounds-safari/bee.m4a', '"Bee buzzing sound (animal noises).opus" by Free Sounds Library User Spanac (CC BY 3.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-19-0","text":"Seagull"},{"id":"asf-19-1","text":"Peacock"},{"id":"asf-19-2","text":"Parakeet"},{"id":"asf-19-3","text":"Penguin"},{"id":"asf-19-4","text":"Flamingo"},{"id":"asf-19-5","text":"Woodpecker"}]'::jsonb, 'asf-19-0', 'animal-sounds-safari/seagull.m4a', '"XC707075 - European Herring Gull - Larus argentatus.mp3" by Sonothèque ADVL (CC0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-20-0","text":"Peacock"},{"id":"asf-20-1","text":"Parakeet"},{"id":"asf-20-2","text":"Penguin"},{"id":"asf-20-3","text":"Flamingo"},{"id":"asf-20-4","text":"Woodpecker"},{"id":"asf-20-5","text":"Canary"}]'::jsonb, 'asf-20-0', 'animal-sounds-safari/peacock.m4a', '"Indian Peafowl.ogg" by Gypsypkd (Public domain), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-21-0","text":"Parakeet"},{"id":"asf-21-1","text":"Penguin"},{"id":"asf-21-2","text":"Flamingo"},{"id":"asf-21-3","text":"Woodpecker"},{"id":"asf-21-4","text":"Canary"},{"id":"asf-21-5","text":"Cat"}]'::jsonb, 'asf-21-0', 'animal-sounds-safari/parakeet.m4a', '"Budgerigar chirping.ogg" by mary905 (Public domain), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-22-0","text":"Penguin"},{"id":"asf-22-1","text":"Flamingo"},{"id":"asf-22-2","text":"Woodpecker"},{"id":"asf-22-3","text":"Canary"},{"id":"asf-22-4","text":"Cat"},{"id":"asf-22-5","text":"Chicken"}]'::jsonb, 'asf-22-0', 'animal-sounds-safari/penguin.m4a', '"20091121 Little Penguin calls at St Kilda Breakwater.ogg" by Mikeybear (CC BY 3.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-23-0","text":"Flamingo"},{"id":"asf-23-1","text":"Woodpecker"},{"id":"asf-23-2","text":"Canary"},{"id":"asf-23-3","text":"Cat"},{"id":"asf-23-4","text":"Chicken"},{"id":"asf-23-5","text":"Cow"}]'::jsonb, 'asf-23-0', 'animal-sounds-safari/flamingo.m4a', '"Greater flamingo call recorded in March 2005 at Mayani, Satara.wav" by Sharadapte (CC BY-SA 4.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-24-0","text":"Woodpecker"},{"id":"asf-24-1","text":"Canary"},{"id":"asf-24-2","text":"Cat"},{"id":"asf-24-3","text":"Chicken"},{"id":"asf-24-4","text":"Cow"},{"id":"asf-24-5","text":"Cricket"}]'::jsonb, 'asf-24-0', 'animal-sounds-safari/woodpecker.m4a', '"Great Spotted Woodpecker drum.ogg" by T.Voekler (CC BY-SA 3.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-25-0","text":"Canary"},{"id":"asf-25-1","text":"Cat"},{"id":"asf-25-2","text":"Chicken"},{"id":"asf-25-3","text":"Cow"},{"id":"asf-25-4","text":"Cricket"},{"id":"asf-25-5","text":"Cuckoo"}]'::jsonb, 'asf-25-0', 'animal-sounds-safari/canary.m4a', '"Long-range-Order-in-Canary-Song-pcbi.1003052.s002.oga" by Markowitz J, Ivie E, Kligler L, Gardner T (CC BY 2.5), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);

-- sound-fx-guess (+13 questions)
with genre as (
    select id from public.genres where slug = 'sound-fx-guess'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('medium', 'What sound effect is this?', '[{"id":"sfx-11-0","text":"Doorbell"},{"id":"sfx-11-1","text":"Telephone Ringing"},{"id":"sfx-11-2","text":"Ocean Waves"},{"id":"sfx-11-3","text":"Rain"},{"id":"sfx-11-4","text":"Bicycle Bell"},{"id":"sfx-11-5","text":"Vacuum Cleaner"}]'::jsonb, 'sfx-11-0', 'sound-fx-guess/doorbell.m4a', '"Sound Effect - Door Bell.ogg" by Amada44 (CC0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-12-0","text":"Telephone Ringing"},{"id":"sfx-12-1","text":"Ocean Waves"},{"id":"sfx-12-2","text":"Rain"},{"id":"sfx-12-3","text":"Bicycle Bell"},{"id":"sfx-12-4","text":"Vacuum Cleaner"},{"id":"sfx-12-5","text":"Cash Register"}]'::jsonb, 'sfx-12-0', 'sound-fx-guess/telephone-ring.m4a', '"Model 500 Telephone British ring.ogg" by CianMcCann (CC BY-SA 3.0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-13-0","text":"Ocean Waves"},{"id":"sfx-13-1","text":"Rain"},{"id":"sfx-13-2","text":"Bicycle Bell"},{"id":"sfx-13-3","text":"Vacuum Cleaner"},{"id":"sfx-13-4","text":"Cash Register"},{"id":"sfx-13-5","text":"Drum Roll"}]'::jsonb, 'sfx-13-0', 'sound-fx-guess/ocean-waves.m4a', '"Oceanwavescrushing.ogg" by Luftrum (CC BY 3.0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-14-0","text":"Rain"},{"id":"sfx-14-1","text":"Bicycle Bell"},{"id":"sfx-14-2","text":"Vacuum Cleaner"},{"id":"sfx-14-3","text":"Cash Register"},{"id":"sfx-14-4","text":"Drum Roll"},{"id":"sfx-14-5","text":"Referee Whistle"}]'::jsonb, 'sfx-14-0', 'sound-fx-guess/rain.m4a', '"Rain (1).ogg" by ezwa (Public domain), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-15-0","text":"Bicycle Bell"},{"id":"sfx-15-1","text":"Vacuum Cleaner"},{"id":"sfx-15-2","text":"Cash Register"},{"id":"sfx-15-3","text":"Drum Roll"},{"id":"sfx-15-4","text":"Referee Whistle"},{"id":"sfx-15-5","text":"Typewriter"}]'::jsonb, 'sfx-15-0', 'sound-fx-guess/bicycle-bell.m4a', '"Bicycle-bell.wav" by Xampi8 (CC BY 3.0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-16-0","text":"Vacuum Cleaner"},{"id":"sfx-16-1","text":"Cash Register"},{"id":"sfx-16-2","text":"Drum Roll"},{"id":"sfx-16-3","text":"Referee Whistle"},{"id":"sfx-16-4","text":"Typewriter"},{"id":"sfx-16-5","text":"Scissors Cutting"}]'::jsonb, 'sfx-16-0', 'sound-fx-guess/vacuum-cleaner.m4a', '"Het aanstaan van een stofzuiger - SoundCloud - Beeld en Geluid.ogg" by Beeld en Geluid (CC BY-SA 3.0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-17-0","text":"Cash Register"},{"id":"sfx-17-1","text":"Drum Roll"},{"id":"sfx-17-2","text":"Referee Whistle"},{"id":"sfx-17-3","text":"Typewriter"},{"id":"sfx-17-4","text":"Scissors Cutting"},{"id":"sfx-17-5","text":"Page Turning"}]'::jsonb, 'sfx-17-0', 'sound-fx-guess/cash-register.m4a', '"Cash register.ogg" by Me (Public domain), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-18-0","text":"Drum Roll"},{"id":"sfx-18-1","text":"Referee Whistle"},{"id":"sfx-18-2","text":"Typewriter"},{"id":"sfx-18-3","text":"Scissors Cutting"},{"id":"sfx-18-4","text":"Page Turning"},{"id":"sfx-18-5","text":"Blender"}]'::jsonb, 'sfx-18-0', 'sound-fx-guess/drum-roll.m4a', '"Drum Roll Intro.ogg" by Iwan Sounds and DIY (CC0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-19-0","text":"Referee Whistle"},{"id":"sfx-19-1","text":"Typewriter"},{"id":"sfx-19-2","text":"Scissors Cutting"},{"id":"sfx-19-3","text":"Page Turning"},{"id":"sfx-19-4","text":"Blender"},{"id":"sfx-19-5","text":"Alarm Clock"}]'::jsonb, 'sfx-19-0', 'sound-fx-guess/referee-whistle.m4a', '"218318 splicesound referee-whistle-blow-gymnasium.wav" by SpliceSound (CC0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-20-0","text":"Typewriter"},{"id":"sfx-20-1","text":"Scissors Cutting"},{"id":"sfx-20-2","text":"Page Turning"},{"id":"sfx-20-3","text":"Blender"},{"id":"sfx-20-4","text":"Alarm Clock"},{"id":"sfx-20-5","text":"Applause"}]'::jsonb, 'sfx-20-0', 'sound-fx-guess/typewriter.m4a', '"WWS Typewriter.ogg" by Work With Sounds / Konrad Gutkowski (CC BY 4.0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-21-0","text":"Scissors Cutting"},{"id":"sfx-21-1","text":"Page Turning"},{"id":"sfx-21-2","text":"Blender"},{"id":"sfx-21-3","text":"Alarm Clock"},{"id":"sfx-21-4","text":"Applause"},{"id":"sfx-21-5","text":"Camera Shutter"}]'::jsonb, 'sfx-21-0', 'sound-fx-guess/scissors-snip.m4a', '"WWS Paper-cuttingscissorsSloveniaPartisanPrintingShop.ogg" by Work With Sounds / Technical Museum of Slovenia (CC BY 4.0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-22-0","text":"Page Turning"},{"id":"sfx-22-1","text":"Blender"},{"id":"sfx-22-2","text":"Alarm Clock"},{"id":"sfx-22-3","text":"Applause"},{"id":"sfx-22-4","text":"Camera Shutter"},{"id":"sfx-22-5","text":"Race Car Engine"}]'::jsonb, 'sfx-22-0', 'sound-fx-guess/page-turning.m4a', '"Turning a page.ogg" by planish (Public domain), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-23-0","text":"Blender"},{"id":"sfx-23-1","text":"Alarm Clock"},{"id":"sfx-23-2","text":"Applause"},{"id":"sfx-23-3","text":"Camera Shutter"},{"id":"sfx-23-4","text":"Race Car Engine"},{"id":"sfx-23-5","text":"Church Bell"}]'::jsonb, 'sfx-23-0', 'sound-fx-guess/blender.m4a', '"Het vermalen van fruit in een blender - SoundCloud - marloeskunst.ogg" by marloeskunst (CC BY 3.0), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);

-- name-that-tune (+14 questions)
with genre as (
    select id from public.genres where slug = 'name-that-tune'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('medium', 'Name that tune!', '[{"id":"ntt-14-0","text":"Ode to Joy"},{"id":"ntt-14-1","text":"Eine kleine Nachtmusik"},{"id":"ntt-14-2","text":"Canon in D"},{"id":"ntt-14-3","text":"Habanera"},{"id":"ntt-14-4","text":"1812 Overture"},{"id":"ntt-14-5","text":"Dance of the Sugar Plum Fairy"}]'::jsonb, 'ntt-14-0', 'name-that-tune/ode-to-joy.m4a', '"Ode to Joy.ogg" by Ludwig van Beethoven (Public domain), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-15-0","text":"Eine kleine Nachtmusik"},{"id":"ntt-15-1","text":"Canon in D"},{"id":"ntt-15-2","text":"Habanera"},{"id":"ntt-15-3","text":"1812 Overture"},{"id":"ntt-15-4","text":"Dance of the Sugar Plum Fairy"},{"id":"ntt-15-5","text":"Waltz of the Flowers"}]'::jsonb, 'ntt-15-0', 'name-that-tune/eine-kleine-nachtmusik.m4a', '"Mozart K525 Serenade in G Major 1 - Allegro.ogg" by Wolfgang Amadeus Mozart (Public domain), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-16-0","text":"Canon in D"},{"id":"ntt-16-1","text":"Habanera"},{"id":"ntt-16-2","text":"1812 Overture"},{"id":"ntt-16-3","text":"Dance of the Sugar Plum Fairy"},{"id":"ntt-16-4","text":"Waltz of the Flowers"},{"id":"ntt-16-5","text":"Radetzky March"}]'::jsonb, 'ntt-16-0', 'name-that-tune/canon-in-d.m4a', '"Kevin MacLeod - Canon in D Major.ogg" by Kevin MacLeod; original composition by Johann Pachelbel (CC BY 3.0), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-17-0","text":"Habanera"},{"id":"ntt-17-1","text":"1812 Overture"},{"id":"ntt-17-2","text":"Dance of the Sugar Plum Fairy"},{"id":"ntt-17-3","text":"Waltz of the Flowers"},{"id":"ntt-17-4","text":"Radetzky March"},{"id":"ntt-17-5","text":"Can-Can (Galop Infernal)"}]'::jsonb, 'ntt-17-0', 'name-that-tune/habanera.m4a', '"Habanera.ogg" by Pracchia-78 (Public domain), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-18-0","text":"1812 Overture"},{"id":"ntt-18-1","text":"Dance of the Sugar Plum Fairy"},{"id":"ntt-18-2","text":"Waltz of the Flowers"},{"id":"ntt-18-3","text":"Radetzky March"},{"id":"ntt-18-4","text":"Can-Can (Galop Infernal)"},{"id":"ntt-18-5","text":"Gymnopédie No. 1"}]'::jsonb, 'ntt-18-0', 'name-that-tune/1812-overture.m4a', '"1812.ogg" by FortunateTheognis (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-19-0","text":"Dance of the Sugar Plum Fairy"},{"id":"ntt-19-1","text":"Waltz of the Flowers"},{"id":"ntt-19-2","text":"Radetzky March"},{"id":"ntt-19-3","text":"Can-Can (Galop Infernal)"},{"id":"ntt-19-4","text":"Gymnopédie No. 1"},{"id":"ntt-19-5","text":"Clair de Lune"}]'::jsonb, 'ntt-19-0', 'name-that-tune/sugar-plum-fairy.m4a', '"Tchaikovsky - Dance of the Sugar Plum Fairy - The Nutcracker.ogg" by Pyotr Ilyich Tchaikovsky (CC BY 3.0), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-20-0","text":"Waltz of the Flowers"},{"id":"ntt-20-1","text":"Radetzky March"},{"id":"ntt-20-2","text":"Can-Can (Galop Infernal)"},{"id":"ntt-20-3","text":"Gymnopédie No. 1"},{"id":"ntt-20-4","text":"Clair de Lune"},{"id":"ntt-20-5","text":"Jupiter (The Planets)"}]'::jsonb, 'ntt-20-0', 'name-that-tune/waltz-of-the-flowers.m4a', '"P.I. Tchaikovsky''s Waltz of the Flowers Performed by The U.S. Army Band, c. 2019.mp3" performed by the U.S. Army Band (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-21-0","text":"Radetzky March"},{"id":"ntt-21-1","text":"Can-Can (Galop Infernal)"},{"id":"ntt-21-2","text":"Gymnopédie No. 1"},{"id":"ntt-21-3","text":"Clair de Lune"},{"id":"ntt-21-4","text":"Jupiter (The Planets)"},{"id":"ntt-21-5","text":"Minuet in G Major"}]'::jsonb, 'ntt-21-0', 'name-that-tune/radetzky-march.m4a', '"Radetzky March.ogg" performed by the United States Marine Band, composed by Johann Strauss I (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-22-0","text":"Can-Can (Galop Infernal)"},{"id":"ntt-22-1","text":"Gymnopédie No. 1"},{"id":"ntt-22-2","text":"Clair de Lune"},{"id":"ntt-22-3","text":"Jupiter (The Planets)"},{"id":"ntt-22-4","text":"Minuet in G Major"},{"id":"ntt-22-5","text":"La Donna è Mobile"}]'::jsonb, 'ntt-22-0', 'name-that-tune/can-can.m4a', '"Jacques Offenbach - Galop Infernal from Orpheus in the Underworld (Can Can) (1858).ogg" by Gnissah (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-23-0","text":"Gymnopédie No. 1"},{"id":"ntt-23-1","text":"Clair de Lune"},{"id":"ntt-23-2","text":"Jupiter (The Planets)"},{"id":"ntt-23-3","text":"Minuet in G Major"},{"id":"ntt-23-4","text":"La Donna è Mobile"},{"id":"ntt-23-5","text":"Air on the G String"}]'::jsonb, 'ntt-23-0', 'name-that-tune/gymnopedie.m4a', '"Gymnopedie No. 1..ogg" by Teknopazzo (CC0), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-24-0","text":"Clair de Lune"},{"id":"ntt-24-1","text":"Jupiter (The Planets)"},{"id":"ntt-24-2","text":"Minuet in G Major"},{"id":"ntt-24-3","text":"La Donna è Mobile"},{"id":"ntt-24-4","text":"Air on the G String"},{"id":"ntt-24-5","text":"The Blue Danube Waltz"}]'::jsonb, 'ntt-24-0', 'name-that-tune/clair-de-lune.m4a', '"Clair de lune (Claude Debussy) Suite bergamasque.ogg" by Claude Debussy (CC BY 3.0), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-25-0","text":"Jupiter (The Planets)"},{"id":"ntt-25-1","text":"Minuet in G Major"},{"id":"ntt-25-2","text":"La Donna è Mobile"},{"id":"ntt-25-3","text":"Air on the G String"},{"id":"ntt-25-4","text":"The Blue Danube Waltz"},{"id":"ntt-25-5","text":"Flight of the Bumblebee"}]'::jsonb, 'ntt-25-0', 'name-that-tune/jupiter.m4a', '"Holst The Planets Jupiter.ogg" performed by the United States Air Force Band, composed by Gustav Holst (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-26-0","text":"Minuet in G Major"},{"id":"ntt-26-1","text":"La Donna è Mobile"},{"id":"ntt-26-2","text":"Air on the G String"},{"id":"ntt-26-3","text":"The Blue Danube Waltz"},{"id":"ntt-26-4","text":"Flight of the Bumblebee"},{"id":"ntt-26-5","text":"The Four Seasons: Spring"}]'::jsonb, 'ntt-26-0', 'name-that-tune/minuet-in-g.m4a', '"Minuet in G major, BWV Anh. 114 (played by PLATO GSW).flac" by Morn (CC0), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-27-0","text":"La Donna è Mobile"},{"id":"ntt-27-1","text":"Air on the G String"},{"id":"ntt-27-2","text":"The Blue Danube Waltz"},{"id":"ntt-27-3","text":"Flight of the Bumblebee"},{"id":"ntt-27-4","text":"The Four Seasons: Spring"},{"id":"ntt-27-5","text":"Für Elise"}]'::jsonb, 'ntt-27-0', 'name-that-tune/la-donna-e-mobile.m4a', '"La Donna E Mobile Rigoletto.ogg" by Giuseppe Verdi & Francesco Maria Piave (Public domain), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);
