-- Travel Trivia — Would You Rather + Movie Quote Mashup seed content
-- (40 questions each, mirroring the app's bundled SeedQuestions.swift; this
-- file is generated from that source).
--
-- Would You Rather is a prediction genre: there is no authored answer, so
-- correct_option_id becomes nullable — null means "majority vote decides
-- at play time".

alter table public.questions alter column correct_option_id drop not null;

with genre as (
    select id from public.genres where slug = 'would-you-rather'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'Which car mishap would be the WORST right now?',
     '[{"text":"AC breaks in July","id":"wyr-1-0"},{"text":"Fries in every seat crack","id":"wyr-1-1"},{"text":"GPS stuck \"recalculating\" for 3 hours","id":"wyr-1-2"},{"id":"wyr-1-3","text":"Carsick sibling in the back"},{"id":"wyr-1-4","text":"Every phone charger dies"},{"id":"wyr-1-5","text":"Flat tire 50 miles from town"}]'::jsonb,
     null),
    ('easy',
     'Which power would help this trip the most?',
     '[{"id":"wyr-2-0","text":"Teleport past traffic"},{"id":"wyr-2-1","text":"X-ray vision for rest stops"},{"id":"wyr-2-2","text":"Talk to animals"},{"id":"wyr-2-3","text":"Control the weather"},{"id":"wyr-2-4","text":"Super speed"},{"id":"wyr-2-5","text":"Turn invisible to skip gas station lines"}]'::jsonb,
     null),
    ('medium',
     'If the car transformed into one of these for the rest of the trip...',
     '[{"id":"wyr-3-0","text":"Hot air balloon"},{"id":"wyr-3-1","text":"Submarine"},{"id":"wyr-3-2","text":"Monster truck"},{"id":"wyr-3-3","text":"Go-kart"},{"id":"wyr-3-4","text":"Rocket ship"},{"id":"wyr-3-5","text":"Horse-drawn carriage"}]'::jsonb,
     null),
    ('easy',
     'Which snack disaster would ruin the car fastest?',
     '[{"id":"wyr-4-0","text":"Melted chocolate on seats"},{"id":"wyr-4-1","text":"Spilled milkshake in the cupholder"},{"id":"wyr-4-2","text":"Exploding popcorn"},{"id":"wyr-4-3","text":"Burst ketchup packet"},{"id":"wyr-4-4","text":"Melted gummy bears in the carpet"},{"id":"wyr-4-5","text":"Crushed chip bag underfoot"}]'::jsonb,
     null),
    ('medium',
     'Which surprise stop would you most want the driver to make?',
     '[{"id":"wyr-5-0","text":"Roadside dinosaur statue"},{"id":"wyr-5-1","text":"Giant ball of twine"},{"id":"wyr-5-2","text":"Drive-in movie theater"},{"id":"wyr-5-3","text":"Ice cream stand"},{"id":"wyr-5-4","text":"Petting zoo"},{"id":"wyr-5-5","text":"Fireworks store"}]'::jsonb,
     null),
    ('easy',
     'Which road trip soundtrack would you be stuck with for 6 hours?',
     '[{"id":"wyr-6-0","text":"Polka music"},{"id":"wyr-6-1","text":"Whale sounds"},{"id":"wyr-6-2","text":"One song on repeat"},{"id":"wyr-6-3","text":"A podcast about tax law"},{"id":"wyr-6-4","text":"Bagpipes"},{"id":"wyr-6-5","text":"Elevator music"}]'::jsonb,
     null),
    ('medium',
     'Which unexpected passenger would make the trip the most interesting?',
     '[{"id":"wyr-7-0","text":"A talking parrot"},{"id":"wyr-7-1","text":"A magician"},{"id":"wyr-7-2","text":"A famous chef"},{"id":"wyr-7-3","text":"A ghost"},{"id":"wyr-7-4","text":"A stand-up comedian"},{"id":"wyr-7-5","text":"A fortune teller"}]'::jsonb,
     null),
    ('easy',
     'Which weather would you least want to drive through?',
     '[{"id":"wyr-8-0","text":"A hailstorm"},{"id":"wyr-8-1","text":"Thick fog"},{"id":"wyr-8-2","text":"A sandstorm"},{"id":"wyr-8-3","text":"A heat wave with no AC"},{"id":"wyr-8-4","text":"A sudden blizzard"},{"id":"wyr-8-5","text":"A swarm of bugs on the windshield"}]'::jsonb,
     null),
    ('medium',
     'Which roadside attraction detour would be worth the extra hour?',
     '[{"id":"wyr-9-0","text":"World''s largest ball of yarn"},{"id":"wyr-9-1","text":"A haunted motel"},{"id":"wyr-9-2","text":"A UFO museum"},{"id":"wyr-9-3","text":"A cheese factory tour"},{"id":"wyr-9-4","text":"An alligator farm"},{"id":"wyr-9-5","text":"A mirror maze"}]'::jsonb,
     null),
    ('medium',
     'Which car game would you be forced to play for the next 2 hours?',
     '[{"id":"wyr-10-0","text":"I Spy with zero good options"},{"id":"wyr-10-1","text":"20 Questions with a cheater"},{"id":"wyr-10-2","text":"Punch Buggy but everyone''s aggressive"},{"id":"wyr-10-3","text":"License plate bingo"},{"id":"wyr-10-4","text":"Would You Rather (very meta)"},{"id":"wyr-10-5","text":"Silent staring contest"}]'::jsonb,
     null),
    ('medium',
     'Which pit stop food would you actually be excited to eat?',
     '[{"id":"wyr-11-0","text":"Gas station sushi"},{"id":"wyr-11-1","text":"A giant turkey leg"},{"id":"wyr-11-2","text":"Mystery gas station hot dog"},{"id":"wyr-11-3","text":"A questionable burrito"},{"id":"wyr-11-4","text":"Truck stop pancakes"},{"id":"wyr-11-5","text":"A whole rotisserie chicken"}]'::jsonb,
     null),
    ('hard',
     'Which navigator mistake would send you the most off course?',
     '[{"id":"wyr-12-0","text":"Reading the map upside down"},{"id":"wyr-12-1","text":"Trusting a psychic instead of GPS"},{"id":"wyr-12-2","text":"Following a \"shortcut\" through a cornfield"},{"id":"wyr-12-3","text":"Arguing with the GPS voice"},{"id":"wyr-12-4","text":"Using a map from 1998"},{"id":"wyr-12-5","text":"Following another car that looked \"confident\""}]'::jsonb,
     null),
    ('easy',
     'Which animal would you least want to spot crossing the road ahead?',
     '[{"id":"wyr-13-0","text":"A moose"},{"id":"wyr-13-1","text":"An escaped zoo lion"},{"id":"wyr-13-2","text":"A herd of turtles"},{"id":"wyr-13-3","text":"A giant tumbleweed monster"},{"id":"wyr-13-4","text":"A peacock"},{"id":"wyr-13-5","text":"A confused ostrich"}]'::jsonb,
     null),
    ('easy',
     'Which car smell would be hardest to survive for 6 hours?',
     '[{"id":"wyr-14-0","text":"Wet dog"},{"id":"wyr-14-1","text":"Old gym socks"},{"id":"wyr-14-2","text":"Durian fruit"},{"id":"wyr-14-3","text":"Burnt popcorn"},{"id":"wyr-14-4","text":"Gas station coffee gone bad"},{"id":"wyr-14-5","text":"A skunk that got a little too close"}]'::jsonb,
     null),
    ('hard',
     'Which vacation would you rather accidentally end up on?',
     '[{"id":"wyr-15-0","text":"A cruise full of clowns"},{"id":"wyr-15-1","text":"A silent meditation retreat"},{"id":"wyr-15-2","text":"A haunted castle tour"},{"id":"wyr-15-3","text":"A competitive cheese-rolling festival"},{"id":"wyr-15-4","text":"A week at a llama farm"},{"id":"wyr-15-5","text":"A convention for people who love traffic cones"}]'::jsonb,
     null),
    ('medium',
     'Which "are we there yet" answer would be the most annoying?',
     '[{"id":"wyr-16-0","text":"\"Ask me again in an hour\""},{"id":"wyr-16-1","text":"A random riddle instead of an answer"},{"id":"wyr-16-2","text":"Complete silence"},{"id":"wyr-16-3","text":"\"We''ll never get there\" (joking, hopefully)"},{"id":"wyr-16-4","text":"A math problem you have to solve first"},{"id":"wyr-16-5","text":"The GPS voice answering instead"}]'::jsonb,
     null),
    ('medium',
     'Which emergency kit item would you actually need most on this trip?',
     '[{"id":"wyr-17-0","text":"A tiny umbrella"},{"id":"wyr-17-1","text":"An inflatable raft"},{"id":"wyr-17-2","text":"A whistle"},{"id":"wyr-17-3","text":"A disguise kit"},{"id":"wyr-17-4","text":"A magic 8-ball"},{"id":"wyr-17-5","text":"A portable karaoke machine"}]'::jsonb,
     null),
    ('easy',
     'Which car temperature disaster would you rather deal with?',
     '[{"id":"wyr-18-0","text":"So hot the seats are lava"},{"id":"wyr-18-1","text":"So cold you can see your breath"},{"id":"wyr-18-2","text":"Only the driver''s seat has AC"},{"id":"wyr-18-3","text":"Heated seats stuck on in summer"},{"id":"wyr-18-4","text":"One window stuck wide open"},{"id":"wyr-18-5","text":"The AC only blows at your feet"}]'::jsonb,
     null),
    ('medium',
     'Which unexpected road trip companion sound would drive you craziest?',
     '[{"id":"wyr-19-0","text":"Someone humming off-key nonstop"},{"id":"wyr-19-1","text":"A squeaky seat that won''t stop"},{"id":"wyr-19-2","text":"Someone narrating everything they see"},{"id":"wyr-19-3","text":"A phone stuck on the lowest possible volume ringtone"},{"id":"wyr-19-4","text":"Someone cracking their knuckles constantly"},{"id":"wyr-19-5","text":"A GPS that mispronounces every street name"}]'::jsonb,
     null),
    ('medium',
     'Which type of rest stop bathroom would you dread most?',
     '[{"id":"wyr-20-0","text":"One with no soap"},{"id":"wyr-20-1","text":"One that''s a 10-minute walk from the car"},{"id":"wyr-20-2","text":"One with a line around the building"},{"id":"wyr-20-3","text":"One that''s suspiciously spotless (too clean, feels like a trap)"},{"id":"wyr-20-4","text":"One with only cold water"},{"id":"wyr-20-5","text":"One where the door doesn''t lock"}]'::jsonb,
     null),
    ('hard',
     'Which time period would you least want this road trip to take place in?',
     '[{"id":"wyr-21-0","text":"The 1800s (horse and wagon)"},{"id":"wyr-21-1","text":"The Stone Age"},{"id":"wyr-21-2","text":"The far future with flying cars you can''t drive"},{"id":"wyr-21-3","text":"Medieval times"},{"id":"wyr-21-4","text":"The Ice Age"},{"id":"wyr-21-5","text":"A world with no roads at all yet"}]'::jsonb,
     null),
    ('medium',
     'Which car breakdown would be the most inconvenient?',
     '[{"id":"wyr-22-0","text":"Dead battery at a scenic overlook"},{"id":"wyr-22-1","text":"Flat tire in a thunderstorm"},{"id":"wyr-22-2","text":"Out of gas in the middle of nowhere"},{"id":"wyr-22-3","text":"Engine trouble right before a big stop"},{"id":"wyr-22-4","text":"A door that won''t open"},{"id":"wyr-22-5","text":"The trunk popping open on the highway"}]'::jsonb,
     null),
    ('hard',
     'Which mythical creature would you least want to see out the car window?',
     '[{"id":"wyr-23-0","text":"A dragon circling overhead"},{"id":"wyr-23-1","text":"A troll blocking a bridge"},{"id":"wyr-23-2","text":"A sea monster in a lake you''re passing"},{"id":"wyr-23-3","text":"A werewolf at a rest stop"},{"id":"wyr-23-4","text":"A giant spider web across the road"},{"id":"wyr-23-5","text":"A ghost hitchhiker"}]'::jsonb,
     null),
    ('easy',
     'Which car chore would you least want to be stuck doing at the next stop?',
     '[{"id":"wyr-24-0","text":"Cleaning out the trash bag"},{"id":"wyr-24-1","text":"Untangling all the charging cables"},{"id":"wyr-24-2","text":"Refilling everyone''s water bottles"},{"id":"wyr-24-3","text":"Wiping bug guts off the windshield"},{"id":"wyr-24-4","text":"Reorganizing the trunk"},{"id":"wyr-24-5","text":"Finding the one shoe that rolled under a seat"}]'::jsonb,
     null),
    ('hard',
     'Which map mishap would send you the most off course?',
     '[{"id":"wyr-25-0","text":"Following an outdated paper map"},{"id":"wyr-25-1","text":"Trusting a GPS with a dead battery"},{"id":"wyr-25-2","text":"Taking directions from a stranger at a gas station"},{"id":"wyr-25-3","text":"Misreading \"north\" as \"south\""},{"id":"wyr-25-4","text":"A GPS voice that keeps changing languages"},{"id":"wyr-25-5","text":"Following a bird because it \"looked confident\""}]'::jsonb,
     null),
    ('medium',
     'Which car playlist would you be forced to listen to on repeat?',
     '[{"id":"wyr-26-0","text":"Nothing but car alarm sounds"},{"id":"wyr-26-1","text":"A single 45-minute song"},{"id":"wyr-26-2","text":"Whale songs"},{"id":"wyr-26-3","text":"A playlist of just sneezes"},{"id":"wyr-26-4","text":"An audiobook read in a monotone"},{"id":"wyr-26-5","text":"Dial-up internet sounds"}]'::jsonb,
     null),
    ('hard',
     'Which unplanned overnight stop would be the most memorable?',
     '[{"id":"wyr-27-0","text":"A haunted-looking motel"},{"id":"wyr-27-1","text":"Sleeping in the car at a rest stop"},{"id":"wyr-27-2","text":"A campsite with no bathrooms nearby"},{"id":"wyr-27-3","text":"A tiny inn run by a very chatty owner"},{"id":"wyr-27-4","text":"A stranger''s guest room after their kind offer"},{"id":"wyr-27-5","text":"A 24-hour diner booth"}]'::jsonb,
     null),
    ('medium',
     'Which co-pilot mistake would cause the most chaos?',
     '[{"id":"wyr-28-0","text":"Falling asleep mid-directions"},{"id":"wyr-28-1","text":"Confidently giving wrong directions"},{"id":"wyr-28-2","text":"Spilling the entire snack bag"},{"id":"wyr-28-3","text":"Losing the phone charger"},{"id":"wyr-28-4","text":"Accidentally locking the doors while parked"},{"id":"wyr-28-5","text":"Turning on the hazard lights instead of the blinker"}]'::jsonb,
     null),
    ('medium',
     'Which car superstition would you actually follow on this trip?',
     '[{"id":"wyr-29-0","text":"Holding your breath through every tunnel"},{"id":"wyr-29-1","text":"Touching the roof when you pass a yellow car"},{"id":"wyr-29-2","text":"Not saying \"flat tire\" out loud"},{"id":"wyr-29-3","text":"Making a wish at every state line"},{"id":"wyr-29-4","text":"Waving at every trucker"},{"id":"wyr-29-5","text":"Counting cows until you pass a graveyard"}]'::jsonb,
     null),
    ('easy',
     'Which sudden detour sign would make you the most curious?',
     '[{"id":"wyr-30-0","text":"\"World''s Smallest Church, 2 Miles\""},{"id":"wyr-30-1","text":"\"Free Kittens\""},{"id":"wyr-30-2","text":"\"Mystery Spot Ahead\""},{"id":"wyr-30-3","text":"\"Home of the Giant Rubber Duck\""},{"id":"wyr-30-4","text":"\"Haunted Bridge, Proceed with Caution\""},{"id":"wyr-30-5","text":"\"Best Pie in 3 States\""}]'::jsonb,
     null),
    ('easy',
     'Which car snack would you regret bringing the most?',
     '[{"id":"wyr-31-0","text":"Extra garlicky chips"},{"id":"wyr-31-1","text":"A whole durian"},{"id":"wyr-31-2","text":"Warm milk in a thermos"},{"id":"wyr-31-3","text":"Crumbly crackers everywhere"},{"id":"wyr-31-4","text":"Gum that lost its flavor in 2 minutes"},{"id":"wyr-31-5","text":"A soda that''s mostly foam"}]'::jsonb,
     null),
    ('medium',
     'Which family road trip tradition would you keep forever?',
     '[{"id":"wyr-32-0","text":"A \"first one to see the ocean\" shout"},{"id":"wyr-32-1","text":"A silly nickname for every gas station"},{"id":"wyr-32-2","text":"A road trip photo at every state sign"},{"id":"wyr-32-3","text":"A car karaoke hour"},{"id":"wyr-32-4","text":"A snack rotation system"},{"id":"wyr-32-5","text":"A \"guess the mileage\" game"}]'::jsonb,
     null),
    ('hard',
     'Which unexpected road hazard would slow you down the most?',
     '[{"id":"wyr-33-0","text":"A parade crossing the highway"},{"id":"wyr-33-1","text":"A herd of cows on the road"},{"id":"wyr-33-2","text":"A marching band rehearsal"},{"id":"wyr-33-3","text":"A film crew blocking one lane"},{"id":"wyr-33-4","text":"A hot air balloon landing in the road"},{"id":"wyr-33-5","text":"A runaway inflatable bounce house"}]'::jsonb,
     null),
    ('easy',
     'Which car nap position would you be stuck with for hours?',
     '[{"id":"wyr-34-0","text":"Head against the window (every bump)"},{"id":"wyr-34-1","text":"Neck at a painful angle"},{"id":"wyr-34-2","text":"Sitting bolt upright"},{"id":"wyr-34-3","text":"Squished in the middle seat"},{"id":"wyr-34-4","text":"Feet up on the dashboard"},{"id":"wyr-34-5","text":"Using a sibling''s shoulder (against their will)"}]'::jsonb,
     null),
    ('medium',
     'Which "we''re lost" moment would be the most stressful?',
     '[{"id":"wyr-35-0","text":"No cell signal and no map"},{"id":"wyr-35-1","text":"A GPS that keeps rerouting in circles"},{"id":"wyr-35-2","text":"Running low on gas while lost"},{"id":"wyr-35-3","text":"It''s getting dark and you''re still lost"},{"id":"wyr-35-4","text":"Everyone in the car has a different opinion on where to go"},{"id":"wyr-35-5","text":"The one person who knows the way is asleep"}]'::jsonb,
     null),
    ('medium',
     'Which travel-sized version of something would you be most annoyed to be stuck with?',
     '[{"id":"wyr-36-0","text":"A travel pillow that deflates"},{"id":"wyr-36-1","text":"A phone charger that barely reaches"},{"id":"wyr-36-2","text":"A tiny bag of chips that''s mostly air"},{"id":"wyr-36-3","text":"A pocket-sized umbrella in a downpour"},{"id":"wyr-36-4","text":"A mini flashlight with a dying battery"},{"id":"wyr-36-5","text":"A sample-sized bottle of sunscreen for a whole beach day"}]'::jsonb,
     null),
    ('easy',
     'Which type of traffic jam would test your patience the most?',
     '[{"id":"wyr-37-0","text":"One caused by nothing you can see"},{"id":"wyr-37-1","text":"One next to a very slow ice cream truck"},{"id":"wyr-37-2","text":"One where everyone''s honking for no reason"},{"id":"wyr-37-3","text":"One caused by a spilled truckload of something silly"},{"id":"wyr-37-4","text":"One where your exit is juuust ahead"},{"id":"wyr-37-5","text":"One caused by a very confused goose"}]'::jsonb,
     null),
    ('medium',
     'Which car repair would you be least equipped to handle yourselves?',
     '[{"id":"wyr-38-0","text":"A flat tire with no spare"},{"id":"wyr-38-1","text":"A dead battery with no jumper cables"},{"id":"wyr-38-2","text":"A check engine light with no manual"},{"id":"wyr-38-3","text":"A cracked windshield mid-drive"},{"id":"wyr-38-4","text":"An overheating engine"},{"id":"wyr-38-5","text":"A broken AC in the middle of summer"}]'::jsonb,
     null),
    ('medium',
     'Which "roughing it" camping surprise would you handle worst?',
     '[{"id":"wyr-39-0","text":"No cell signal for 3 days"},{"id":"wyr-39-1","text":"A raccoon raiding the snacks"},{"id":"wyr-39-2","text":"Rain on the one night you forgot the tarp"},{"id":"wyr-39-3","text":"A tent that''s suspiciously smaller than advertised"},{"id":"wyr-39-4","text":"Bugs everywhere at sunset"},{"id":"wyr-39-5","text":"Realizing you forgot the marshmallows"}]'::jsonb,
     null),
    ('hard',
     'Which final stretch of the trip would drag the most?',
     '[{"id":"wyr-40-0","text":"The last hour with everyone asleep but you"},{"id":"wyr-40-1","text":"The last hour stuck behind a slow truck"},{"id":"wyr-40-2","text":"The last hour with a full bladder and no exit"},{"id":"wyr-40-3","text":"The last hour of a sibling asking \"are we there yet\""},{"id":"wyr-40-4","text":"The last hour in bumper-to-bumper traffic"},{"id":"wyr-40-5","text":"The last hour realizing you''re going the wrong way"}]'::jsonb,
     null)
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'movie-quote-mashup'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'Which movie is this from? "To infinity and beyond!"',
     '[{"id":"mqm-1-0","text":"Toy Story"},{"id":"mqm-1-1","text":"Cars"},{"id":"mqm-1-2","text":"The Incredibles"},{"id":"mqm-1-3","text":"Monsters, Inc."},{"id":"mqm-1-4","text":"Finding Nemo"},{"id":"mqm-1-5","text":"Shrek"}]'::jsonb,
     'mqm-1-0'),
    ('easy',
     'Which movie is this from? "Just keep swimming."',
     '[{"id":"mqm-2-0","text":"Finding Nemo"},{"id":"mqm-2-1","text":"Moana"},{"id":"mqm-2-2","text":"The Little Mermaid"},{"id":"mqm-2-3","text":"Shark Tale"},{"id":"mqm-2-4","text":"Free Willy"},{"id":"mqm-2-5","text":"Finding Dory"}]'::jsonb,
     'mqm-2-0'),
    ('easy',
     'Which movie is this from? "Hakuna Matata, what a wonderful phrase."',
     '[{"id":"mqm-3-0","text":"The Lion King"},{"id":"mqm-3-1","text":"Madagascar"},{"id":"mqm-3-2","text":"Zootopia"},{"id":"mqm-3-3","text":"Tarzan"},{"id":"mqm-3-4","text":"The Jungle Book"},{"id":"mqm-3-5","text":"Ice Age"}]'::jsonb,
     'mqm-3-0'),
    ('easy',
     'Which movie is this from? "There''s no place like home."',
     '[{"id":"mqm-4-0","text":"The Wizard of Oz"},{"id":"mqm-4-1","text":"Alice in Wonderland"},{"id":"mqm-4-2","text":"Peter Pan"},{"id":"mqm-4-3","text":"Mary Poppins"},{"id":"mqm-4-4","text":"Charlie and the Chocolate Factory"},{"id":"mqm-4-5","text":"The Chronicles of Narnia"}]'::jsonb,
     'mqm-4-0'),
    ('easy',
     'Which movie is this from? "You''re a wizard, Harry."',
     '[{"id":"mqm-5-0","text":"Harry Potter and the Sorcerer''s Stone"},{"id":"mqm-5-1","text":"The Chronicles of Narnia"},{"id":"mqm-5-2","text":"The Hobbit"},{"id":"mqm-5-3","text":"Percy Jackson & the Olympians"},{"id":"mqm-5-4","text":"Fantastic Beasts and Where to Find Them"},{"id":"mqm-5-5","text":"Shrek"}]'::jsonb,
     'mqm-5-0'),
    ('easy',
     'Which movie is this from? "It''s so fluffy I''m gonna die!"',
     '[{"id":"mqm-6-0","text":"Despicable Me"},{"id":"mqm-6-1","text":"Minions"},{"id":"mqm-6-2","text":"The Secret Life of Pets"},{"id":"mqm-6-3","text":"Hop"},{"id":"mqm-6-4","text":"Sing"},{"id":"mqm-6-5","text":"Trolls"}]'::jsonb,
     'mqm-6-0'),
    ('easy',
     'Which movie is this from? "Bibbidi-Bobbidi-Boo."',
     '[{"id":"mqm-7-0","text":"Cinderella"},{"id":"mqm-7-1","text":"Sleeping Beauty"},{"id":"mqm-7-2","text":"Snow White and the Seven Dwarfs"},{"id":"mqm-7-3","text":"Frozen"},{"id":"mqm-7-4","text":"Enchanted"},{"id":"mqm-7-5","text":"Tangled"}]'::jsonb,
     'mqm-7-0'),
    ('easy',
     'Which movie is this from? "E.T. phone home."',
     '[{"id":"mqm-8-0","text":"E.T. the Extra-Terrestrial"},{"id":"mqm-8-1","text":"Close Encounters of the Third Kind"},{"id":"mqm-8-2","text":"Lilo & Stitch"},{"id":"mqm-8-3","text":"Flight of the Navigator"},{"id":"mqm-8-4","text":"Mars Attacks"},{"id":"mqm-8-5","text":"Paul"}]'::jsonb,
     'mqm-8-0'),
    ('easy',
     'Which movie is this from? "With great power comes great responsibility."',
     '[{"id":"mqm-9-0","text":"Spider-Man"},{"id":"mqm-9-1","text":"Batman Begins"},{"id":"mqm-9-2","text":"Iron Man"},{"id":"mqm-9-3","text":"Superman"},{"id":"mqm-9-4","text":"The Incredibles"},{"id":"mqm-9-5","text":"Big Hero 6"}]'::jsonb,
     'mqm-9-0'),
    ('easy',
     'Which movie is this from? "Ogres are like onions."',
     '[{"id":"mqm-10-0","text":"Shrek"},{"id":"mqm-10-1","text":"Puss in Boots"},{"id":"mqm-10-2","text":"Trolls"},{"id":"mqm-10-3","text":"Hotel Transylvania"},{"id":"mqm-10-4","text":"The Princess Bride"},{"id":"mqm-10-5","text":"Ella Enchanted"}]'::jsonb,
     'mqm-10-0'),
    ('easy',
     'Which movie is this from? "Some people are worth melting for."',
     '[{"id":"mqm-11-0","text":"Frozen"},{"id":"mqm-11-1","text":"Frozen II"},{"id":"mqm-11-2","text":"Ice Age"},{"id":"mqm-11-3","text":"Happy Feet"},{"id":"mqm-11-4","text":"The Snowman"},{"id":"mqm-11-5","text":"Klaus"}]'::jsonb,
     'mqm-11-0'),
    ('easy',
     'Which movie is this from? "The ocean chose you."',
     '[{"id":"mqm-12-0","text":"Moana"},{"id":"mqm-12-1","text":"Aquaman"},{"id":"mqm-12-2","text":"The Little Mermaid"},{"id":"mqm-12-3","text":"Finding Nemo"},{"id":"mqm-12-4","text":"Pirates of the Caribbean"},{"id":"mqm-12-5","text":"Life of Pi"}]'::jsonb,
     'mqm-12-0'),
    ('easy',
     'Which movie is this from? "No capes!"',
     '[{"id":"mqm-13-0","text":"The Incredibles"},{"id":"mqm-13-1","text":"Sky High"},{"id":"mqm-13-2","text":"Big Hero 6"},{"id":"mqm-13-3","text":"Megamind"},{"id":"mqm-13-4","text":"Despicable Me"},{"id":"mqm-13-5","text":"The Boy and the Heron"}]'::jsonb,
     'mqm-13-0'),
    ('easy',
     'Which movie is this from? "Adventure is out there!"',
     '[{"id":"mqm-14-0","text":"Up"},{"id":"mqm-14-1","text":"The Secret Life of Walter Mitty"},{"id":"mqm-14-2","text":"Onward"},{"id":"mqm-14-3","text":"Brave"},{"id":"mqm-14-4","text":"The Jungle Book"},{"id":"mqm-14-5","text":"Coco"}]'::jsonb,
     'mqm-14-0'),
    ('easy',
     'Which movie is this from? "Anyone can cook."',
     '[{"id":"mqm-15-0","text":"Ratatouille"},{"id":"mqm-15-1","text":"Cloudy with a Chance of Meatballs"},{"id":"mqm-15-2","text":"Kung Fu Panda"},{"id":"mqm-15-3","text":"Chef"},{"id":"mqm-15-4","text":"The Grand Budapest Hotel"},{"id":"mqm-15-5","text":"Julie & Julia"}]'::jsonb,
     'mqm-15-0'),
    ('medium',
     'Which movie is this from? "May the Force be with you."',
     '[{"id":"mqm-16-0","text":"Star Wars: Episode IV – A New Hope"},{"id":"mqm-16-1","text":"Star Trek"},{"id":"mqm-16-2","text":"Guardians of the Galaxy"},{"id":"mqm-16-3","text":"Men in Black"},{"id":"mqm-16-4","text":"The Fifth Element"},{"id":"mqm-16-5","text":"Interstellar"}]'::jsonb,
     'mqm-16-0'),
    ('medium',
     'Which movie is this from? "Life finds a way."',
     '[{"id":"mqm-17-0","text":"Jurassic Park"},{"id":"mqm-17-1","text":"Jurassic World"},{"id":"mqm-17-2","text":"King Kong"},{"id":"mqm-17-3","text":"Godzilla"},{"id":"mqm-17-4","text":"The Land Before Time"},{"id":"mqm-17-5","text":"Rio"}]'::jsonb,
     'mqm-17-0'),
    ('medium',
     'Which movie is this from? "Great Scott!"',
     '[{"id":"mqm-18-0","text":"Back to the Future"},{"id":"mqm-18-1","text":"Doctor Strange"},{"id":"mqm-18-2","text":"Sherlock Holmes"},{"id":"mqm-18-3","text":"The Time Machine"},{"id":"mqm-18-4","text":"A Wrinkle in Time"},{"id":"mqm-18-5","text":"Hugo"}]'::jsonb,
     'mqm-18-0'),
    ('medium',
     'Which movie is this from? "Life is like a box of chocolates."',
     '[{"id":"mqm-19-0","text":"Forrest Gump"},{"id":"mqm-19-1","text":"Big"},{"id":"mqm-19-2","text":"The Sandlot"},{"id":"mqm-19-3","text":"Charlie and the Chocolate Factory"},{"id":"mqm-19-4","text":"Cast Away"},{"id":"mqm-19-5","text":"The Terminal"}]'::jsonb,
     'mqm-19-0'),
    ('medium',
     'Which movie is this from? "I feel the need... the need for speed."',
     '[{"id":"mqm-20-0","text":"Top Gun"},{"id":"mqm-20-1","text":"Cars"},{"id":"mqm-20-2","text":"Speed Racer"},{"id":"mqm-20-3","text":"The Fast and the Furious"},{"id":"mqm-20-4","text":"Rush"},{"id":"mqm-20-5","text":"Days of Thunder"}]'::jsonb,
     'mqm-20-0'),
    ('medium',
     'Which movie is this from? "Houston, we have a problem."',
     '[{"id":"mqm-21-0","text":"Apollo 13"},{"id":"mqm-21-1","text":"Gravity"},{"id":"mqm-21-2","text":"The Martian"},{"id":"mqm-21-3","text":"Interstellar"},{"id":"mqm-21-4","text":"Armageddon"},{"id":"mqm-21-5","text":"First Man"}]'::jsonb,
     'mqm-21-0'),
    ('medium',
     'Which movie is this from? "You shall not pass!"',
     '[{"id":"mqm-22-0","text":"The Lord of the Rings: The Fellowship of the Ring"},{"id":"mqm-22-1","text":"The Hobbit: An Unexpected Journey"},{"id":"mqm-22-2","text":"Harry Potter and the Goblet of Fire"},{"id":"mqm-22-3","text":"Willow"},{"id":"mqm-22-4","text":"The Chronicles of Narnia"},{"id":"mqm-22-5","text":"Eragon"}]'::jsonb,
     'mqm-22-0'),
    ('medium',
     'Which movie is this from? "Not all treasure is silver and gold, mate."',
     '[{"id":"mqm-23-0","text":"Pirates of the Caribbean: The Curse of the Black Pearl"},{"id":"mqm-23-1","text":"Treasure Planet"},{"id":"mqm-23-2","text":"Hook"},{"id":"mqm-23-3","text":"Peter Pan"},{"id":"mqm-23-4","text":"The Goonies"},{"id":"mqm-23-5","text":"Moana"}]'::jsonb,
     'mqm-23-0'),
    ('medium',
     'Which movie is this from? "To boldly go where no man has gone before."',
     '[{"id":"mqm-24-0","text":"Star Trek"},{"id":"mqm-24-1","text":"Star Wars: Episode IV – A New Hope"},{"id":"mqm-24-2","text":"Interstellar"},{"id":"mqm-24-3","text":"Guardians of the Galaxy"},{"id":"mqm-24-4","text":"Lost in Space"},{"id":"mqm-24-5","text":"The Martian"}]'::jsonb,
     'mqm-24-0'),
    ('medium',
     'Which movie is this from? "I''m the king of the world!"',
     '[{"id":"mqm-25-0","text":"Titanic"},{"id":"mqm-25-1","text":"Pearl Harbor"},{"id":"mqm-25-2","text":"The Aviator"},{"id":"mqm-25-3","text":"Master and Commander"},{"id":"mqm-25-4","text":"Gladiator"},{"id":"mqm-25-5","text":"Braveheart"}]'::jsonb,
     'mqm-25-0'),
    ('medium',
     'Which movie is this from? "Hasta la vista, baby."',
     '[{"id":"mqm-26-0","text":"Terminator 2: Judgment Day"},{"id":"mqm-26-1","text":"The Terminator"},{"id":"mqm-26-2","text":"RoboCop"},{"id":"mqm-26-3","text":"Predator"},{"id":"mqm-26-4","text":"Total Recall"},{"id":"mqm-26-5","text":"Commando"}]'::jsonb,
     'mqm-26-0'),
    ('medium',
     'Which movie is this from? "I''ll be back."',
     '[{"id":"mqm-27-0","text":"The Terminator"},{"id":"mqm-27-1","text":"Terminator 2: Judgment Day"},{"id":"mqm-27-2","text":"RoboCop"},{"id":"mqm-27-3","text":"Predator"},{"id":"mqm-27-4","text":"Total Recall"},{"id":"mqm-27-5","text":"True Lies"}]'::jsonb,
     'mqm-27-0'),
    ('medium',
     'Which movie is this from? "Keep the change, ya filthy animal."',
     '[{"id":"mqm-28-0","text":"Home Alone"},{"id":"mqm-28-1","text":"Home Alone 2: Lost in New York"},{"id":"mqm-28-2","text":"The Sandlot"},{"id":"mqm-28-3","text":"Uncle Buck"},{"id":"mqm-28-4","text":"Angels in the Outfield"},{"id":"mqm-28-5","text":"Richie Rich"}]'::jsonb,
     'mqm-28-0'),
    ('medium',
     'Which movie is this from? "The best way to spread Christmas cheer is singing loud for all to hear."',
     '[{"id":"mqm-29-0","text":"Elf"},{"id":"mqm-29-1","text":"The Santa Clause"},{"id":"mqm-29-2","text":"How the Grinch Stole Christmas"},{"id":"mqm-29-3","text":"The Polar Express"},{"id":"mqm-29-4","text":"A Christmas Story"},{"id":"mqm-29-5","text":"Home Alone"}]'::jsonb,
     'mqm-29-0'),
    ('hard',
     'Which movie is this from? "It is our choices, Harry, that show what we truly are."',
     '[{"id":"mqm-30-0","text":"Harry Potter and the Chamber of Secrets"},{"id":"mqm-30-1","text":"Harry Potter and the Sorcerer''s Stone"},{"id":"mqm-30-2","text":"The Chronicles of Narnia"},{"id":"mqm-30-3","text":"Star Wars: Episode V – The Empire Strikes Back"},{"id":"mqm-30-4","text":"The Hobbit"},{"id":"mqm-30-5","text":"Percy Jackson & the Olympians"}]'::jsonb,
     'mqm-30-0'),
    ('hard',
     'Which movie is this from? "I am inevitable."',
     '[{"id":"mqm-31-0","text":"Avengers: Endgame"},{"id":"mqm-31-1","text":"Avengers: Infinity War"},{"id":"mqm-31-2","text":"The Avengers"},{"id":"mqm-31-3","text":"Iron Man"},{"id":"mqm-31-4","text":"Guardians of the Galaxy"},{"id":"mqm-31-5","text":"Thor: Ragnarok"}]'::jsonb,
     'mqm-31-0'),
    ('hard',
     'Which movie is this from? "I see dead people."',
     '[{"id":"mqm-32-0","text":"The Sixth Sense"},{"id":"mqm-32-1","text":"Ghost"},{"id":"mqm-32-2","text":"Poltergeist"},{"id":"mqm-32-3","text":"Coco"},{"id":"mqm-32-4","text":"The Others"},{"id":"mqm-32-5","text":"Beetlejuice"}]'::jsonb,
     'mqm-32-0'),
    ('hard',
     'Which movie is this from? "You can''t handle the truth!"',
     '[{"id":"mqm-33-0","text":"A Few Good Men"},{"id":"mqm-33-1","text":"Twelve Angry Men"},{"id":"mqm-33-2","text":"My Cousin Vinny"},{"id":"mqm-33-3","text":"Erin Brockovich"},{"id":"mqm-33-4","text":"The Verdict"},{"id":"mqm-33-5","text":"Philadelphia"}]'::jsonb,
     'mqm-33-0'),
    ('hard',
     'Which movie is this from? "You had me at hello."',
     '[{"id":"mqm-34-0","text":"Jerry Maguire"},{"id":"mqm-34-1","text":"Notting Hill"},{"id":"mqm-34-2","text":"You''ve Got Mail"},{"id":"mqm-34-3","text":"Sleepless in Seattle"},{"id":"mqm-34-4","text":"While You Were Sleeping"},{"id":"mqm-34-5","text":"27 Dresses"}]'::jsonb,
     'mqm-34-0'),
    ('hard',
     'Which movie is this from? "Nobody puts Baby in a corner."',
     '[{"id":"mqm-35-0","text":"Dirty Dancing"},{"id":"mqm-35-1","text":"Footloose"},{"id":"mqm-35-2","text":"Flashdance"},{"id":"mqm-35-3","text":"Grease"},{"id":"mqm-35-4","text":"Save the Last Dance"},{"id":"mqm-35-5","text":"Step Up"}]'::jsonb,
     'mqm-35-0'),
    ('hard',
     'Which movie is this from? "Bueller? Bueller?"',
     '[{"id":"mqm-36-0","text":"Ferris Bueller''s Day Off"},{"id":"mqm-36-1","text":"Fast Times at Ridgemont High"},{"id":"mqm-36-2","text":"The Breakfast Club"},{"id":"mqm-36-3","text":"Sixteen Candles"},{"id":"mqm-36-4","text":"Clueless"},{"id":"mqm-36-5","text":"Napoleon Dynamite"}]'::jsonb,
     'mqm-36-0'),
    ('hard',
     'Which movie is this from? "Here''s looking at you, kid."',
     '[{"id":"mqm-37-0","text":"Casablanca"},{"id":"mqm-37-1","text":"Gone with the Wind"},{"id":"mqm-37-2","text":"Roman Holiday"},{"id":"mqm-37-3","text":"An Affair to Remember"},{"id":"mqm-37-4","text":"Breakfast at Tiffany''s"},{"id":"mqm-37-5","text":"North by Northwest"}]'::jsonb,
     'mqm-37-0'),
    ('hard',
     'Which movie is this from? "I''ll have what she''s having."',
     '[{"id":"mqm-38-0","text":"When Harry Met Sally"},{"id":"mqm-38-1","text":"Sleepless in Seattle"},{"id":"mqm-38-2","text":"Annie Hall"},{"id":"mqm-38-3","text":"You''ve Got Mail"},{"id":"mqm-38-4","text":"The Princess Bride"},{"id":"mqm-38-5","text":"Groundhog Day"}]'::jsonb,
     'mqm-38-0'),
    ('hard',
     'Which movie is this from? "You''re gonna need a bigger boat."',
     '[{"id":"mqm-39-0","text":"Jaws"},{"id":"mqm-39-1","text":"Jaws 2"},{"id":"mqm-39-2","text":"The Perfect Storm"},{"id":"mqm-39-3","text":"Deep Blue Sea"},{"id":"mqm-39-4","text":"The Meg"},{"id":"mqm-39-5","text":"Moby Dick"}]'::jsonb,
     'mqm-39-0'),
    ('hard',
     'Which movie is this from? "Yippee-ki-yay!"',
     '[{"id":"mqm-40-0","text":"Die Hard"},{"id":"mqm-40-1","text":"Die Hard 2"},{"id":"mqm-40-2","text":"Lethal Weapon"},{"id":"mqm-40-3","text":"RoboCop"},{"id":"mqm-40-4","text":"The Fifth Element"},{"id":"mqm-40-5","text":"Speed"}]'::jsonb,
     'mqm-40-0')
) as q (difficulty, prompt, options, correct_option_id);
