-- Travel Trivia — audio genre seed content (Animal Sounds Safari,
-- Sound FX Guess, Name That Tune). Mirrors the app's bundled
-- AudioSeedQuestions.swift (see Travel Trivia/Models/AudioSeedQuestions.swift
-- for the full sourcing rationale).
--
-- Sourcing: the original plan was Freesound + Zapsplat (animal/SFX) and
-- Jamendo (music) free-tier APIs. Both Freesound and Jamendo require a
-- registered client_id from an account signup this automated session
-- couldn't complete (no anonymous access; a shared Jamendo test client_id
-- came back suspended). Zapsplat needs manual curation per the original
-- sourcing decision and was skipped here for the same reason. Every clip
-- below is instead a real, CC-licensed audio file fetched live from the
-- Wikimedia Commons API — same attribution obligations as Freesound would
-- have carried, just a different catalog. media_url stores a bundle-
-- relative path ("<genre-slug>/<file>.m4a"), not the original Wikimedia
-- URL, because the client plays the pre-transcoded bundled clip (iOS/
-- AVFoundation can't decode the source Ogg Vorbis files directly) — the
-- full original title/author/license lives in `attribution` instead.
--
-- Name That Tune uses public-domain classical pieces rather than pop
-- songs, sidestepping the sync/performance licensing risk flagged as
-- unresolved in 2026-07-25_question-format-and-content-sourcing.md.

alter table public.questions drop constraint questions_source_check;
alter table public.questions add constraint questions_source_check
    check (source in ('generated', 'open_trivia_db', 'wikimedia_commons'));

-- animal-sounds-safari (13 questions)
with genre as (
    select id from public.genres where slug = 'animal-sounds-safari'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('easy', 'Which animal made this sound?', '[{"id":"asf-1-0","text":"Cat"},{"id":"asf-1-1","text":"Chicken"},{"id":"asf-1-2","text":"Cow"},{"id":"asf-1-3","text":"Cricket"},{"id":"asf-1-4","text":"Cuckoo"},{"id":"asf-1-5","text":"Dog"}]'::jsonb, 'asf-1-0', 'animal-sounds-safari/cat.m4a', '"Meow of a pleading cat.oga" by Heismark (Public domain), via Wikimedia Commons'),
    ('easy', 'Which animal made this sound?', '[{"id":"asf-2-0","text":"Chicken"},{"id":"asf-2-1","text":"Cow"},{"id":"asf-2-2","text":"Cricket"},{"id":"asf-2-3","text":"Cuckoo"},{"id":"asf-2-4","text":"Dog"},{"id":"asf-2-5","text":"Elephant"}]'::jsonb, 'asf-2-0', 'animal-sounds-safari/chicken.m4a', '"Chickens demanding food.ogg" by alys (Public domain), via Wikimedia Commons'),
    ('easy', 'Which animal made this sound?', '[{"id":"asf-3-0","text":"Cow"},{"id":"asf-3-1","text":"Cricket"},{"id":"asf-3-2","text":"Cuckoo"},{"id":"asf-3-3","text":"Dog"},{"id":"asf-3-4","text":"Elephant"},{"id":"asf-3-5","text":"Frog"}]'::jsonb, 'asf-3-0', 'animal-sounds-safari/cow.m4a', '"Single Cow Moo.ogg" by MichaeltheFox8621 (CC BY-SA 4.0), via Wikimedia Commons'),
    ('easy', 'Which animal made this sound?', '[{"id":"asf-4-0","text":"Cricket"},{"id":"asf-4-1","text":"Cuckoo"},{"id":"asf-4-2","text":"Dog"},{"id":"asf-4-3","text":"Elephant"},{"id":"asf-4-4","text":"Frog"},{"id":"asf-4-5","text":"Horse"}]'::jsonb, 'asf-4-0', 'animal-sounds-safari/cricket.m4a', '"Field cricket unedited.ogg" by Thatcher (CC BY-SA 3.0), via Wikimedia Commons'),
    ('easy', 'Which animal made this sound?', '[{"id":"asf-5-0","text":"Cuckoo"},{"id":"asf-5-1","text":"Dog"},{"id":"asf-5-2","text":"Elephant"},{"id":"asf-5-3","text":"Frog"},{"id":"asf-5-4","text":"Horse"},{"id":"asf-5-5","text":"Lion"}]'::jsonb, 'asf-5-0', 'animal-sounds-safari/cuckoo.m4a', '"Great Spotted Cuckoo call (Clamator glandarius).ogg" by João Tomás (CC BY 4.0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-6-0","text":"Dog"},{"id":"asf-6-1","text":"Elephant"},{"id":"asf-6-2","text":"Frog"},{"id":"asf-6-3","text":"Horse"},{"id":"asf-6-4","text":"Lion"},{"id":"asf-6-5","text":"Owl"}]'::jsonb, 'asf-6-0', 'animal-sounds-safari/dog.m4a', '"Barking of a dog 2.ogg" by Amada44 (CC BY-SA 3.0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-7-0","text":"Elephant"},{"id":"asf-7-1","text":"Frog"},{"id":"asf-7-2","text":"Horse"},{"id":"asf-7-3","text":"Lion"},{"id":"asf-7-4","text":"Owl"},{"id":"asf-7-5","text":"Rooster"}]'::jsonb, 'asf-7-0', 'animal-sounds-safari/elephant.m4a', '"Elephant voice - trumpeting.ogg" by தகவலுழவன் (CC0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-8-0","text":"Frog"},{"id":"asf-8-1","text":"Horse"},{"id":"asf-8-2","text":"Lion"},{"id":"asf-8-3","text":"Owl"},{"id":"asf-8-4","text":"Rooster"},{"id":"asf-8-5","text":"Sheep"}]'::jsonb, 'asf-8-0', 'animal-sounds-safari/frog.m4a', '"Single Frog Croak.oga" by MichaeltheFox8621 (CC BY-SA 4.0), via Wikimedia Commons'),
    ('medium', 'Which animal made this sound?', '[{"id":"asf-9-0","text":"Horse"},{"id":"asf-9-1","text":"Lion"},{"id":"asf-9-2","text":"Owl"},{"id":"asf-9-3","text":"Rooster"},{"id":"asf-9-4","text":"Sheep"},{"id":"asf-9-5","text":"Cat"}]'::jsonb, 'asf-9-0', 'animal-sounds-safari/horse.m4a', '"Wiehern.ogg" by Hü. (Public domain), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-10-0","text":"Lion"},{"id":"asf-10-1","text":"Owl"},{"id":"asf-10-2","text":"Rooster"},{"id":"asf-10-3","text":"Sheep"},{"id":"asf-10-4","text":"Cat"},{"id":"asf-10-5","text":"Chicken"}]'::jsonb, 'asf-10-0', 'animal-sounds-safari/lion.m4a', '"Lion raring-sound1TamilNadu178.ogg" by த*உழவன் (Public domain), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-11-0","text":"Owl"},{"id":"asf-11-1","text":"Rooster"},{"id":"asf-11-2","text":"Sheep"},{"id":"asf-11-3","text":"Cat"},{"id":"asf-11-4","text":"Chicken"},{"id":"asf-11-5","text":"Cow"}]'::jsonb, 'asf-11-0', 'animal-sounds-safari/owl.m4a', '"Strix aluco male.oga" by Vianney Bajart (CC BY-SA 4.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-12-0","text":"Rooster"},{"id":"asf-12-1","text":"Sheep"},{"id":"asf-12-2","text":"Cat"},{"id":"asf-12-3","text":"Chicken"},{"id":"asf-12-4","text":"Cow"},{"id":"asf-12-5","text":"Cricket"}]'::jsonb, 'asf-12-0', 'animal-sounds-safari/rooster.m4a', '"Rooster crowing.ogg" by Filo gèn'' (CC BY-SA 4.0), via Wikimedia Commons'),
    ('hard', 'Which animal made this sound?', '[{"id":"asf-13-0","text":"Sheep"},{"id":"asf-13-1","text":"Cat"},{"id":"asf-13-2","text":"Chicken"},{"id":"asf-13-3","text":"Cow"},{"id":"asf-13-4","text":"Cricket"},{"id":"asf-13-5","text":"Cuckoo"}]'::jsonb, 'asf-13-0', 'animal-sounds-safari/sheep.m4a', '"Sheep bleating.ogg" by earthcalling (Public domain), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);

-- sound-fx-guess (10 questions)
with genre as (
    select id from public.genres where slug = 'sound-fx-guess'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('easy', 'What sound effect is this?', '[{"id":"sfx-1-0","text":"Alarm Clock"},{"id":"sfx-1-1","text":"Applause"},{"id":"sfx-1-2","text":"Camera Shutter"},{"id":"sfx-1-3","text":"Race Car Engine"},{"id":"sfx-1-4","text":"Church Bell"},{"id":"sfx-1-5","text":"Door Knock"}]'::jsonb, 'sfx-1-0', 'sound-fx-guess/alarm-clock.m4a', '"Alarm clock - 01.ogg" by Mathieu Kappler (CC BY-SA 4.0), via Wikimedia Commons'),
    ('easy', 'What sound effect is this?', '[{"id":"sfx-2-0","text":"Applause"},{"id":"sfx-2-1","text":"Camera Shutter"},{"id":"sfx-2-2","text":"Race Car Engine"},{"id":"sfx-2-3","text":"Church Bell"},{"id":"sfx-2-4","text":"Door Knock"},{"id":"sfx-2-5","text":"Geese Honking"}]'::jsonb, 'sfx-2-0', 'sound-fx-guess/applause.m4a', '"Clapping hurray (cropped).oga" by Starlite (Public domain), via Wikimedia Commons'),
    ('easy', 'What sound effect is this?', '[{"id":"sfx-3-0","text":"Camera Shutter"},{"id":"sfx-3-1","text":"Race Car Engine"},{"id":"sfx-3-2","text":"Church Bell"},{"id":"sfx-3-3","text":"Door Knock"},{"id":"sfx-3-4","text":"Geese Honking"},{"id":"sfx-3-5","text":"Keyboard Typing"}]'::jsonb, 'sfx-3-0', 'sound-fx-guess/camera-shutter.m4a', '"Canon T50 shutter noise.ogg" by Francois C (CC BY-SA 3.0), via Wikimedia Commons'),
    ('easy', 'What sound effect is this?', '[{"id":"sfx-4-0","text":"Race Car Engine"},{"id":"sfx-4-1","text":"Church Bell"},{"id":"sfx-4-2","text":"Door Knock"},{"id":"sfx-4-3","text":"Geese Honking"},{"id":"sfx-4-4","text":"Keyboard Typing"},{"id":"sfx-4-5","text":"Police Siren"}]'::jsonb, 'sfx-4-0', 'sound-fx-guess/car-engine.m4a', '"Benetton-Ford B188 (1988).ogg" by Edvvc (CC BY-SA 3.0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-5-0","text":"Church Bell"},{"id":"sfx-5-1","text":"Door Knock"},{"id":"sfx-5-2","text":"Geese Honking"},{"id":"sfx-5-3","text":"Keyboard Typing"},{"id":"sfx-5-4","text":"Police Siren"},{"id":"sfx-5-5","text":"Train Whistle"}]'::jsonb, 'sfx-5-0', 'sound-fx-guess/church-bell.m4a', '"Bytom Margaret church John of Nepomuk bell ringing.ogg" by Adrian Tync (CC BY-SA 4.0), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-6-0","text":"Door Knock"},{"id":"sfx-6-1","text":"Geese Honking"},{"id":"sfx-6-2","text":"Keyboard Typing"},{"id":"sfx-6-3","text":"Police Siren"},{"id":"sfx-6-4","text":"Train Whistle"},{"id":"sfx-6-5","text":"Alarm Clock"}]'::jsonb, 'sfx-6-0', 'sound-fx-guess/door-knock.m4a', '"Knocking on wood or door.ogg" by stephan (Public domain), via Wikimedia Commons'),
    ('medium', 'What sound effect is this?', '[{"id":"sfx-7-0","text":"Geese Honking"},{"id":"sfx-7-1","text":"Keyboard Typing"},{"id":"sfx-7-2","text":"Police Siren"},{"id":"sfx-7-3","text":"Train Whistle"},{"id":"sfx-7-4","text":"Alarm Clock"},{"id":"sfx-7-5","text":"Applause"}]'::jsonb, 'sfx-7-0', 'sound-fx-guess/geese-honking.m4a', '"Geese Honking (loud).ogg" by U.S. Fish and Wildlife Service (Public domain), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-8-0","text":"Keyboard Typing"},{"id":"sfx-8-1","text":"Police Siren"},{"id":"sfx-8-2","text":"Train Whistle"},{"id":"sfx-8-3","text":"Alarm Clock"},{"id":"sfx-8-4","text":"Applause"},{"id":"sfx-8-5","text":"Camera Shutter"}]'::jsonb, 'sfx-8-0', 'sound-fx-guess/keyboard-typing.m4a', '"Typing - Model M13 1999.ogg" by Raymangold22 (CC0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-9-0","text":"Police Siren"},{"id":"sfx-9-1","text":"Train Whistle"},{"id":"sfx-9-2","text":"Alarm Clock"},{"id":"sfx-9-3","text":"Applause"},{"id":"sfx-9-4","text":"Camera Shutter"},{"id":"sfx-9-5","text":"Race Car Engine"}]'::jsonb, 'sfx-9-0', 'sound-fx-guess/police-siren.m4a', '"WWS Policecarsiren.ogg" by Work With Sounds / Konrad Gutkowski (CC BY 4.0), via Wikimedia Commons'),
    ('hard', 'What sound effect is this?', '[{"id":"sfx-10-0","text":"Train Whistle"},{"id":"sfx-10-1","text":"Alarm Clock"},{"id":"sfx-10-2","text":"Applause"},{"id":"sfx-10-3","text":"Camera Shutter"},{"id":"sfx-10-4","text":"Race Car Engine"},{"id":"sfx-10-5","text":"Church Bell"}]'::jsonb, 'sfx-10-0', 'sound-fx-guess/train-whistle.m4a', '"WWS SteamWhistle.ogg" by Work With Sounds / Konrad Gutkowski (CC BY 4.0), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);

-- name-that-tune (13 questions)
with genre as (
    select id from public.genres where slug = 'name-that-tune'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, media_url, attribution, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, q.media_url, q.attribution, 'wikimedia_commons'
from genre, (values
    ('easy', 'Name that tune!', '[{"id":"ntt-1-0","text":"Air on the G String"},{"id":"ntt-1-1","text":"The Blue Danube Waltz"},{"id":"ntt-1-2","text":"Flight of the Bumblebee"},{"id":"ntt-1-3","text":"The Four Seasons: Spring"},{"id":"ntt-1-4","text":"Für Elise"},{"id":"ntt-1-5","text":"In the Hall of the Mountain King"}]'::jsonb, 'ntt-1-0', 'name-that-tune/air-on-g-string.m4a', '"Air (Bach).ogg" by Unknown (Public domain), via Wikimedia Commons'),
    ('easy', 'Name that tune!', '[{"id":"ntt-2-0","text":"The Blue Danube Waltz"},{"id":"ntt-2-1","text":"Flight of the Bumblebee"},{"id":"ntt-2-2","text":"The Four Seasons: Spring"},{"id":"ntt-2-3","text":"Für Elise"},{"id":"ntt-2-4","text":"In the Hall of the Mountain King"},{"id":"ntt-2-5","text":"Moonlight Sonata"}]'::jsonb, 'ntt-2-0', 'name-that-tune/blue-danube.m4a', '"Polyphon - Donau-Walzer (Johann Strauss).ogg" by unbekannt, tot seit über 70 Jahren (CC0), via Wikimedia Commons'),
    ('easy', 'Name that tune!', '[{"id":"ntt-3-0","text":"Flight of the Bumblebee"},{"id":"ntt-3-1","text":"The Four Seasons: Spring"},{"id":"ntt-3-2","text":"Für Elise"},{"id":"ntt-3-3","text":"In the Hall of the Mountain King"},{"id":"ntt-3-4","text":"Moonlight Sonata"},{"id":"ntt-3-5","text":"Pomp and Circumstance"}]'::jsonb, 'ntt-3-0', 'name-that-tune/flight-of-the-bumblebee.m4a', '"Muriel-Nguyen-Xuan-Korsakov-Flight-of-the-bumblebee.flac.oga" by Play by Muriel Nguyen Xuan, recording by Stéphane Magnenat (CC BY-SA 3.0), via Wikimedia Commons'),
    ('easy', 'Name that tune!', '[{"id":"ntt-4-0","text":"The Four Seasons: Spring"},{"id":"ntt-4-1","text":"Für Elise"},{"id":"ntt-4-2","text":"In the Hall of the Mountain King"},{"id":"ntt-4-3","text":"Moonlight Sonata"},{"id":"ntt-4-4","text":"Pomp and Circumstance"},{"id":"ntt-4-5","text":"Ride of the Valkyries"}]'::jsonb, 'ntt-4-0', 'name-that-tune/four-seasons-spring.m4a', '"Vivaldi - Four Seasons 1 Spring mvt 1 Allegro - John Harrison violin.oga" by Antonio Vivaldi (CC BY-SA), via Wikimedia Commons'),
    ('easy', 'Name that tune!', '[{"id":"ntt-5-0","text":"Für Elise"},{"id":"ntt-5-1","text":"In the Hall of the Mountain King"},{"id":"ntt-5-2","text":"Moonlight Sonata"},{"id":"ntt-5-3","text":"Pomp and Circumstance"},{"id":"ntt-5-4","text":"Ride of the Valkyries"},{"id":"ntt-5-5","text":"Swan Lake"}]'::jsonb, 'ntt-5-0', 'name-that-tune/fur-elise.m4a', '"For Elise (Für Elise) Beethoven JMC Han.ogg" by Ludwig van Beethoven (CC BY-SA 4.0), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-6-0","text":"In the Hall of the Mountain King"},{"id":"ntt-6-1","text":"Moonlight Sonata"},{"id":"ntt-6-2","text":"Pomp and Circumstance"},{"id":"ntt-6-3","text":"Ride of the Valkyries"},{"id":"ntt-6-4","text":"Swan Lake"},{"id":"ntt-6-5","text":"Toccata and Fugue in D Minor"}]'::jsonb, 'ntt-6-0', 'name-that-tune/hall-of-the-mountain-king.m4a', '"Musopen - In the Hall Of The Mountain King.ogg" by Grieg, Edvard; Musopen Symphony Orchestra (Public domain), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-7-0","text":"Moonlight Sonata"},{"id":"ntt-7-1","text":"Pomp and Circumstance"},{"id":"ntt-7-2","text":"Ride of the Valkyries"},{"id":"ntt-7-3","text":"Swan Lake"},{"id":"ntt-7-4","text":"Toccata and Fugue in D Minor"},{"id":"ntt-7-5","text":"Turkish March"}]'::jsonb, 'ntt-7-0', 'name-that-tune/moonlight-sonata.m4a', '"Moonlight Sonata (Sharp c minor Sonata) 2nd Movement Beethoven JMC,Han.ogg" by Ludwig van Beethoven (CC BY-SA 4.0), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-8-0","text":"Pomp and Circumstance"},{"id":"ntt-8-1","text":"Ride of the Valkyries"},{"id":"ntt-8-2","text":"Swan Lake"},{"id":"ntt-8-3","text":"Toccata and Fugue in D Minor"},{"id":"ntt-8-4","text":"Turkish March"},{"id":"ntt-8-5","text":"William Tell Overture"}]'::jsonb, 'ntt-8-0', 'name-that-tune/pomp-and-circumstance.m4a', '"Pomp and circumstances No. 1.ogg" by Edward Elgar (1857–1934) (Public domain), via Wikimedia Commons'),
    ('medium', 'Name that tune!', '[{"id":"ntt-9-0","text":"Ride of the Valkyries"},{"id":"ntt-9-1","text":"Swan Lake"},{"id":"ntt-9-2","text":"Toccata and Fugue in D Minor"},{"id":"ntt-9-3","text":"Turkish March"},{"id":"ntt-9-4","text":"William Tell Overture"},{"id":"ntt-9-5","text":"Air on the G String"}]'::jsonb, 'ntt-9-0', 'name-that-tune/ride-of-the-valkyries.m4a', '"Richard Wagner - Ride of the Valkyries.ogg" by Richard Wagner (1813–1883) (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-10-0","text":"Swan Lake"},{"id":"ntt-10-1","text":"Toccata and Fugue in D Minor"},{"id":"ntt-10-2","text":"Turkish March"},{"id":"ntt-10-3","text":"William Tell Overture"},{"id":"ntt-10-4","text":"Air on the G String"},{"id":"ntt-10-5","text":"The Blue Danube Waltz"}]'::jsonb, 'ntt-10-0', 'name-that-tune/swan-lake.m4a', '"Peter Ilyich Tchaikovsky-Swan Lake- Extract from Act 3.ogg" by Ballet Francaise Symphony Orchestra (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-11-0","text":"Toccata and Fugue in D Minor"},{"id":"ntt-11-1","text":"Turkish March"},{"id":"ntt-11-2","text":"William Tell Overture"},{"id":"ntt-11-3","text":"Air on the G String"},{"id":"ntt-11-4","text":"The Blue Danube Waltz"},{"id":"ntt-11-5","text":"Flight of the Bumblebee"}]'::jsonb, 'ntt-11-0', 'name-that-tune/toccata-fugue.m4a', '"BachToccataAndFugueInDMinorOpeningPianoHiFi.ogg" by Opus33 at English Wikipedia (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-12-0","text":"Turkish March"},{"id":"ntt-12-1","text":"William Tell Overture"},{"id":"ntt-12-2","text":"Air on the G String"},{"id":"ntt-12-3","text":"The Blue Danube Waltz"},{"id":"ntt-12-4","text":"Flight of the Bumblebee"},{"id":"ntt-12-5","text":"The Four Seasons: Spring"}]'::jsonb, 'ntt-12-0', 'name-that-tune/turkish-march.m4a', '"Rondo Alla Turka.ogg" by Wolfgang Amadeus Mozart (Public domain), via Wikimedia Commons'),
    ('hard', 'Name that tune!', '[{"id":"ntt-13-0","text":"William Tell Overture"},{"id":"ntt-13-1","text":"Air on the G String"},{"id":"ntt-13-2","text":"The Blue Danube Waltz"},{"id":"ntt-13-3","text":"Flight of the Bumblebee"},{"id":"ntt-13-4","text":"The Four Seasons: Spring"},{"id":"ntt-13-5","text":"Für Elise"}]'::jsonb, 'ntt-13-0', 'name-that-tune/william-tell-overture.m4a', '"William Tell Overture - Edison.ogg" by Edison National Historic Site (Public domain), via Wikimedia Commons')
) as q(difficulty, prompt, options, correct_option_id, media_url, attribution);

