-- Travel Trivia — Would You Rather Round 5 (174 new questions)
-- Scales the bundled Would You Rather pool from 130 to 304 questions,
-- since WYR is the only genre with no fallback variety (every game is
-- WYR or nothing) and needed a deeper pool than the other text genres.
-- Mirrors the app's bundled SeedQuestions.swift "Round 5 additions";
-- correct_option_id stays null, same as every prior WYR batch.

with genre as (
    select id from public.genres where slug = 'would-you-rather'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'Which superpower would you actually use every single day?',
     '[{"id":"wyr-131-0","text":"Flying"},{"id":"wyr-131-1","text":"Invisibility"},{"id":"wyr-131-2","text":"Super strength"},{"id":"wyr-131-3","text":"Reading minds"},{"id":"wyr-131-4","text":"Freezing time"},{"id":"wyr-131-5","text":"Talking to animals"}]'::jsonb,
     null),
    ('medium',
     'Which power would be the most annoying to actually live with?',
     '[{"id":"wyr-132-0","text":"Hearing everyone's thoughts nonstop"},{"id":"wyr-132-1","text":"Never being able to turn invisibility off"},{"id":"wyr-132-2","text":"Super smell (you notice EVERY smell)"},{"id":"wyr-132-3","text":"Super hearing (every whisper is a shout)"},{"id":"wyr-132-4","text":"Growing ten feet tall with no warning"},{"id":"wyr-132-5","text":"Turning anything you touch to ice"}]'::jsonb,
     null),
    ('easy',
     'Which sidekick power would you want if your best friend got the cool power instead?',
     '[{"id":"wyr-133-0","text":"Super speed on a bike only"},{"id":"wyr-133-1","text":"The ability to always find parking"},{"id":"wyr-133-2","text":"Perfect aim with a nerf gun"},{"id":"wyr-133-3","text":"Never losing at rock-paper-scissors"},{"id":"wyr-133-4","text":"Instantly knowing any word's spelling"},{"id":"wyr-133-5","text":"Always picking the fastest checkout line"}]'::jsonb,
     null),
    ('hard',
     'Which cursed superpower would you be stuck with forever?',
     '[{"id":"wyr-134-0","text":"Turning invisible whenever you sneeze"},{"id":"wyr-134-1","text":"Flying but only backwards"},{"id":"wyr-134-2","text":"Super strength that only works on Tuesdays"},{"id":"wyr-134-3","text":"Reading minds but only of pets"},{"id":"wyr-134-4","text":"Teleporting but always five feet off target"},{"id":"wyr-134-5","text":"Super speed that only works when no one's watching"}]'::jsonb,
     null),
    ('medium',
     'Which power would you want for exactly one hour a day?',
     '[{"id":"wyr-135-0","text":"Flight"},{"id":"wyr-135-1","text":"Invisibility"},{"id":"wyr-135-2","text":"Time freeze"},{"id":"wyr-135-3","text":"X-ray vision"},{"id":"wyr-135-4","text":"Shape-shifting"},{"id":"wyr-135-5","text":"Super speed"}]'::jsonb,
     null),
    ('easy',
     'Which magical item would you want hidden in your backpack?',
     '[{"id":"wyr-136-0","text":"A bag that's never empty of snacks"},{"id":"wyr-136-1","text":"A compass that always points home"},{"id":"wyr-136-2","text":"A cloak of invisibility"},{"id":"wyr-136-3","text":"A map that shows secret shortcuts"},{"id":"wyr-136-4","text":"A pen that never runs out of ink"},{"id":"wyr-136-5","text":"Boots that never get tired"}]'::jsonb,
     null),
    ('medium',
     'Which power-swap would make the funniest superhero team?',
     '[{"id":"wyr-137-0","text":"A hero who can fly but is terrified of heights"},{"id":"wyr-137-1","text":"A hero with super strength who's incredibly clumsy"},{"id":"wyr-137-2","text":"A hero who's invisible but really loud"},{"id":"wyr-137-3","text":"A mind-reader who's terrible at keeping secrets"},{"id":"wyr-137-4","text":"A super-fast hero who always gets lost"},{"id":"wyr-137-5","text":"A shapeshifter who can only turn into farm animals"}]'::jsonb,
     null),
    ('medium',
     'Which supervillain weakness would be the funniest to have?',
     '[{"id":"wyr-138-0","text":"Melts in direct sunlight like ice cream"},{"id":"wyr-138-1","text":"Loses all power after a big sneeze"},{"id":"wyr-138-2","text":"Can't stop dancing when music plays"},{"id":"wyr-138-3","text":"Turns nice whenever someone says \"please\""},{"id":"wyr-138-4","text":"Falls asleep exactly at 8pm no matter what"},{"id":"wyr-138-5","text":"Becomes see-through when embarrassed"}]'::jsonb,
     null),
    ('medium',
     'Which power would you want to secretly have and never tell anyone about?',
     '[{"id":"wyr-139-0","text":"Talking to animals"},{"id":"wyr-139-1","text":"Perfect luck at games"},{"id":"wyr-139-2","text":"Always knowing the right answer in class"},{"id":"wyr-139-3","text":"Never getting sick"},{"id":"wyr-139-4","text":"Super short naps that fully recharge you"},{"id":"wyr-139-5","text":"Always knowing when it will rain"}]'::jsonb,
     null),
    ('easy',
     'Which magical pet upgrade would you want most?',
     '[{"id":"wyr-140-0","text":"A dog that can talk"},{"id":"wyr-140-1","text":"A cat that grants wishes"},{"id":"wyr-140-2","text":"A hamster the size of a horse"},{"id":"wyr-140-3","text":"A goldfish that can breathe air"},{"id":"wyr-140-4","text":"A bird that delivers your messages instantly"},{"id":"wyr-140-5","text":"A turtle that's actually super fast"}]'::jsonb,
     null),
    ('hard',
     'Which mind-bending power would freak you out the most to actually have?',
     '[{"id":"wyr-141-0","text":"Seeing five minutes into the future"},{"id":"wyr-141-1","text":"Feeling everyone's emotions around you"},{"id":"wyr-141-2","text":"Remembering every single day of your life perfectly"},{"id":"wyr-141-3","text":"Knowing exactly how everything will end before it happens"},{"id":"wyr-141-4","text":"Hearing every conversation happening in the building"},{"id":"wyr-141-5","text":"Always knowing when someone is lying"}]'::jsonb,
     null),
    ('medium',
     'Which power would be the most useful for surviving school?',
     '[{"id":"wyr-142-0","text":"Photographic memory"},{"id":"wyr-142-1","text":"Speed-reading any book instantly"},{"id":"wyr-142-2","text":"Never needing to sleep"},{"id":"wyr-142-3","text":"Understanding any subject on the first try"},{"id":"wyr-142-4","text":"Being invisible during pop quizzes"},{"id":"wyr-142-5","text":"Perfect handwriting every time"}]'::jsonb,
     null),
    ('easy',
     'Which food would you eat for every meal for a whole month if you had to pick one?',
     '[{"id":"wyr-143-0","text":"Pizza"},{"id":"wyr-143-1","text":"Tacos"},{"id":"wyr-143-2","text":"Mac and cheese"},{"id":"wyr-143-3","text":"Pancakes"},{"id":"wyr-143-4","text":"Sushi"},{"id":"wyr-143-5","text":"Burgers"}]'::jsonb,
     null),
    ('medium',
     'Which weird food combo would you actually try if a friend dared you?',
     '[{"id":"wyr-144-0","text":"Pickles dipped in chocolate"},{"id":"wyr-144-1","text":"Ketchup on ice cream"},{"id":"wyr-144-2","text":"Peanut butter on pizza"},{"id":"wyr-144-3","text":"Popcorn in your cereal"},{"id":"wyr-144-4","text":"French fries dipped in a milkshake"},{"id":"wyr-144-5","text":"Hot sauce on watermelon"}]'::jsonb,
     null),
    ('easy',
     'Which dessert would you never want to run out of?',
     '[{"id":"wyr-145-0","text":"Chocolate chip cookies"},{"id":"wyr-145-1","text":"Ice cream"},{"id":"wyr-145-2","text":"Brownies"},{"id":"wyr-145-3","text":"Cupcakes"},{"id":"wyr-145-4","text":"Donuts"},{"id":"wyr-145-5","text":"Cheesecake"}]'::jsonb,
     null),
    ('medium',
     'Which food rule would be the hardest to follow for a whole year?',
     '[{"id":"wyr-146-0","text":"No dessert ever, not even on birthdays"},{"id":"wyr-146-1","text":"Only eating foods that are one color"},{"id":"wyr-146-2","text":"Eating with chopsticks for every meal"},{"id":"wyr-146-3","text":"No snacks between meals ever"},{"id":"wyr-146-4","text":"Only drinking water, nothing else"},{"id":"wyr-146-5","text":"Cooking every single meal yourself"}]'::jsonb,
     null),
    ('medium',
     'Which mystery meal at a food truck festival would you actually order?',
     '[{"id":"wyr-147-0","text":"\"Chef's Surprise\" with no description"},{"id":"wyr-147-1","text":"A dish named after a dare"},{"id":"wyr-147-2","text":"The spiciest thing on the menu"},{"id":"wyr-147-3","text":"A fusion dish that sounds made up"},{"id":"wyr-147-4","text":"Whatever the longest line is for"},{"id":"wyr-147-5","text":"A dish served in a way you've never seen"}]'::jsonb,
     null),
    ('easy',
     'Which breakfast food would you want an unlimited supply of forever?',
     '[{"id":"wyr-148-0","text":"Pancakes"},{"id":"wyr-148-1","text":"Waffles"},{"id":"wyr-148-2","text":"Cereal"},{"id":"wyr-148-3","text":"Bacon"},{"id":"wyr-148-4","text":"Donuts"},{"id":"wyr-148-5","text":"Cinnamon rolls"}]'::jsonb,
     null),
    ('medium',
     'Which cooking disaster would be the most disappointing to walk into?',
     '[{"id":"wyr-149-0","text":"A cake that collapsed in the oven"},{"id":"wyr-149-1","text":"Soup that's way too salty"},{"id":"wyr-149-2","text":"Burnt cookies on movie night"},{"id":"wyr-149-3","text":"A pizza that got stuck to the pan"},{"id":"wyr-149-4","text":"Popcorn that's mostly unpopped kernels"},{"id":"wyr-149-5","text":"A smoothie that separated into weird layers"}]'::jsonb,
     null),
    ('easy',
     'Which classic snack would you want in an endless bowl at every party?',
     '[{"id":"wyr-150-0","text":"Popcorn"},{"id":"wyr-150-1","text":"Chips and salsa"},{"id":"wyr-150-2","text":"Trail mix"},{"id":"wyr-150-3","text":"Pretzels"},{"id":"wyr-150-4","text":"Fruit snacks"},{"id":"wyr-150-5","text":"Cheese and crackers"}]'::jsonb,
     null),
    ('medium',
     'Which unusual food from around the world would you actually be brave enough to try?',
     '[{"id":"wyr-151-0","text":"Century eggs"},{"id":"wyr-151-1","text":"Durian fruit"},{"id":"wyr-151-2","text":"Escargot (cooked snails)"},{"id":"wyr-151-3","text":"Fried crickets"},{"id":"wyr-151-4","text":"Stinky tofu"},{"id":"wyr-151-5","text":"Balut"}]'::jsonb,
     null),
    ('medium',
     'Which restaurant rule would you want enforced everywhere?',
     '[{"id":"wyr-152-0","text":"Free refills on everything"},{"id":"wyr-152-1","text":"Kids eat free every day"},{"id":"wyr-152-2","text":"Dessert comes before dinner"},{"id":"wyr-152-3","text":"You can always ask for extra sauce"},{"id":"wyr-152-4","text":"No waiting in line ever"},{"id":"wyr-152-5","text":"Every meal comes with a surprise side"}]'::jsonb,
     null),
    ('easy',
     'Which pizza topping combo would you actually order?',
     '[{"id":"wyr-153-0","text":"Pineapple and jalapeno"},{"id":"wyr-153-1","text":"Extra cheese and bacon"},{"id":"wyr-153-2","text":"BBQ chicken"},{"id":"wyr-153-3","text":"Mushroom and olive"},{"id":"wyr-153-4","text":"Buffalo chicken"},{"id":"wyr-153-5","text":"Just plain cheese, no debate"}]'::jsonb,
     null),
    ('medium',
     'Which candy would you want to be the official flavor of your birthday every year?',
     '[{"id":"wyr-154-0","text":"Chocolate"},{"id":"wyr-154-1","text":"Sour gummy worms"},{"id":"wyr-154-2","text":"Cotton candy"},{"id":"wyr-154-3","text":"Bubblegum"},{"id":"wyr-154-4","text":"Caramel"},{"id":"wyr-154-5","text":"Peppermint"}]'::jsonb,
     null),
    ('medium',
     'Which food-based punishment would be the worst if you lost a family game night?',
     '[{"id":"wyr-155-0","text":"Eating a spoonful of hot sauce"},{"id":"wyr-155-1","text":"No dessert for a week"},{"id":"wyr-155-2","text":"Eating a food you dislike"},{"id":"wyr-155-3","text":"Doing dishes for a month"},{"id":"wyr-155-4","text":"Drinking a weird smoothie combo"},{"id":"wyr-155-5","text":"Cooking dinner for everyone else all week"}]'::jsonb,
     null),
    ('easy',
     'Which animal would you want as a giant-sized pet?',
     '[{"id":"wyr-156-0","text":"A golden retriever"},{"id":"wyr-156-1","text":"A bunny"},{"id":"wyr-156-2","text":"A turtle"},{"id":"wyr-156-3","text":"A parrot"},{"id":"wyr-156-4","text":"A hedgehog"},{"id":"wyr-156-5","text":"A cat"}]'::jsonb,
     null),
    ('medium',
     'Which tiny-sized animal would you want to carry around in your pocket?',
     '[{"id":"wyr-157-0","text":"An elephant"},{"id":"wyr-157-1","text":"A giraffe"},{"id":"wyr-157-2","text":"A horse"},{"id":"wyr-157-3","text":"A lion"},{"id":"wyr-157-4","text":"A dolphin"},{"id":"wyr-157-5","text":"A kangaroo"}]'::jsonb,
     null),
    ('easy',
     'Which farm animal sound would you actually want as your phone''s ringtone?',
     '[{"id":"wyr-158-0","text":"A rooster crowing"},{"id":"wyr-158-1","text":"A goat bleating"},{"id":"wyr-158-2","text":"A cow mooing"},{"id":"wyr-158-3","text":"A duck quacking"},{"id":"wyr-158-4","text":"A pig oinking"},{"id":"wyr-158-5","text":"A donkey braying"}]'::jsonb,
     null),
    ('hard',
     'Which extinct animal would you actually want to see brought back to life (safely, from a distance)?',
     '[{"id":"wyr-159-0","text":"A woolly mammoth"},{"id":"wyr-159-1","text":"A saber-toothed cat"},{"id":"wyr-159-2","text":"A dodo bird"},{"id":"wyr-159-3","text":"A giant ground sloth"},{"id":"wyr-159-4","text":"A pterosaur flying overhead"},{"id":"wyr-159-5","text":"A triceratops"}]'::jsonb,
     null),
    ('medium',
     'Which animal ability would you want to borrow for a day?',
     '[{"id":"wyr-160-0","text":"A chameleon's color-changing skin"},{"id":"wyr-160-1","text":"A cheetah's top speed"},{"id":"wyr-160-2","text":"An octopus's ability to squeeze anywhere"},{"id":"wyr-160-3","text":"A bird's ability to fly"},{"id":"wyr-160-4","text":"A bat's echolocation"},{"id":"wyr-160-5","text":"A gecko's wall-climbing feet"}]'::jsonb,
     null),
    ('easy',
     'Which zoo animal would you want to watch the longest?',
     '[{"id":"wyr-161-0","text":"The playful otters"},{"id":"wyr-161-1","text":"The lounging lions"},{"id":"wyr-161-2","text":"The swinging monkeys"},{"id":"wyr-161-3","text":"The waddling penguins"},{"id":"wyr-161-4","text":"The napping pandas"},{"id":"wyr-161-5","text":"The strutting peacocks"}]'::jsonb,
     null),
    ('medium',
     'Which underwater creature would be the coolest to swim alongside (safely)?',
     '[{"id":"wyr-162-0","text":"A dolphin"},{"id":"wyr-162-1","text":"A sea turtle"},{"id":"wyr-162-2","text":"A whale shark"},{"id":"wyr-162-3","text":"A manta ray"},{"id":"wyr-162-4","text":"A colorful school of fish"},{"id":"wyr-162-5","text":"A friendly seal"}]'::jsonb,
     null),
    ('medium',
     'Which animal would be the most chaotic to have as the family pet instead of a dog or cat?',
     '[{"id":"wyr-163-0","text":"A full-grown emu"},{"id":"wyr-163-1","text":"A raccoon"},{"id":"wyr-163-2","text":"A pot-bellied pig"},{"id":"wyr-163-3","text":"A capuchin monkey"},{"id":"wyr-163-4","text":"A peacock"},{"id":"wyr-163-5","text":"A llama"}]'::jsonb,
     null),
    ('easy',
     'Which bug would you least mind having crawl on your hand?',
     '[{"id":"wyr-164-0","text":"A ladybug"},{"id":"wyr-164-1","text":"A caterpillar"},{"id":"wyr-164-2","text":"A grasshopper"},{"id":"wyr-164-3","text":"A pill bug (roly-poly)"},{"id":"wyr-164-4","text":"A beetle"},{"id":"wyr-164-5","text":"A cricket"}]'::jsonb,
     null),
    ('medium',
     'Which bird would you want to have as your personal messenger?',
     '[{"id":"wyr-165-0","text":"An owl"},{"id":"wyr-165-1","text":"A parrot"},{"id":"wyr-165-2","text":"A falcon"},{"id":"wyr-165-3","text":"A pigeon"},{"id":"wyr-165-4","text":"A crow"},{"id":"wyr-165-5","text":"A hummingbird"}]'::jsonb,
     null),
    ('medium',
     'Which nighttime animal sound outside your tent would keep you awake the longest?',
     '[{"id":"wyr-166-0","text":"An owl hooting"},{"id":"wyr-166-1","text":"Crickets chirping nonstop"},{"id":"wyr-166-2","text":"A distant coyote howl"},{"id":"wyr-166-3","text":"Frogs croaking in a chorus"},{"id":"wyr-166-4","text":"Something rustling in the leaves"},{"id":"wyr-166-5","text":"A woodpecker at dawn"}]'::jsonb,
     null),
    ('medium',
     'Which time period would you actually want to visit for a day (round trip guaranteed)?',
     '[{"id":"wyr-167-0","text":"Ancient Egypt"},{"id":"wyr-167-1","text":"The Wild West"},{"id":"wyr-167-2","text":"Medieval times"},{"id":"wyr-167-3","text":"The 1920s"},{"id":"wyr-167-4","text":"The dinosaur age (from a safe distance)"},{"id":"wyr-167-5","text":"The future, 100 years from now"}]'::jsonb,
     null),
    ('hard',
     'Which historical event would you want to witness in person from a safe distance?',
     '[{"id":"wyr-168-0","text":"The first moon landing"},{"id":"wyr-168-1","text":"The building of the pyramids"},{"id":"wyr-168-2","text":"The signing of a great treaty"},{"id":"wyr-168-3","text":"The first flight at Kitty Hawk"},{"id":"wyr-168-4","text":"A knight's tournament"},{"id":"wyr-168-5","text":"The opening of a famous world's fair"}]'::jsonb,
     null),
    ('easy',
     'Which old-timey invention would you actually want to try using for a week?',
     '[{"id":"wyr-169-0","text":"A rotary phone"},{"id":"wyr-169-1","text":"A typewriter"},{"id":"wyr-169-2","text":"A record player"},{"id":"wyr-169-3","text":"A film camera with no instant preview"},{"id":"wyr-169-4","text":"A horse-drawn carriage"},{"id":"wyr-169-5","text":"A hand-crank ice cream maker"}]'::jsonb,
     null),
    ('medium',
     'Which future invention would you most want to see arrive in your lifetime?',
     '[{"id":"wyr-170-0","text":"A flying car for everyone"},{"id":"wyr-170-1","text":"Teleportation"},{"id":"wyr-170-2","text":"Robots that do all the chores"},{"id":"wyr-170-3","text":"A cure for every illness"},{"id":"wyr-170-4","text":"Weather control"},{"id":"wyr-170-5","text":"Instant language translation for any language"}]'::jsonb,
     null),
    ('hard',
     'Which decade''s fashion would you actually be willing to wear for a whole month?',
     '[{"id":"wyr-171-0","text":"1970s bell-bottoms"},{"id":"wyr-171-1","text":"1980s neon and big hair"},{"id":"wyr-171-2","text":"1990s baggy everything"},{"id":"wyr-171-3","text":"1920s flapper style"},{"id":"wyr-171-4","text":"Victorian-era formal wear"},{"id":"wyr-171-5","text":"Medieval tunics and capes"}]'::jsonb,
     null),
    ('medium',
     'Which ancient wonder would you most want to have seen when it was brand new?',
     '[{"id":"wyr-172-0","text":"The Great Pyramid of Giza"},{"id":"wyr-172-1","text":"The Hanging Gardens of Babylon"},{"id":"wyr-172-2","text":"The Colosseum on opening day"},{"id":"wyr-172-3","text":"The Great Wall of China under construction"},{"id":"wyr-172-4","text":"Stonehenge freshly built"},{"id":"wyr-172-5","text":"The Lighthouse of Alexandria lit for the first time"}]'::jsonb,
     null),
    ('easy',
     'Which futuristic school subject would you actually want to take?',
     '[{"id":"wyr-173-0","text":"Space travel 101"},{"id":"wyr-173-1","text":"Robot building"},{"id":"wyr-173-2","text":"Time travel history"},{"id":"wyr-173-3","text":"Underwater exploration"},{"id":"wyr-173-4","text":"Talking-to-animals class"},{"id":"wyr-173-5","text":"Zero-gravity gym class"}]'::jsonb,
     null),
    ('medium',
     'Which lost historical treasure would you want to be the one to finally find?',
     '[{"id":"wyr-174-0","text":"A pirate's buried gold"},{"id":"wyr-174-1","text":"A sunken ship's cargo"},{"id":"wyr-174-2","text":"A lost ancient city"},{"id":"wyr-174-3","text":"A hidden royal jewel"},{"id":"wyr-174-4","text":"An explorer's missing journal"},{"id":"wyr-174-5","text":"A forgotten dinosaur fossil bed"}]'::jsonb,
     null),
    ('medium',
     'Which planet would you actually want to visit if it were completely safe?',
     '[{"id":"wyr-175-0","text":"Mars"},{"id":"wyr-175-1","text":"Saturn (just to see the rings up close)"},{"id":"wyr-175-2","text":"Jupiter's moon Europa"},{"id":"wyr-175-3","text":"Venus (from a hovering ship)"},{"id":"wyr-175-4","text":"Neptune"},{"id":"wyr-175-5","text":"A planet no one's discovered yet"}]'::jsonb,
     null),
    ('easy',
     'Which space snack would you want on a rocket ship?',
     '[{"id":"wyr-176-0","text":"Freeze-dried ice cream"},{"id":"wyr-176-1","text":"A tube of applesauce"},{"id":"wyr-176-2","text":"Astronaut-style dehydrated fruit"},{"id":"wyr-176-3","text":"Space-grade beef jerky"},{"id":"wyr-176-4","text":"Powdered hot chocolate"},{"id":"wyr-176-5","text":"Crunchy granola bars that don't crumble"}]'::jsonb,
     null),
    ('hard',
     'Which alien first-contact scenario would go the smoothest?',
     '[{"id":"wyr-177-0","text":"Friendly aliens who just want to trade recipes"},{"id":"wyr-177-1","text":"Aliens who communicate only through music"},{"id":"wyr-177-2","text":"Aliens who are tiny and adorable"},{"id":"wyr-177-3","text":"Aliens who are basically giant talking plants"},{"id":"wyr-177-4","text":"Aliens who just want directions somewhere"},{"id":"wyr-177-5","text":"Aliens who think humans are the weird ones"}]'::jsonb,
     null),
    ('medium',
     'Which sci-fi mode of transportation would you want to use for your commute?',
     '[{"id":"wyr-178-0","text":"A jetpack"},{"id":"wyr-178-1","text":"A hoverboard"},{"id":"wyr-178-2","text":"A teleportation pad"},{"id":"wyr-178-3","text":"A flying car"},{"id":"wyr-178-4","text":"A personal spaceship"},{"id":"wyr-178-5","text":"A high-speed pod tube"}]'::jsonb,
     null),
    ('easy',
     'Which space sight would you want to see with your own eyes?',
     '[{"id":"wyr-179-0","text":"A meteor shower up close"},{"id":"wyr-179-1","text":"Earth from orbit"},{"id":"wyr-179-2","text":"The rings of Saturn"},{"id":"wyr-179-3","text":"A shooting comet"},{"id":"wyr-179-4","text":"The Northern Lights from space"},{"id":"wyr-179-5","text":"A galaxy through a giant telescope"}]'::jsonb,
     null),
    ('medium',
     'Which space station chore would be the worst to get stuck with?',
     '[{"id":"wyr-180-0","text":"Fixing a leaky air filter"},{"id":"wyr-180-1","text":"Cleaning the zero-gravity bathroom"},{"id":"wyr-180-2","text":"Untangling floating cables"},{"id":"wyr-180-3","text":"Recalibrating the navigation system"},{"id":"wyr-180-4","text":"Chasing down a loose tool that's floating away"},{"id":"wyr-180-5","text":"Repairing a solar panel on a spacewalk"}]'::jsonb,
     null),
    ('medium',
     'Which robot companion feature would you want most?',
     '[{"id":"wyr-181-0","text":"Perfect memory to never forget your homework"},{"id":"wyr-181-1","text":"The ability to cook any meal instantly"},{"id":"wyr-181-2","text":"A built-in translator for any language"},{"id":"wyr-181-3","text":"Super strength to carry your backpack"},{"id":"wyr-181-4","text":"A built-in flashlight and GPS"},{"id":"wyr-181-5","text":"Endless patience to help you practice anything"}]'::jsonb,
     null),
    ('medium',
     'Which magical creature companion would you want by your side?',
     '[{"id":"wyr-182-0","text":"A baby dragon"},{"id":"wyr-182-1","text":"A phoenix"},{"id":"wyr-182-2","text":"A unicorn"},{"id":"wyr-182-3","text":"A griffin"},{"id":"wyr-182-4","text":"A talking fox"},{"id":"wyr-182-5","text":"A tiny friendly gargoyle"}]'::jsonb,
     null),
    ('hard',
     'Which fantasy kingdom would you actually want to rule for a day?',
     '[{"id":"wyr-183-0","text":"An underwater kingdom"},{"id":"wyr-183-1","text":"A cloud kingdom in the sky"},{"id":"wyr-183-2","text":"An enchanted forest realm"},{"id":"wyr-183-3","text":"A kingdom made entirely of candy"},{"id":"wyr-183-4","text":"A kingdom of talking animals"},{"id":"wyr-183-5","text":"A snow and ice kingdom"}]'::jsonb,
     null),
    ('easy',
     'Which fairy tale role would you want to play for a day?',
     '[{"id":"wyr-184-0","text":"The brave knight"},{"id":"wyr-184-1","text":"The clever wizard"},{"id":"wyr-184-2","text":"The adventurous explorer"},{"id":"wyr-184-3","text":"The wise dragon"},{"id":"wyr-184-4","text":"The clever fox"},{"id":"wyr-184-5","text":"The kind-hearted giant"}]'::jsonb,
     null),
    ('medium',
     'Which magical school subject would you want to ace?',
     '[{"id":"wyr-185-0","text":"Potion making"},{"id":"wyr-185-1","text":"Flying lessons"},{"id":"wyr-185-2","text":"Spell casting"},{"id":"wyr-185-3","text":"Talking to magical creatures"},{"id":"wyr-185-4","text":"Enchanted map reading"},{"id":"wyr-185-5","text":"Dragon care"}]'::jsonb,
     null),
    ('hard',
     'Which mythical quest would you actually sign up for?',
     '[{"id":"wyr-186-0","text":"Finding a hidden treasure guarded by a dragon"},{"id":"wyr-186-1","text":"Rescuing a friend from an enchanted tower"},{"id":"wyr-186-2","text":"Solving an ancient riddle to unlock a portal"},{"id":"wyr-186-3","text":"Retrieving a magical item from the top of a mountain"},{"id":"wyr-186-4","text":"Befriending a legendary sea monster"},{"id":"wyr-186-5","text":"Breaking a curse on an entire village"}]'::jsonb,
     null),
    ('medium',
     'Which magical weather event would be the coolest to witness?',
     '[{"id":"wyr-187-0","text":"Raining glitter instead of water"},{"id":"wyr-187-1","text":"A rainbow that you could actually walk on"},{"id":"wyr-187-2","text":"Snow that never melts but isn't cold"},{"id":"wyr-187-3","text":"Clouds shaped like animals that actually move"},{"id":"wyr-187-4","text":"A sunset with every color at once"},{"id":"wyr-187-5","text":"Lightning that's completely silent and harmless"}]'::jsonb,
     null),
    ('easy',
     'Which enchanted object would you want hidden in your room?',
     '[{"id":"wyr-188-0","text":"A mirror that shows the future"},{"id":"wyr-188-1","text":"A book that reads itself aloud"},{"id":"wyr-188-2","text":"A lamp with a genie inside"},{"id":"wyr-188-3","text":"A chest that's never empty"},{"id":"wyr-188-4","text":"A key that opens any door"},{"id":"wyr-188-5","text":"A snow globe you could shrink into"}]'::jsonb,
     null),
    ('medium',
     'Which unusual job would you actually want to try for a week?',
     '[{"id":"wyr-189-0","text":"Video game tester"},{"id":"wyr-189-1","text":"Roller coaster designer"},{"id":"wyr-189-2","text":"Zoo keeper"},{"id":"wyr-189-3","text":"Chocolate taste tester"},{"id":"wyr-189-4","text":"Movie stunt double"},{"id":"wyr-189-5","text":"Theme park mascot"}]'::jsonb,
     null),
    ('medium',
     'Which everyday job would be secretly the hardest to actually do well?',
     '[{"id":"wyr-190-0","text":"Air traffic controller"},{"id":"wyr-190-1","text":"Restaurant chef during rush hour"},{"id":"wyr-190-2","text":"Teacher for a room of kindergartners"},{"id":"wyr-190-3","text":"Airline pilot"},{"id":"wyr-190-4","text":"Surgeon"},{"id":"wyr-190-5","text":"Firefighter"}]'::jsonb,
     null),
    ('easy',
     'Which family role would you want to swap with for a day?',
     '[{"id":"wyr-191-0","text":"Being the parent for a day"},{"id":"wyr-191-1","text":"Being the oldest sibling"},{"id":"wyr-191-2","text":"Being the youngest sibling"},{"id":"wyr-191-3","text":"Being an only child for a day"},{"id":"wyr-191-4","text":"Being the family pet"},{"id":"wyr-191-5","text":"Being in charge of dinner every night"}]'::jsonb,
     null),
    ('medium',
     'Which celebrity job would you actually want, even with all the attention that comes with it?',
     '[{"id":"wyr-192-0","text":"A famous movie actor"},{"id":"wyr-192-1","text":"A chart-topping musician"},{"id":"wyr-192-2","text":"A pro athlete"},{"id":"wyr-192-3","text":"A famous author"},{"id":"wyr-192-4","text":"A viral internet creator"},{"id":"wyr-192-5","text":"An Olympic gold medalist"}]'::jsonb,
     null),
    ('medium',
     'Which job would you dread the most if you had to do it for a whole summer?',
     '[{"id":"wyr-193-0","text":"Cleaning up after a parade"},{"id":"wyr-193-1","text":"Washing dishes at a huge restaurant"},{"id":"wyr-193-2","text":"Answering a complaint hotline"},{"id":"wyr-193-3","text":"Testing amusement park lines all day"},{"id":"wyr-193-4","text":"Picking up litter at a stadium"},{"id":"wyr-193-5","text":"Untangling cords at an electronics store"}]'::jsonb,
     null),
    ('medium',
     'Which behind-the-scenes movie job sounds the most fun?',
     '[{"id":"wyr-194-0","text":"Special effects designer"},{"id":"wyr-194-1","text":"Costume designer"},{"id":"wyr-194-2","text":"Stunt coordinator"},{"id":"wyr-194-3","text":"Set builder"},{"id":"wyr-194-4","text":"Sound effects creator"},{"id":"wyr-194-5","text":"Animal wrangler on set"}]'::jsonb,
     null),
    ('easy',
     'Which weather event would you want to experience from somewhere totally safe and cozy?',
     '[{"id":"wyr-195-0","text":"A thunderstorm"},{"id":"wyr-195-1","text":"A heavy snowfall"},{"id":"wyr-195-2","text":"A windstorm rattling the windows"},{"id":"wyr-195-3","text":"A foggy morning"},{"id":"wyr-195-4","text":"A hailstorm"},{"id":"wyr-195-5","text":"A rainbow right after rain"}]'::jsonb,
     null),
    ('medium',
     'Which season would you want to last for six whole months?',
     '[{"id":"wyr-196-0","text":"Summer"},{"id":"wyr-196-1","text":"Fall"},{"id":"wyr-196-2","text":"Winter"},{"id":"wyr-196-3","text":"Spring"},{"id":"wyr-196-4","text":"A perfect 70-degree season all its own"},{"id":"wyr-196-5","text":"A season that's always sunset"}]'::jsonb,
     null),
    ('hard',
     'Which extreme weather would you least want to get caught in, even briefly?',
     '[{"id":"wyr-197-0","text":"A tornado warning"},{"id":"wyr-197-1","text":"A blizzard"},{"id":"wyr-197-2","text":"A heat wave with no AC"},{"id":"wyr-197-3","text":"A flash flood"},{"id":"wyr-197-4","text":"A hailstorm the size of golf balls"},{"id":"wyr-197-5","text":"Gale-force winds"}]'::jsonb,
     null),
    ('easy',
     'Which snowy activity would you want to do all winter long?',
     '[{"id":"wyr-198-0","text":"Sledding"},{"id":"wyr-198-1","text":"Building a snowman"},{"id":"wyr-198-2","text":"A snowball fight"},{"id":"wyr-198-3","text":"Ice skating"},{"id":"wyr-198-4","text":"Making snow angels"},{"id":"wyr-198-5","text":"Hot cocoa by the fire after playing outside"}]'::jsonb,
     null),
    ('easy',
     'Which school day surprise would make your whole week?',
     '[{"id":"wyr-199-0","text":"An unannounced snow day"},{"id":"wyr-199-1","text":"A surprise pizza party"},{"id":"wyr-199-2","text":"A field trip announcement"},{"id":"wyr-199-3","text":"A substitute who lets you watch a movie"},{"id":"wyr-199-4","text":"An extra recess"},{"id":"wyr-199-5","text":"A pop quiz that turns out to be super easy"}]'::jsonb,
     null),
    ('medium',
     'Which sibling swap for a week would be the most chaotic?',
     '[{"id":"wyr-200-0","text":"Trading rooms"},{"id":"wyr-200-1","text":"Trading chores"},{"id":"wyr-200-2","text":"Trading friend groups"},{"id":"wyr-200-3","text":"Trading bedtimes"},{"id":"wyr-200-4","text":"Trading allowances"},{"id":"wyr-200-5","text":"Trading who gets to pick dinner"}]'::jsonb,
     null),
    ('hard',
     'Which classroom rule would be the hardest for you to follow for a whole month?',
     '[{"id":"wyr-201-0","text":"No talking during silent reading"},{"id":"wyr-201-1","text":"Raise your hand for everything, even to sharpen a pencil"},{"id":"wyr-201-2","text":"No snacks at your desk"},{"id":"wyr-201-3","text":"Assigned seats you can't change"},{"id":"wyr-201-4","text":"No phones anywhere near your backpack"},{"id":"wyr-201-5","text":"Walking in a perfectly silent line"}]'::jsonb,
     null),
    ('easy',
     'Which best friend superpower combo would make your friendship unstoppable?',
     '[{"id":"wyr-202-0","text":"You fly, they teleport"},{"id":"wyr-202-1","text":"You read minds, they're invisible"},{"id":"wyr-202-2","text":"You're super strong, they're super fast"},{"id":"wyr-202-3","text":"You control weather, they talk to animals"},{"id":"wyr-202-4","text":"You freeze time, they can un-freeze it too"},{"id":"wyr-202-5","text":"You shape-shift, they can copy your shape"}]'::jsonb,
     null),
    ('medium',
     'Which recess game would you want to be the undisputed champion of?',
     '[{"id":"wyr-203-0","text":"Four square"},{"id":"wyr-203-1","text":"Tag"},{"id":"wyr-203-2","text":"Basketball"},{"id":"wyr-203-3","text":"Jump rope"},{"id":"wyr-203-4","text":"Kickball"},{"id":"wyr-203-5","text":"Hopscotch"}]'::jsonb,
     null),
    ('medium',
     'Which surprise windfall would you be most excited about?',
     '[{"id":"wyr-204-0","text":"Finding $100 in an old coat pocket"},{"id":"wyr-204-1","text":"Winning a year of free ice cream"},{"id":"wyr-204-2","text":"Getting a free trip anywhere in the world"},{"id":"wyr-204-3","text":"Winning a shopping spree at your favorite store"},{"id":"wyr-204-4","text":"Getting a whole arcade to yourself for a day"},{"id":"wyr-204-5","text":"Winning free tickets to any concert"}]'::jsonb,
     null),
    ('medium',
     'Which type of fame would actually be the most fun to have?',
     '[{"id":"wyr-205-0","text":"Famous for a talent show performance"},{"id":"wyr-205-1","text":"Famous for a viral funny video"},{"id":"wyr-205-2","text":"Famous for winning a huge competition"},{"id":"wyr-205-3","text":"Famous as a kid inventor"},{"id":"wyr-205-4","text":"Famous for a record-breaking feat"},{"id":"wyr-205-5","text":"Famous as the world's best at a weird hobby"}]'::jsonb,
     null),
    ('easy',
     'Which prize would you pick if you won a mystery contest?',
     '[{"id":"wyr-206-0","text":"A lifetime supply of your favorite snack"},{"id":"wyr-206-1","text":"A brand-new bike"},{"id":"wyr-206-2","text":"A trip to a theme park"},{"id":"wyr-206-3","text":"A shopping spree"},{"id":"wyr-206-4","text":"A pet of your choice"},{"id":"wyr-206-5","text":"A custom-built treehouse"}]'::jsonb,
     null),
    ('medium',
     'Which "unlimited" perk would you want more than the others?',
     '[{"id":"wyr-207-0","text":"Unlimited video game credits"},{"id":"wyr-207-1","text":"Unlimited movie theater popcorn"},{"id":"wyr-207-2","text":"Unlimited theme park fast passes"},{"id":"wyr-207-3","text":"Unlimited books from any bookstore"},{"id":"wyr-207-4","text":"Unlimited art supplies"},{"id":"wyr-207-5","text":"Unlimited ice cream flavors to try"}]'::jsonb,
     null),
    ('easy',
     'Which backyard game would you want to be unbeatable at?',
     '[{"id":"wyr-208-0","text":"Cornhole"},{"id":"wyr-208-1","text":"Horseshoes"},{"id":"wyr-208-2","text":"Wiffle ball"},{"id":"wyr-208-3","text":"Frisbee"},{"id":"wyr-208-4","text":"Badminton"},{"id":"wyr-208-5","text":"Water balloon toss"}]'::jsonb,
     null),
    ('medium',
     'Which Olympic sport would you actually want to try competing in?',
     '[{"id":"wyr-209-0","text":"Gymnastics"},{"id":"wyr-209-1","text":"Swimming"},{"id":"wyr-209-2","text":"Track and field sprinting"},{"id":"wyr-209-3","text":"Diving"},{"id":"wyr-209-4","text":"Skateboarding"},{"id":"wyr-209-5","text":"Archery"}]'::jsonb,
     null),
    ('hard',
     'Which extreme sport would you try just once if you were guaranteed to be safe?',
     '[{"id":"wyr-210-0","text":"Skydiving"},{"id":"wyr-210-1","text":"Bungee jumping"},{"id":"wyr-210-2","text":"White-water rafting"},{"id":"wyr-210-3","text":"Rock climbing a tall cliff"},{"id":"wyr-210-4","text":"Zip-lining across a canyon"},{"id":"wyr-210-5","text":"Cliff diving into clear water"}]'::jsonb,
     null),
    ('easy',
     'Which board game power-up would make family game night more fun?',
     '[{"id":"wyr-211-0","text":"An extra turn card"},{"id":"wyr-211-1","text":"A \"skip this challenge\" pass"},{"id":"wyr-211-2","text":"A \"steal a point\" move"},{"id":"wyr-211-3","text":"A guaranteed correct answer once per game"},{"id":"wyr-211-4","text":"Double points on your best category"},{"id":"wyr-211-5","text":"A \"redo\" for one bad roll"}]'::jsonb,
     null),
    ('medium',
     'Which team sport position would you want to master?',
     '[{"id":"wyr-212-0","text":"Star goalie"},{"id":"wyr-212-1","text":"Star pitcher"},{"id":"wyr-212-2","text":"Star quarterback"},{"id":"wyr-212-3","text":"Star point guard"},{"id":"wyr-212-4","text":"Star forward"},{"id":"wyr-212-5","text":"Team captain who calls the plays"}]'::jsonb,
     null),
    ('medium',
     'Which gadget would you want if you could only pick one for a deserted island (with power somehow provided)?',
     '[{"id":"wyr-213-0","text":"A tablet loaded with every movie"},{"id":"wyr-213-1","text":"A satellite phone"},{"id":"wyr-213-2","text":"A solar-powered speaker"},{"id":"wyr-213-3","text":"A drone for exploring"},{"id":"wyr-213-4","text":"A universal translator"},{"id":"wyr-213-5","text":"A device that purifies any water instantly"}]'::jsonb,
     null),
    ('easy',
     'Which app feature would you want invented next?',
     '[{"id":"wyr-214-0","text":"An app that finds your lost stuff instantly"},{"id":"wyr-214-1","text":"An app that translates pet sounds"},{"id":"wyr-214-2","text":"An app that predicts the weather perfectly"},{"id":"wyr-214-3","text":"An app that never lets your phone die"},{"id":"wyr-214-4","text":"An app that summarizes any homework instantly"},{"id":"wyr-214-5","text":"An app that finds the shortest line anywhere"}]'::jsonb,
     null),
    ('medium',
     'Which futuristic home upgrade would you want most?',
     '[{"id":"wyr-215-0","text":"A room that changes theme with a voice command"},{"id":"wyr-215-1","text":"A robot that does all your chores"},{"id":"wyr-215-2","text":"A fridge that never runs out of your favorites"},{"id":"wyr-215-3","text":"A shower that's always the perfect temperature"},{"id":"wyr-215-4","text":"A bed that makes itself"},{"id":"wyr-215-5","text":"Walls that turn into any video game world"}]'::jsonb,
     null),
    ('medium',
     'Which video game power-up would you want to actually have in real life?',
     '[{"id":"wyr-216-0","text":"An extra life"},{"id":"wyr-216-1","text":"A speed boost"},{"id":"wyr-216-2","text":"A shield that blocks one bad thing a day"},{"id":"wyr-216-3","text":"A coin magnet for finding money"},{"id":"wyr-216-4","text":"A double-jump"},{"id":"wyr-216-5","text":"An invincibility star for ten seconds"}]'::jsonb,
     null),
    ('easy',
     'Which instrument would you want to instantly know how to play perfectly?',
     '[{"id":"wyr-217-0","text":"Guitar"},{"id":"wyr-217-1","text":"Piano"},{"id":"wyr-217-2","text":"Drums"},{"id":"wyr-217-3","text":"Violin"},{"id":"wyr-217-4","text":"Trumpet"},{"id":"wyr-217-5","text":"Ukulele"}]'::jsonb,
     null),
    ('medium',
     'Which movie genre marathon would you want to binge for a rainy weekend?',
     '[{"id":"wyr-218-0","text":"Adventure movies"},{"id":"wyr-218-1","text":"Animated movies"},{"id":"wyr-218-2","text":"Mystery movies"},{"id":"wyr-218-3","text":"Comedy movies"},{"id":"wyr-218-4","text":"Superhero movies"},{"id":"wyr-218-5","text":"Fantasy movies"}]'::jsonb,
     null),
    ('medium',
     'Which behind-the-curtain talent show act would you actually want to perform?',
     '[{"id":"wyr-219-0","text":"A magic trick that goes perfectly"},{"id":"wyr-219-1","text":"A stand-up comedy bit"},{"id":"wyr-219-2","text":"A dance routine"},{"id":"wyr-219-3","text":"A song you wrote yourself"},{"id":"wyr-219-4","text":"A juggling act"},{"id":"wyr-219-5","text":"A dramatic monologue"}]'::jsonb,
     null),
    ('easy',
     'Which theme park ride category would you want unlimited fast passes for?',
     '[{"id":"wyr-220-0","text":"Roller coasters"},{"id":"wyr-220-1","text":"Water rides"},{"id":"wyr-220-2","text":"Dark rides with a story"},{"id":"wyr-220-3","text":"Spinning rides"},{"id":"wyr-220-4","text":"Drop towers"},{"id":"wyr-220-5","text":"Slow scenic rides"}]'::jsonb,
     null),
    ('hard',
     'Which sense would be hardest to lose for a whole day?',
     '[{"id":"wyr-221-0","text":"Taste"},{"id":"wyr-221-1","text":"Smell"},{"id":"wyr-221-2","text":"Hearing"},{"id":"wyr-221-3","text":"Sight"},{"id":"wyr-221-4","text":"Touch"},{"id":"wyr-221-5","text":"Balance"}]'::jsonb,
     null),
    ('medium',
     'Which body upgrade would you want if it were totally safe?',
     '[{"id":"wyr-222-0","text":"Night vision"},{"id":"wyr-222-1","text":"Never getting tired"},{"id":"wyr-222-2","text":"Perfect balance"},{"id":"wyr-222-3","text":"Super fast healing from scrapes"},{"id":"wyr-222-4","text":"Never getting motion sick"},{"id":"wyr-222-5","text":"A memory that never forgets a face"}]'::jsonb,
     null),
    ('easy',
     'Which silly temporary body swap would be the most fun for a day?',
     '[{"id":"wyr-223-0","text":"Swapping height with your tallest friend"},{"id":"wyr-223-1","text":"Swapping voices with a sibling"},{"id":"wyr-223-2","text":"Swapping handwriting with a friend"},{"id":"wyr-223-3","text":"Swapping laughs with someone"},{"id":"wyr-223-4","text":"Swapping left and right hands (you become ambidextrous)"},{"id":"wyr-223-5","text":"Swapping favorite facial expressions"}]'::jsonb,
     null),
    ('easy',
     'Which holiday would you want to celebrate twice a year?',
     '[{"id":"wyr-224-0","text":"Your birthday"},{"id":"wyr-224-1","text":"Halloween"},{"id":"wyr-224-2","text":"Thanksgiving"},{"id":"wyr-224-3","text":"The Fourth of July"},{"id":"wyr-224-4","text":"Winter holidays"},{"id":"wyr-224-5","text":"New Year's Eve"}]'::jsonb,
     null),
    ('medium',
     'Which birthday party theme would you actually want for your next birthday?',
     '[{"id":"wyr-225-0","text":"A carnival theme with games"},{"id":"wyr-225-1","text":"A movie night theme with a big screen outside"},{"id":"wyr-225-2","text":"A scavenger hunt theme"},{"id":"wyr-225-3","text":"A talent show theme"},{"id":"wyr-225-4","text":"A campout theme in the backyard"},{"id":"wyr-225-5","text":"A mystery/detective theme"}]'::jsonb,
     null),
    ('medium',
     'Which made-up holiday would you actually want to become real?',
     '[{"id":"wyr-226-0","text":"National Sleep-In Day"},{"id":"wyr-226-1","text":"National Pick-the-Dinner Day (for kids)"},{"id":"wyr-226-2","text":"National No-Chores Day"},{"id":"wyr-226-3","text":"National Extra-Recess Day"},{"id":"wyr-226-4","text":"National Dessert-First Day"},{"id":"wyr-226-5","text":"National Stay-Up-Late Day"}]'::jsonb,
     null),
    ('easy',
     'Which natural wonder would you most want to see in person?',
     '[{"id":"wyr-227-0","text":"The Grand Canyon"},{"id":"wyr-227-1","text":"A tropical waterfall"},{"id":"wyr-227-2","text":"A giant redwood forest"},{"id":"wyr-227-3","text":"A glowing bioluminescent beach"},{"id":"wyr-227-4","text":"A field of wildflowers stretching for miles"},{"id":"wyr-227-5","text":"A glacier up close"}]'::jsonb,
     null),
    ('medium',
     'Which campsite upgrade would make roughing it actually feel luxurious?',
     '[{"id":"wyr-228-0","text":"A tent with real air conditioning"},{"id":"wyr-228-1","text":"A campfire that lights itself"},{"id":"wyr-228-2","text":"A cooler that never runs out of ice"},{"id":"wyr-228-3","text":"A hammock strung between the perfect two trees"},{"id":"wyr-228-4","text":"A shower that's actually warm"},{"id":"wyr-228-5","text":"String lights covering the whole campsite"}]'::jsonb,
     null),
    ('hard',
     'Which wilderness survival skill would be the most useful to actually master?',
     '[{"id":"wyr-229-0","text":"Starting a fire without matches"},{"id":"wyr-229-1","text":"Finding clean water"},{"id":"wyr-229-2","text":"Reading a map and compass with no GPS"},{"id":"wyr-229-3","text":"Building a shelter from scratch"},{"id":"wyr-229-4","text":"Identifying safe plants to eat"},{"id":"wyr-229-5","text":"Signaling for help if you're lost"}]'::jsonb,
     null),
    ('easy',
     'Which outdoor nighttime activity would you want to do most?',
     '[{"id":"wyr-230-0","text":"Stargazing with a telescope"},{"id":"wyr-230-1","text":"Roasting marshmallows by a fire"},{"id":"wyr-230-2","text":"Catching fireflies"},{"id":"wyr-230-3","text":"Telling ghost stories"},{"id":"wyr-230-4","text":"A moonlit walk"},{"id":"wyr-230-5","text":"Sleeping outside under the stars"}]'::jsonb,
     null),
    ('medium',
     'Which spooky legend would you actually want to investigate (safely, in daylight)?',
     '[{"id":"wyr-231-0","text":"A supposedly haunted house"},{"id":"wyr-231-1","text":"A lake with a monster rumor"},{"id":"wyr-231-2","text":"An abandoned amusement park"},{"id":"wyr-231-3","text":"A forest said to be enchanted"},{"id":"wyr-231-4","text":"A creaky old lighthouse"},{"id":"wyr-231-5","text":"A ghost town"}]'::jsonb,
     null),
    ('hard',
     'Which classic monster would you least want knocking on your door at midnight?',
     '[{"id":"wyr-232-0","text":"A friendly-looking vampire"},{"id":"wyr-232-1","text":"A polite werewolf"},{"id":"wyr-232-2","text":"A chatty ghost"},{"id":"wyr-232-3","text":"A lumbering zombie (slow but relentless)"},{"id":"wyr-232-4","text":"A mischievous goblin"},{"id":"wyr-232-5","text":"A giant, curious yeti"}]'::jsonb,
     null),
    ('easy',
     'Which Halloween costume category would you always pick?',
     '[{"id":"wyr-233-0","text":"A superhero"},{"id":"wyr-233-1","text":"A spooky classic monster"},{"id":"wyr-233-2","text":"A funny pun costume"},{"id":"wyr-233-3","text":"A favorite movie character"},{"id":"wyr-233-4","text":"An animal"},{"id":"wyr-233-5","text":"Something homemade and creative"}]'::jsonb,
     null),
    ('medium',
     'Which everyday object would you want to be able to shrink or grow on command?',
     '[{"id":"wyr-234-0","text":"Your backpack"},{"id":"wyr-234-1","text":"Your bed"},{"id":"wyr-234-2","text":"Your umbrella"},{"id":"wyr-234-3","text":"Your car"},{"id":"wyr-234-4","text":"Your snack bag"},{"id":"wyr-234-5","text":"Your favorite blanket"}]'::jsonb,
     null),
    ('medium',
     'Which weird talent would you rather be famous for?',
     '[{"id":"wyr-235-0","text":"Being able to recite pi to 100 digits"},{"id":"wyr-235-1","text":"Being unbeatable at a niche video game"},{"id":"wyr-235-2","text":"Having a perfect sense of direction"},{"id":"wyr-235-3","text":"Being able to name any song in two seconds"},{"id":"wyr-235-4","text":"Never losing at rock-paper-scissors"},{"id":"wyr-235-5","text":"Being able to fold laundry impossibly fast"}]'::jsonb,
     null),
    ('easy',
     'Which silly rule would you actually want your family to adopt for a week?',
     '[{"id":"wyr-236-0","text":"Everyone talks like a pirate"},{"id":"wyr-236-1","text":"No one uses their real name"},{"id":"wyr-236-2","text":"Every meal has to include a fruit shaped like a face"},{"id":"wyr-236-3","text":"Everyone wears mismatched socks"},{"id":"wyr-236-4","text":"You can only communicate in gestures for an hour a day"},{"id":"wyr-236-5","text":"Everyone has to compliment someone before breakfast"}]'::jsonb,
     null),
    ('medium',
     'Which "opposite day" swap would be the most fun to try for real?',
     '[{"id":"wyr-237-0","text":"Bedtime and wake-up time flip"},{"id":"wyr-237-1","text":"Breakfast and dinner flip"},{"id":"wyr-237-2","text":"You're in charge instead of the adults"},{"id":"wyr-237-3","text":"Dessert comes before the meal"},{"id":"wyr-237-4","text":"Everyone speaks only in questions"},{"id":"wyr-237-5","text":"Chores get done backwards, last to first"}]'::jsonb,
     null),
    ('hard',
     'Which impossible weather combo would be the most fun to actually experience?',
     '[{"id":"wyr-238-0","text":"Snow falling on a warm sunny beach day"},{"id":"wyr-238-1","text":"Rainbows appearing every single day"},{"id":"wyr-238-2","text":"Fireflies that glow in daylight"},{"id":"wyr-238-3","text":"Clouds that gently rain confetti instead of water"},{"id":"wyr-238-4","text":"A breeze that always smells like your favorite food"},{"id":"wyr-238-5","text":"Stars visible in a bright blue daytime sky"}]'::jsonb,
     null),
    ('medium',
     'Which household chore would you want a robot to handle first?',
     '[{"id":"wyr-239-0","text":"Doing the dishes"},{"id":"wyr-239-1","text":"Folding laundry"},{"id":"wyr-239-2","text":"Vacuuming"},{"id":"wyr-239-3","text":"Taking out the trash"},{"id":"wyr-239-4","text":"Making your bed"},{"id":"wyr-239-5","text":"Cleaning your room"}]'::jsonb,
     null),
    ('easy',
     'Which "trade places for a day" swap sounds like the most fun?',
     '[{"id":"wyr-240-0","text":"Trading places with your pet"},{"id":"wyr-240-1","text":"Trading places with a favorite book character"},{"id":"wyr-240-2","text":"Trading places with a cartoon character"},{"id":"wyr-240-3","text":"Trading places with a video game character"},{"id":"wyr-240-4","text":"Trading places with a movie superhero"},{"id":"wyr-240-5","text":"Trading places with a famous athlete"}]'::jsonb,
     null),
    ('hard',
     'Which impossible but harmless power would cause the most chaos at a family dinner?',
     '[{"id":"wyr-241-0","text":"Everyone can read each other's minds for one hour"},{"id":"wyr-241-1","text":"Food refills itself the second the plate is empty"},{"id":"wyr-241-2","text":"Every joke told becomes hilarious, guaranteed"},{"id":"wyr-241-3","text":"Whoever laughs first has to do dishes"},{"id":"wyr-241-4","text":"The chairs randomly float an inch off the ground"},{"id":"wyr-241-5","text":"Every spilled drink instantly cleans itself up"}]'::jsonb,
     null),
    ('medium',
     'Which type of house would be the most fun to actually live in?',
     '[{"id":"wyr-242-0","text":"A treehouse with multiple levels"},{"id":"wyr-242-1","text":"A houseboat that can travel"},{"id":"wyr-242-2","text":"An underground bunker-style home"},{"id":"wyr-242-3","text":"A tiny house on wheels"},{"id":"wyr-242-4","text":"A converted lighthouse"},{"id":"wyr-242-5","text":"A geodesic dome house"}]'::jsonb,
     null),
    ('easy',
     'Which creative hobby would you want to instantly be amazing at?',
     '[{"id":"wyr-243-0","text":"Drawing"},{"id":"wyr-243-1","text":"Painting"},{"id":"wyr-243-2","text":"Sculpting with clay"},{"id":"wyr-243-3","text":"Photography"},{"id":"wyr-243-4","text":"Writing stories"},{"id":"wyr-243-5","text":"Building with LEGO"}]'::jsonb,
     null),
    ('medium',
     'Which mural would you want painted on your bedroom wall?',
     '[{"id":"wyr-244-0","text":"An underwater ocean scene"},{"id":"wyr-244-1","text":"A galaxy full of stars and planets"},{"id":"wyr-244-2","text":"A jungle full of animals"},{"id":"wyr-244-3","text":"A city skyline at night"},{"id":"wyr-244-4","text":"A field of wildflowers"},{"id":"wyr-244-5","text":"A map of a made-up fantasy world"}]'::jsonb,
     null),
    ('medium',
     'Which art project would you actually want to spend an entire weekend on?',
     '[{"id":"wyr-245-0","text":"A giant sidewalk chalk mural"},{"id":"wyr-245-1","text":"A stop-motion animated short film"},{"id":"wyr-245-2","text":"A treehouse mural inside and out"},{"id":"wyr-245-3","text":"A comic book of your own story"},{"id":"wyr-245-4","text":"A sculpture made entirely of recycled stuff"},{"id":"wyr-245-5","text":"A mosaic made of broken tile pieces"}]'::jsonb,
     null),
    ('medium',
     'Which emotion would you want to be able to turn off for exactly one hour?',
     '[{"id":"wyr-246-0","text":"Nervousness before a big moment"},{"id":"wyr-246-1","text":"Embarrassment"},{"id":"wyr-246-2","text":"Boredom"},{"id":"wyr-246-3","text":"Frustration"},{"id":"wyr-246-4","text":"Shyness"},{"id":"wyr-246-5","text":"Impatience"}]'::jsonb,
     null),
    ('easy',
     'Which compliment would make your whole day?',
     '[{"id":"wyr-247-0","text":"\"You're really funny\""},{"id":"wyr-247-1","text":"\"You're so creative\""},{"id":"wyr-247-2","text":"\"You're a great friend\""},{"id":"wyr-247-3","text":"\"You're really smart\""},{"id":"wyr-247-4","text":"\"You're so brave\""},{"id":"wyr-247-5","text":"\"You're really kind\""}]'::jsonb,
     null),
    ('hard',
     'Which social situation would be the hardest to walk into completely alone?',
     '[{"id":"wyr-248-0","text":"A new school on the first day"},{"id":"wyr-248-1","text":"A birthday party where you know no one"},{"id":"wyr-248-2","text":"A team tryout"},{"id":"wyr-248-3","text":"A stage to give a speech"},{"id":"wyr-248-4","text":"A restaurant to eat by yourself"},{"id":"wyr-248-5","text":"A new neighborhood block party"}]'::jsonb,
     null),
    ('medium',
     'Which everyday invention are you most grateful actually exists?',
     '[{"id":"wyr-249-0","text":"The remote control"},{"id":"wyr-249-1","text":"The microwave"},{"id":"wyr-249-2","text":"Velcro shoes"},{"id":"wyr-249-3","text":"Noise-canceling headphones"},{"id":"wyr-249-4","text":"Automatic doors"},{"id":"wyr-249-5","text":"The zipper"}]'::jsonb,
     null),
    ('medium',
     'Which not-yet-invented gadget would you want to be the one to invent?',
     '[{"id":"wyr-250-0","text":"A machine that folds laundry instantly"},{"id":"wyr-250-1","text":"Shoes that tie themselves"},{"id":"wyr-250-2","text":"A backpack that never feels heavy"},{"id":"wyr-250-3","text":"A pillow that's always cool"},{"id":"wyr-250-4","text":"A pencil that never needs sharpening"},{"id":"wyr-250-5","text":"An alarm clock that wakes you up gently, every time"}]'::jsonb,
     null),
    ('easy',
     'Which classic toy would you want an entire room full of?',
     '[{"id":"wyr-251-0","text":"LEGO bricks"},{"id":"wyr-251-1","text":"Stuffed animals"},{"id":"wyr-251-2","text":"Action figures"},{"id":"wyr-251-3","text":"Board games"},{"id":"wyr-251-4","text":"Building blocks"},{"id":"wyr-251-5","text":"Art supplies"}]'::jsonb,
     null),
    ('easy',
     'Which dog breed personality would you want in a best friend?',
     '[{"id":"wyr-252-0","text":"A golden retriever's friendliness"},{"id":"wyr-252-1","text":"A husky's energy"},{"id":"wyr-252-2","text":"A bulldog's laid-back attitude"},{"id":"wyr-252-3","text":"A border collie's smarts"},{"id":"wyr-252-4","text":"A corgi's playfulness"},{"id":"wyr-252-5","text":"A great dane's gentle giant vibe"}]'::jsonb,
     null),
    ('medium',
     'Which animal''s daily schedule would you actually want to copy?',
     '[{"id":"wyr-253-0","text":"A cat's naps whenever it wants"},{"id":"wyr-253-1","text":"A bird's early sunrise wake-up and free flying"},{"id":"wyr-253-2","text":"A bear's long winter hibernation"},{"id":"wyr-253-3","text":"A dolphin's playful swim-all-day life"},{"id":"wyr-253-4","text":"A squirrel's constant snack-gathering"},{"id":"wyr-253-5","text":"A sloth's slow, no-rush pace"}]'::jsonb,
     null),
    ('medium',
     'Which animal superpower would be the weirdest to actually have?',
     '[{"id":"wyr-254-0","text":"A skunk's ability to clear a room"},{"id":"wyr-254-1","text":"An electric eel's shock"},{"id":"wyr-254-2","text":"A pufferfish's ability to inflate when scared"},{"id":"wyr-254-3","text":"A gecko's sticky feet"},{"id":"wyr-254-4","text":"A chameleon's tongue that's twice its body length"},{"id":"wyr-254-5","text":"An octopus's three hearts"}]'::jsonb,
     null),
    ('easy',
     'Which way of traveling would you pick for your next big trip?',
     '[{"id":"wyr-255-0","text":"A train"},{"id":"wyr-255-1","text":"A cruise ship"},{"id":"wyr-255-2","text":"An airplane"},{"id":"wyr-255-3","text":"An RV"},{"id":"wyr-255-4","text":"A bike tour"},{"id":"wyr-255-5","text":"A hot air balloon (for part of it)"}]'::jsonb,
     null),
    ('medium',
     'Which type of vacation would you actually enjoy most?',
     '[{"id":"wyr-256-0","text":"A beach vacation"},{"id":"wyr-256-1","text":"A mountain cabin trip"},{"id":"wyr-256-2","text":"A big city adventure"},{"id":"wyr-256-3","text":"A theme park trip"},{"id":"wyr-256-4","text":"A camping trip"},{"id":"wyr-256-5","text":"A cruise"}]'::jsonb,
     null),
    ('medium',
     'Which travel mishap would be the most stressful to deal with?',
     '[{"id":"wyr-257-0","text":"A canceled flight the night before"},{"id":"wyr-257-1","text":"Lost luggage on arrival"},{"id":"wyr-257-2","text":"A hotel booking that got mixed up"},{"id":"wyr-257-3","text":"Missing a connection by five minutes"},{"id":"wyr-257-4","text":"A rental car that won't start"},{"id":"wyr-257-5","text":"Forgetting your passport at security"}]'::jsonb,
     null),
    ('easy',
     'Which hotel amenity would you actually use the most?',
     '[{"id":"wyr-258-0","text":"The pool"},{"id":"wyr-258-1","text":"Free breakfast"},{"id":"wyr-258-2","text":"A game room"},{"id":"wyr-258-3","text":"Room service"},{"id":"wyr-258-4","text":"A rooftop view"},{"id":"wyr-258-5","text":"Comfy beds for extra sleeping in"}]'::jsonb,
     null),
    ('easy',
     'Which weekend family tradition would you want to start?',
     '[{"id":"wyr-259-0","text":"Sunday pancake breakfast"},{"id":"wyr-259-1","text":"Friday movie night"},{"id":"wyr-259-2","text":"Saturday morning bike rides"},{"id":"wyr-259-3","text":"A weekly game night"},{"id":"wyr-259-4","text":"A monthly new-restaurant night"},{"id":"wyr-259-5","text":"A backyard campout once a season"}]'::jsonb,
     null),
    ('medium',
     'Which chore would you actually volunteer for if you got to pick?',
     '[{"id":"wyr-260-0","text":"Mowing the lawn"},{"id":"wyr-260-1","text":"Washing the car"},{"id":"wyr-260-2","text":"Grocery shopping"},{"id":"wyr-260-3","text":"Cooking one meal a week"},{"id":"wyr-260-4","text":"Organizing the garage"},{"id":"wyr-260-5","text":"Walking the dog"}]'::jsonb,
     null),
    ('medium',
     'Which family heirloom would you want passed down to you someday?',
     '[{"id":"wyr-261-0","text":"An old pocket watch"},{"id":"wyr-261-1","text":"A handwritten recipe book"},{"id":"wyr-261-2","text":"A vintage camera"},{"id":"wyr-261-3","text":"A quilt made by hand"},{"id":"wyr-261-4","text":"An old family photo album"},{"id":"wyr-261-5","text":"A piece of jewelry with a story behind it"}]'::jsonb,
     null),
    ('easy',
     'Which superpower would be the most useless but still kind of fun?',
     '[{"id":"wyr-262-0","text":"Making your hair change color on command"},{"id":"wyr-262-1","text":"Perfectly imitating any animal sound"},{"id":"wyr-262-2","text":"Never getting hiccups"},{"id":"wyr-262-3","text":"Always landing coin flips correctly"},{"id":"wyr-262-4","text":"Instantly knowing what day of the week any date fell on"},{"id":"wyr-262-5","text":"Wiggling your ears on command"}]'::jsonb,
     null),
    ('medium',
     'Which item would you want to never lose again for the rest of your life?',
     '[{"id":"wyr-263-0","text":"Your phone charger"},{"id":"wyr-263-1","text":"Your favorite pair of socks"},{"id":"wyr-263-2","text":"A pencil that's always sharpened"},{"id":"wyr-263-3","text":"Your house keys"},{"id":"wyr-263-4","text":"Your water bottle"},{"id":"wyr-263-5","text":"One earbud that always seems to vanish"}]'::jsonb,
     null),
    ('medium',
     'Which slightly embarrassing childhood habit would you be fine with everyone finding out about?',
     '[{"id":"wyr-264-0","text":"Talking to your stuffed animals"},{"id":"wyr-264-1","text":"Having an imaginary friend"},{"id":"wyr-264-2","text":"Sleeping with a nightlight past age ten"},{"id":"wyr-264-3","text":"Practicing speeches in the mirror"},{"id":"wyr-264-4","text":"Making up secret handshakes"},{"id":"wyr-264-5","text":"Narrating your own life like a movie"}]'::jsonb,
     null),
    ('medium',
     'Which unusual sport would you actually want in the Olympics?',
     '[{"id":"wyr-265-0","text":"Competitive dodgeball"},{"id":"wyr-265-1","text":"Extreme hide and seek"},{"id":"wyr-265-2","text":"Competitive video gaming"},{"id":"wyr-265-3","text":"Pillow fighting"},{"id":"wyr-265-4","text":"Kite flying"},{"id":"wyr-265-5","text":"Cup stacking"}]'::jsonb,
     null),
    ('easy',
     'Which arcade game would you want unlimited free credits for?',
     '[{"id":"wyr-266-0","text":"Skee-ball"},{"id":"wyr-266-1","text":"Whack-a-mole"},{"id":"wyr-266-2","text":"A racing game"},{"id":"wyr-266-3","text":"A claw machine"},{"id":"wyr-266-4","text":"Air hockey"},{"id":"wyr-266-5","text":"A dance game"}]'::jsonb,
     null),
    ('hard',
     'Which sports injury risk would you accept to guarantee a game-winning play?',
     '[{"id":"wyr-267-0","text":"A scraped knee sliding into base"},{"id":"wyr-267-1","text":"A bruise from blocking a shot"},{"id":"wyr-267-2","text":"A twisted ankle from a quick pivot"},{"id":"wyr-267-3","text":"Getting the wind knocked out of you"},{"id":"wyr-267-4","text":"A rope burn from a rappel"},{"id":"wyr-267-5","text":"A stubbed toe from a diving catch"}]'::jsonb,
     null),
    ('easy',
     'Which reward would motivate you the most to finish all your chores early?',
     '[{"id":"wyr-268-0","text":"An extra hour of screen time"},{"id":"wyr-268-1","text":"Picking dinner for the whole family"},{"id":"wyr-268-2","text":"A later bedtime"},{"id":"wyr-268-3","text":"A trip to get ice cream"},{"id":"wyr-268-4","text":"Skipping one chore next week"},{"id":"wyr-268-5","text":"A new book or game of your choice"}]'::jsonb,
     null),
    ('medium',
     'Which mystery box prize would you be most excited to open?',
     '[{"id":"wyr-269-0","text":"A box that's guaranteed to have your favorite snack"},{"id":"wyr-269-1","text":"A box with a random cool gadget"},{"id":"wyr-269-2","text":"A box with tickets to somewhere fun"},{"id":"wyr-269-3","text":"A box with a brand-new game"},{"id":"wyr-269-4","text":"A box with art supplies"},{"id":"wyr-269-5","text":"A box with a surprise pet accessory (you already have the pet)"}]'::jsonb,
     null),
    ('medium',
     'Which enchanted forest creature would you want to befriend?',
     '[{"id":"wyr-270-0","text":"A talking owl"},{"id":"wyr-270-1","text":"A tiny forest dragon"},{"id":"wyr-270-2","text":"A wise old tortoise"},{"id":"wyr-270-3","text":"A mischievous fox spirit"},{"id":"wyr-270-4","text":"A gentle giant deer with glowing antlers"},{"id":"wyr-270-5","text":"A pack of friendly wolves"}]'::jsonb,
     null),
    ('hard',
     'Which magical curse would be the most annoying to accidentally get stuck with for a week?',
     '[{"id":"wyr-271-0","text":"Sneezing glitter every time you laugh"},{"id":"wyr-271-1","text":"Speaking only in rhymes"},{"id":"wyr-271-2","text":"Floating two inches off the ground at random"},{"id":"wyr-271-3","text":"Every animal you meet starts following you"},{"id":"wyr-271-4","text":"Your shadow moves on its own"},{"id":"wyr-271-5","text":"You can only whisper, never talk normally"}]'::jsonb,
     null),
    ('easy',
     'Which type of treasure would be the most exciting to actually find?',
     '[{"id":"wyr-272-0","text":"A chest of gold coins"},{"id":"wyr-272-1","text":"A map to somewhere unknown"},{"id":"wyr-272-2","text":"A gemstone the size of your fist"},{"id":"wyr-272-3","text":"An ancient artifact with a mystery"},{"id":"wyr-272-4","text":"A hidden room full of old books"},{"id":"wyr-272-5","text":"A sunken ship's cargo"}]'::jsonb,
     null),
    ('medium',
     'Which cozy indoor activity would you want on the snowiest day of the year?',
     '[{"id":"wyr-273-0","text":"Baking cookies"},{"id":"wyr-273-1","text":"Watching movies under a blanket"},{"id":"wyr-273-2","text":"Building a blanket fort"},{"id":"wyr-273-3","text":"Playing board games all day"},{"id":"wyr-273-4","text":"Reading by the fireplace"},{"id":"wyr-273-5","text":"A hot cocoa and puzzle marathon"}]'::jsonb,
     null),
    ('easy',
     'Which sign of a season changing would make you the most excited?',
     '[{"id":"wyr-274-0","text":"The first snowfall"},{"id":"wyr-274-1","text":"The first warm day of spring"},{"id":"wyr-274-2","text":"The leaves turning colors in fall"},{"id":"wyr-274-3","text":"The first day of summer break"},{"id":"wyr-274-4","text":"The first thunderstorm of the season"},{"id":"wyr-274-5","text":"Fireflies showing up at dusk"}]'::jsonb,
     null),
    ('medium',
     'Which class would you want to have twice as long every day?',
     '[{"id":"wyr-275-0","text":"Art class"},{"id":"wyr-275-1","text":"P.E."},{"id":"wyr-275-2","text":"Music class"},{"id":"wyr-275-3","text":"Science with experiments"},{"id":"wyr-275-4","text":"Free reading time"},{"id":"wyr-275-5","text":"Recess"}]'::jsonb,
     null),
    ('medium',
     'Which school project format would you actually enjoy the most?',
     '[{"id":"wyr-276-0","text":"Building a diorama"},{"id":"wyr-276-1","text":"Making a short documentary video"},{"id":"wyr-276-2","text":"Writing and performing a skit"},{"id":"wyr-276-3","text":"Building a working model"},{"id":"wyr-276-4","text":"Designing a poster presentation"},{"id":"wyr-276-5","text":"Creating a podcast episode"}]'::jsonb,
     null),
    ('medium',
     'Which "one wish" would you actually use if a genie offered exactly one?',
     '[{"id":"wyr-277-0","text":"Unlimited more wishes (if that's even allowed)"},{"id":"wyr-277-1","text":"Never getting sick again"},{"id":"wyr-277-2","text":"Being great at everything you try"},{"id":"wyr-277-3","text":"A guaranteed happy life for your whole family"},{"id":"wyr-277-4","text":"Getting to relive your favorite day anytime"},{"id":"wyr-277-5","text":"Knowing the answer to any one question in the world"}]'::jsonb,
     null),
    ('easy',
     'Which classic prank would you actually pull on a sibling if you knew you wouldn''t get in trouble?',
     '[{"id":"wyr-278-0","text":"Switching the sugar and salt"},{"id":"wyr-278-1","text":"A whoopee cushion on their chair"},{"id":"wyr-278-2","text":"Fake spider in their shoe"},{"id":"wyr-278-3","text":"Setting all their clocks five minutes fast"},{"id":"wyr-278-4","text":"Covering their door in sticky notes"},{"id":"wyr-278-5","text":"Swapping their phone wallpaper to something silly"}]'::jsonb,
     null),
    ('medium',
     'Which slightly risky dare would you actually accept from a friend?',
     '[{"id":"wyr-279-0","text":"Eating a whole lemon"},{"id":"wyr-279-1","text":"Singing loudly in a public place"},{"id":"wyr-279-2","text":"Wearing mismatched shoes to school"},{"id":"wyr-279-3","text":"Trying the spiciest sauce on the table"},{"id":"wyr-279-4","text":"Doing your best impression in front of the class"},{"id":"wyr-279-5","text":"Talking in an accent for the whole day"}]'::jsonb,
     null),
    ('medium',
     'Which household item would you want turned into a working vehicle for a day?',
     '[{"id":"wyr-280-0","text":"Your bed (a flying bed)"},{"id":"wyr-280-1","text":"The couch (a rolling couch-mobile)"},{"id":"wyr-280-2","text":"A laundry basket (a go-kart)"},{"id":"wyr-280-3","text":"A kiddie pool (a hovercraft)"},{"id":"wyr-280-4","text":"A wagon (with rocket boosters)"},{"id":"wyr-280-5","text":"A shopping cart (with actual steering)"}]'::jsonb,
     null),
    ('easy',
     'Which "free pass" would you want once a month?',
     '[{"id":"wyr-281-0","text":"Skip one chore"},{"id":"wyr-281-1","text":"Pick the family movie"},{"id":"wyr-281-2","text":"Stay up 30 minutes late"},{"id":"wyr-281-3","text":"Choose the takeout order"},{"id":"wyr-281-4","text":"Skip one homework assignment (teacher-approved)"},{"id":"wyr-281-5","text":"Get out of one dish duty"}]'::jsonb,
     null),
    ('hard',
     'Which slightly chaotic party game would actually be the most fun at your birthday?',
     '[{"id":"wyr-282-0","text":"A giant water balloon fight"},{"id":"wyr-282-1","text":"An egg-and-spoon obstacle course"},{"id":"wyr-282-2","text":"A messy pie-in-the-face challenge"},{"id":"wyr-282-3","text":"A blindfolded pi\u00f1ata free-for-all"},{"id":"wyr-282-4","text":"A silly-string battle"},{"id":"wyr-282-5","text":"A three-legged race relay"}]'::jsonb,
     null),
    ('medium',
     'Which unusual pet would you actually want if your parents said yes to anything?',
     '[{"id":"wyr-283-0","text":"A miniature pig"},{"id":"wyr-283-1","text":"A parrot"},{"id":"wyr-283-2","text":"A tortoise"},{"id":"wyr-283-3","text":"A ferret"},{"id":"wyr-283-4","text":"A bearded dragon"},{"id":"wyr-283-5","text":"A hedgehog"}]'::jsonb,
     null),
    ('easy',
     'Which classic playground equipment would you want in your own backyard?',
     '[{"id":"wyr-284-0","text":"A trampoline"},{"id":"wyr-284-1","text":"A tall slide"},{"id":"wyr-284-2","text":"A swing set"},{"id":"wyr-284-3","text":"Monkey bars"},{"id":"wyr-284-4","text":"A zip line"},{"id":"wyr-284-5","text":"A tetherball pole"}]'::jsonb,
     null),
    ('hard',
     'Which impossible but harmless weather-control power would you want at your next outdoor party?',
     '[{"id":"wyr-285-0","text":"Guaranteed perfect sunny weather"},{"id":"wyr-285-1","text":"A gentle breeze exactly when you need to cool off"},{"id":"wyr-285-2","text":"Clouds that part right on schedule for photos"},{"id":"wyr-285-3","text":"No bugs allowed near the food table"},{"id":"wyr-285-4","text":"Rain that only falls exactly at bedtime"},{"id":"wyr-285-5","text":"A rainbow appearing for the group photo"}]'::jsonb,
     null),
    ('medium',
     'Which candy shop feature would make it the best one in town?',
     '[{"id":"wyr-286-0","text":"A wall of pick-your-own candy bins"},{"id":"wyr-286-1","text":"Free samples of everything"},{"id":"wyr-286-2","text":"A build-your-own chocolate bar station"},{"id":"wyr-286-3","text":"A giant gummy bear as tall as you"},{"id":"wyr-286-4","text":"A candy that changes flavor as you eat it"},{"id":"wyr-286-5","text":"A frequent buyer card with real rewards"}]'::jsonb,
     null),
    ('medium',
     'Which slightly scary carnival ride would you actually get in line for?',
     '[{"id":"wyr-287-0","text":"The tallest drop tower"},{"id":"wyr-287-1","text":"The fastest roller coaster"},{"id":"wyr-287-2","text":"The ride that spins you upside down"},{"id":"wyr-287-3","text":"The haunted house walkthrough"},{"id":"wyr-287-4","text":"The giant swinging pirate ship"},{"id":"wyr-287-5","text":"The ride that goes backwards too"}]'::jsonb,
     null),
    ('easy',
     'Which ice cream truck jingle replacement would you want instead?',
     '[{"id":"wyr-288-0","text":"A kazoo cover of a pop song"},{"id":"wyr-288-1","text":"A tune that changes every day"},{"id":"wyr-288-2","text":"A jingle you get to vote on"},{"id":"wyr-288-3","text":"A song that plays backwards"},{"id":"wyr-288-4","text":"A tune played on actual bells"},{"id":"wyr-288-5","text":"A jingle that's just someone whistling"}]'::jsonb,
     null),
    ('medium',
     'Which unusual talent show act would you want to watch live?',
     '[{"id":"wyr-289-0","text":"A dog doing tricks"},{"id":"wyr-289-1","text":"A kid solving a puzzle cube blindfolded"},{"id":"wyr-289-2","text":"A yo-yo trick master"},{"id":"wyr-289-3","text":"A beatboxer"},{"id":"wyr-289-4","text":"A hula hoop performer with twenty hoops"},{"id":"wyr-289-5","text":"A whistling champion"}]'::jsonb,
     null),
    ('easy',
     'Which backyard campout upgrade would you want most?',
     '[{"id":"wyr-290-0","text":"A projector for movies under the stars"},{"id":"wyr-290-1","text":"A popcorn machine right by the tent"},{"id":"wyr-290-2","text":"String lights strung through the trees"},{"id":"wyr-290-3","text":"A s'mores bar with every topping"},{"id":"wyr-290-4","text":"A speaker for a campfire playlist"},{"id":"wyr-290-5","text":"Walkie-talkies for late-night giggling"}]'::jsonb,
     null),
    ('medium',
     'Which unusual museum would you actually want to visit?',
     '[{"id":"wyr-291-0","text":"A museum of world records"},{"id":"wyr-291-1","text":"A museum entirely about candy"},{"id":"wyr-291-2","text":"A museum of optical illusions"},{"id":"wyr-291-3","text":"A museum of weird inventions"},{"id":"wyr-291-4","text":"A wax museum of your favorite characters"},{"id":"wyr-291-5","text":"A museum you can only explore in the dark with flashlights"}]'::jsonb,
     null),
    ('hard',
     'Which slightly nerve-wracking first would you rather get over with?',
     '[{"id":"wyr-292-0","text":"Your first roller coaster drop"},{"id":"wyr-292-1","text":"Your first time diving off the high board"},{"id":"wyr-292-2","text":"Your first solo bike ride to a friend's house"},{"id":"wyr-292-3","text":"Your first time speaking in front of the whole school"},{"id":"wyr-292-4","text":"Your first sleepover away from home"},{"id":"wyr-292-5","text":"Your first time riding a horse"}]'::jsonb,
     null),
    ('easy',
     'Which classic dessert would you want to learn to bake perfectly?',
     '[{"id":"wyr-293-0","text":"Chocolate chip cookies"},{"id":"wyr-293-1","text":"A birthday cake from scratch"},{"id":"wyr-293-2","text":"Brownies"},{"id":"wyr-293-3","text":"Cupcakes"},{"id":"wyr-293-4","text":"A fruit pie"},{"id":"wyr-293-5","text":"Homemade donuts"}]'::jsonb,
     null),
    ('medium',
     'Which "build it yourself" kit would you want to spend a whole Saturday on?',
     '[{"id":"wyr-294-0","text":"A model rocket"},{"id":"wyr-294-1","text":"A birdhouse"},{"id":"wyr-294-2","text":"A remote control car"},{"id":"wyr-294-3","text":"A marble run"},{"id":"wyr-294-4","text":"A robot kit"},{"id":"wyr-294-5","text":"A fort made of cardboard boxes"}]'::jsonb,
     null),
    ('medium',
     'Which slightly tricky outdoor skill would you want to master this summer?',
     '[{"id":"wyr-295-0","text":"Skipping a stone across water on the first try"},{"id":"wyr-295-1","text":"Whistling with two fingers"},{"id":"wyr-295-2","text":"Doing a cartwheel perfectly"},{"id":"wyr-295-3","text":"Riding a bike with no hands"},{"id":"wyr-295-4","text":"Catching a frisbee behind your back"},{"id":"wyr-295-5","text":"Doing a proper cannonball off the diving board"}]'::jsonb,
     null),
    ('easy',
     'Which stuffed animal upgrade would you want as a kid?',
     '[{"id":"wyr-296-0","text":"One that talks back"},{"id":"wyr-296-1","text":"One the size of a real bed"},{"id":"wyr-296-2","text":"One that lights up softly at night"},{"id":"wyr-296-3","text":"One that's warm like a heating pad"},{"id":"wyr-296-4","text":"One that plays your favorite lullaby"},{"id":"wyr-296-5","text":"One that changes color with your mood"}]'::jsonb,
     null),
    ('medium',
     'Which unusual ice cream shop special would you actually order?',
     '[{"id":"wyr-297-0","text":"A sundae the size of your head"},{"id":"wyr-297-1","text":"A flavor that changes color as it melts"},{"id":"wyr-297-2","text":"A build-your-own flavor swirl"},{"id":"wyr-297-3","text":"A milkshake topped with a whole slice of cake"},{"id":"wyr-297-4","text":"A scoop that pops like candy in your mouth"},{"id":"wyr-297-5","text":"A flavor named after your hometown"}]'::jsonb,
     null),
    ('hard',
     'Which slightly spooky campfire story ending would you actually want to hear?',
     '[{"id":"wyr-298-0","text":"One with a twist you never see coming"},{"id":"wyr-298-1","text":"One that turns out to be a funny prank"},{"id":"wyr-298-2","text":"One with a happy, heartwarming ending"},{"id":"wyr-298-3","text":"One that's left a total mystery on purpose"},{"id":"wyr-298-4","text":"One where the \"monster\" turns out to be friendly"},{"id":"wyr-298-5","text":"One that connects back to something from earlier in the trip"}]'::jsonb,
     null),
    ('medium',
     'Which weird world record would you actually want to attempt breaking?',
     '[{"id":"wyr-299-0","text":"Longest hula hoop streak"},{"id":"wyr-299-1","text":"Most marshmallows caught in your mouth in a minute"},{"id":"wyr-299-2","text":"Fastest time solving a puzzle cube"},{"id":"wyr-299-3","text":"Longest time balancing a spoon on your nose"},{"id":"wyr-299-4","text":"Most jumping jacks in a minute"},{"id":"wyr-299-5","text":"Longest game of tag without getting caught"}]'::jsonb,
     null),
    ('easy',
     'Which classic road game upgrade would make it way more fun?',
     '[{"id":"wyr-300-0","text":"20 Questions but with unlimited questions"},{"id":"wyr-300-1","text":"I Spy but with prizes for winning"},{"id":"wyr-300-2","text":"License plate bingo with a real bingo card"},{"id":"wyr-300-3","text":"Punch Buggy but you get a point instead of a punch"},{"id":"wyr-300-4","text":"The alphabet game but themed to your destination"},{"id":"wyr-300-5","text":"Would You Rather but everyone has to explain their pick"}]'::jsonb,
     null),
    ('hard',
     'Which slightly chaotic weather-themed party would you actually want to throw?',
     '[{"id":"wyr-301-0","text":"A puddle-jumping party after a rainstorm"},{"id":"wyr-301-1","text":"A snow-day sledding party"},{"id":"wyr-301-2","text":"A summer sprinkler and water balloon bash"},{"id":"wyr-301-3","text":"A windy-day kite-flying party"},{"id":"wyr-301-4","text":"A first-frost hot cocoa party"},{"id":"wyr-301-5","text":"A rainbow-watching party right after a storm"}]'::jsonb,
     null),
    ('medium',
     'Which unusual sandwich combo would you actually be willing to try?',
     '[{"id":"wyr-302-0","text":"Peanut butter and pickles"},{"id":"wyr-302-1","text":"Grilled cheese with apple slices inside"},{"id":"wyr-302-2","text":"A breakfast-for-lunch sandwich with eggs and syrup"},{"id":"wyr-302-3","text":"A dessert sandwich with cookies as the bread"},{"id":"wyr-302-4","text":"Turkey with cranberry and potato chips inside"},{"id":"wyr-302-5","text":"A sandwich stacked five layers high"}]'::jsonb,
     null),
    ('easy',
     'Which cozy rainy-day activity would you want most?',
     '[{"id":"wyr-303-0","text":"Reading a good book"},{"id":"wyr-303-1","text":"A puzzle on the living room floor"},{"id":"wyr-303-2","text":"Baking something warm"},{"id":"wyr-303-3","text":"A blanket fort movie marathon"},{"id":"wyr-303-4","text":"Board games with the whole family"},{"id":"wyr-303-5","text":"Drawing or coloring for hours"}]'::jsonb,
     null),
    ('hard',
     'Which slightly wild backyard adventure would you actually want to try?',
     '[{"id":"wyr-304-0","text":"Sleeping in a hammock all night"},{"id":"wyr-304-1","text":"Building an obstacle course out of household items"},{"id":"wyr-304-2","text":"A scavenger hunt with clues hidden all over"},{"id":"wyr-304-3","text":"A DIY zip line (built safely by an adult)"},{"id":"wyr-304-4","text":"A homemade water slide down a hill"},{"id":"wyr-304-5","text":"A glow-in-the-dark game of tag after dark"}]'::jsonb,
     null)
) as q (difficulty, prompt, options, correct_option_id);
