-- Travel Trivia — Genre Batch 2 seed content (Globe-Trotter Clues,
-- Mythical Creatures & Legends, Random Acts of Weird Facts, Superlative
-- Showdown, Time Machine, Pop Culture Time Capsule; 30 questions each,
-- mirroring the app's bundled SeedQuestions.swift; this file is generated
-- from that source).
--
-- All six genres are fixed-answer (unlike Would You Rather), so
-- correct_option_id is always non-null here — no alter table needed.

with genre as (
    select id from public.genres where slug = 'globe-trotter-clues'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('hard',
     'I''m home to more pyramids than Egypt.
My capital sits along the Nile, way south of Cairo.
My ancient kingdom was called Kush.',
     '[{"id":"gtc-1-0","text":"Sudan"},{"id":"gtc-1-1","text":"Egypt"},{"id":"gtc-1-2","text":"Ethiopia"},{"id":"gtc-1-3","text":"Kenya"},{"id":"gtc-1-4","text":"Libya"},{"id":"gtc-1-5","text":"Chad"}]'::jsonb,
     'gtc-1-0'),
    ('easy',
     'I''m shaped like a boot''s little cousin.
I''m famous for volcanoes, ancient ruins, and incredible pasta.
My capital is Rome.',
     '[{"id":"gtc-2-0","text":"Italy"},{"id":"gtc-2-1","text":"Greece"},{"id":"gtc-2-2","text":"Spain"},{"id":"gtc-2-3","text":"Portugal"},{"id":"gtc-2-4","text":"Croatia"},{"id":"gtc-2-5","text":"Turkey"}]'::jsonb,
     'gtc-2-0'),
    ('easy',
     'I''m the world''s largest country by area.
I span 11 time zones.
My capital is Moscow.',
     '[{"id":"gtc-3-0","text":"Russia"},{"id":"gtc-3-1","text":"Canada"},{"id":"gtc-3-2","text":"China"},{"id":"gtc-3-3","text":"USA"},{"id":"gtc-3-4","text":"Brazil"},{"id":"gtc-3-5","text":"Australia"}]'::jsonb,
     'gtc-3-0'),
    ('easy',
     'I''m a country entirely on one continent that''s also my name.
I''m home to kangaroos and the Great Barrier Reef.
My capital is Canberra, not Sydney.',
     '[{"id":"gtc-4-0","text":"Australia"},{"id":"gtc-4-1","text":"New Zealand"},{"id":"gtc-4-2","text":"South Africa"},{"id":"gtc-4-3","text":"Brazil"},{"id":"gtc-4-4","text":"Indonesia"},{"id":"gtc-4-5","text":"Fiji"}]'::jsonb,
     'gtc-4-0'),
    ('easy',
     'I''m known as the Land of the Rising Sun.
I have more vending machines per person than almost anywhere else.
My capital is Tokyo.',
     '[{"id":"gtc-5-0","text":"Japan"},{"id":"gtc-5-1","text":"South Korea"},{"id":"gtc-5-2","text":"China"},{"id":"gtc-5-3","text":"Thailand"},{"id":"gtc-5-4","text":"Vietnam"},{"id":"gtc-5-5","text":"Taiwan"}]'::jsonb,
     'gtc-5-0'),
    ('medium',
     'I''m home to the tallest mountain on Earth.
I sit between India and China.
My capital is Kathmandu.',
     '[{"id":"gtc-6-0","text":"Nepal"},{"id":"gtc-6-1","text":"Bhutan"},{"id":"gtc-6-2","text":"Tibet"},{"id":"gtc-6-3","text":"Pakistan"},{"id":"gtc-6-4","text":"Mongolia"},{"id":"gtc-6-5","text":"Myanmar"}]'::jsonb,
     'gtc-6-0'),
    ('easy',
     'I''m famous for a giant clock tower people often call by the wrong name.
I drive on the left side of the road.
My capital is London.',
     '[{"id":"gtc-7-0","text":"United Kingdom"},{"id":"gtc-7-1","text":"Ireland"},{"id":"gtc-7-2","text":"Australia"},{"id":"gtc-7-3","text":"Canada"},{"id":"gtc-7-4","text":"South Africa"},{"id":"gtc-7-5","text":"New Zealand"}]'::jsonb,
     'gtc-7-0'),
    ('easy',
     'A maple leaf describes me well.
I''m the second-largest country in the world by area.
My capital is Ottawa, not Toronto.',
     '[{"id":"gtc-8-0","text":"Canada"},{"id":"gtc-8-1","text":"USA"},{"id":"gtc-8-2","text":"Russia"},{"id":"gtc-8-3","text":"Greenland"},{"id":"gtc-8-4","text":"Mexico"},{"id":"gtc-8-5","text":"Norway"}]'::jsonb,
     'gtc-8-0'),
    ('medium',
     'I''m home to the largest rainforest on Earth.
Soccer is basically a religion here.
My capital is Brasília, not Rio de Janeiro.',
     '[{"id":"gtc-9-0","text":"Brazil"},{"id":"gtc-9-1","text":"Argentina"},{"id":"gtc-9-2","text":"Peru"},{"id":"gtc-9-3","text":"Colombia"},{"id":"gtc-9-4","text":"Venezuela"},{"id":"gtc-9-5","text":"Ecuador"}]'::jsonb,
     'gtc-9-0'),
    ('hard',
     'I''m a chain of over 17,000 islands.
I''m the largest Muslim-majority country in the world.
My capital is Jakarta.',
     '[{"id":"gtc-10-0","text":"Indonesia"},{"id":"gtc-10-1","text":"Philippines"},{"id":"gtc-10-2","text":"Malaysia"},{"id":"gtc-10-3","text":"Thailand"},{"id":"gtc-10-4","text":"Vietnam"},{"id":"gtc-10-5","text":"India"}]'::jsonb,
     'gtc-10-0'),
    ('easy',
     'I''m famous for the Eiffel Tower and croissants.
I''m shaped roughly like a hexagon.
My capital is Paris.',
     '[{"id":"gtc-11-0","text":"France"},{"id":"gtc-11-1","text":"Belgium"},{"id":"gtc-11-2","text":"Switzerland"},{"id":"gtc-11-3","text":"Spain"},{"id":"gtc-11-4","text":"Germany"},{"id":"gtc-11-5","text":"Italy"}]'::jsonb,
     'gtc-11-0'),
    ('medium',
     'I''m the only country that''s also an entire continent.
I''m home to more sheep than people.
My capital is Canberra.',
     '[{"id":"gtc-12-0","text":"Australia"},{"id":"gtc-12-1","text":"New Zealand"},{"id":"gtc-12-2","text":"Antarctica"},{"id":"gtc-12-3","text":"Greenland"},{"id":"gtc-12-4","text":"Iceland"},{"id":"gtc-12-5","text":"Madagascar"}]'::jsonb,
     'gtc-12-0'),
    ('easy',
     'I''m known for the Great Wall.
I have the world''s largest population.
My capital is Beijing.',
     '[{"id":"gtc-13-0","text":"China"},{"id":"gtc-13-1","text":"India"},{"id":"gtc-13-2","text":"Mongolia"},{"id":"gtc-13-3","text":"Japan"},{"id":"gtc-13-4","text":"South Korea"},{"id":"gtc-13-5","text":"Vietnam"}]'::jsonb,
     'gtc-13-0'),
    ('hard',
     'I''m home to the Sahara, the world''s largest hot desert.
I''m the largest country in Africa by area.
My capital is Algiers.',
     '[{"id":"gtc-14-0","text":"Algeria"},{"id":"gtc-14-1","text":"Libya"},{"id":"gtc-14-2","text":"Egypt"},{"id":"gtc-14-3","text":"Morocco"},{"id":"gtc-14-4","text":"Sudan"},{"id":"gtc-14-5","text":"Chad"}]'::jsonb,
     'gtc-14-0'),
    ('medium',
     'I''m a small European country famous for chocolate, waffles, and beer.
I host the headquarters of the EU.
My capital is Brussels.',
     '[{"id":"gtc-15-0","text":"Belgium"},{"id":"gtc-15-1","text":"Netherlands"},{"id":"gtc-15-2","text":"Switzerland"},{"id":"gtc-15-3","text":"Luxembourg"},{"id":"gtc-15-4","text":"Austria"},{"id":"gtc-15-5","text":"Germany"}]'::jsonb,
     'gtc-15-0'),
    ('hard',
     'I''m the world''s largest island that isn''t also a continent.
Most of me is covered in ice.
I''m technically part of the Kingdom of Denmark.',
     '[{"id":"gtc-16-0","text":"Greenland"},{"id":"gtc-16-1","text":"Iceland"},{"id":"gtc-16-2","text":"Svalbard"},{"id":"gtc-16-3","text":"Antarctica"},{"id":"gtc-16-4","text":"Baffin Island"},{"id":"gtc-16-5","text":"Madagascar"}]'::jsonb,
     'gtc-16-0'),
    ('medium',
     'I''m home to the Great Barrier Reef.
I have more venomous animals than anywhere else on Earth.
My capital is Canberra.',
     '[{"id":"gtc-17-0","text":"Australia"},{"id":"gtc-17-1","text":"Indonesia"},{"id":"gtc-17-2","text":"Papua New Guinea"},{"id":"gtc-17-3","text":"Philippines"},{"id":"gtc-17-4","text":"Fiji"},{"id":"gtc-17-5","text":"New Zealand"}]'::jsonb,
     'gtc-17-0'),
    ('easy',
     'I''m a country famous for the Taj Mahal.
I have the second-largest population in the world.
My capital is New Delhi.',
     '[{"id":"gtc-18-0","text":"India"},{"id":"gtc-18-1","text":"Pakistan"},{"id":"gtc-18-2","text":"Bangladesh"},{"id":"gtc-18-3","text":"Nepal"},{"id":"gtc-18-4","text":"Sri Lanka"},{"id":"gtc-18-5","text":"China"}]'::jsonb,
     'gtc-18-0'),
    ('medium',
     'I''m home to Machu Picchu, high in the Andes.
The ancient Inca Empire was centered here.
My capital is Lima.',
     '[{"id":"gtc-19-0","text":"Peru"},{"id":"gtc-19-1","text":"Bolivia"},{"id":"gtc-19-2","text":"Ecuador"},{"id":"gtc-19-3","text":"Chile"},{"id":"gtc-19-4","text":"Colombia"},{"id":"gtc-19-5","text":"Argentina"}]'::jsonb,
     'gtc-19-0'),
    ('easy',
     'I''m made up of over 5,000 named islands.
I''m known for cherry blossoms and bullet trains.
My capital is Tokyo.',
     '[{"id":"gtc-20-0","text":"Japan"},{"id":"gtc-20-1","text":"Philippines"},{"id":"gtc-20-2","text":"Indonesia"},{"id":"gtc-20-3","text":"South Korea"},{"id":"gtc-20-4","text":"Taiwan"},{"id":"gtc-20-5","text":"Greece"}]'::jsonb,
     'gtc-20-0'),
    ('hard',
     'I''m home to the world''s tallest building.
I''m a desert country known for indoor ski slopes.
My capital is Abu Dhabi, not Dubai.',
     '[{"id":"gtc-21-0","text":"United Arab Emirates"},{"id":"gtc-21-1","text":"Qatar"},{"id":"gtc-21-2","text":"Saudi Arabia"},{"id":"gtc-21-3","text":"Kuwait"},{"id":"gtc-21-4","text":"Oman"},{"id":"gtc-21-5","text":"Bahrain"}]'::jsonb,
     'gtc-21-0'),
    ('hard',
     'I''m a landlocked country in the Alps famous for chocolate and watches.
I have four official languages.
My capital is Bern, not Zurich.',
     '[{"id":"gtc-22-0","text":"Switzerland"},{"id":"gtc-22-1","text":"Austria"},{"id":"gtc-22-2","text":"Liechtenstein"},{"id":"gtc-22-3","text":"Germany"},{"id":"gtc-22-4","text":"Belgium"},{"id":"gtc-22-5","text":"Slovenia"}]'::jsonb,
     'gtc-22-0'),
    ('easy',
     'I''m the birthplace of the Olympic Games.
I''m known for ancient ruins and thousands of islands.
My capital is Athens.',
     '[{"id":"gtc-23-0","text":"Greece"},{"id":"gtc-23-1","text":"Italy"},{"id":"gtc-23-2","text":"Turkey"},{"id":"gtc-23-3","text":"Cyprus"},{"id":"gtc-23-4","text":"Egypt"},{"id":"gtc-23-5","text":"Malta"}]'::jsonb,
     'gtc-23-0'),
    ('easy',
     'I''m famous for tacos, mariachi music, and ancient pyramids.
I share a long border with the United States.
My capital is Mexico City.',
     '[{"id":"gtc-24-0","text":"Mexico"},{"id":"gtc-24-1","text":"Guatemala"},{"id":"gtc-24-2","text":"Belize"},{"id":"gtc-24-3","text":"Cuba"},{"id":"gtc-24-4","text":"Colombia"},{"id":"gtc-24-5","text":"Honduras"}]'::jsonb,
     'gtc-24-0'),
    ('hard',
     'I''m home to Mount Kilimanjaro, Africa''s tallest peak.
The Serengeti and its wildebeest migration are here.
My capital is Dodoma, not Dar es Salaam.',
     '[{"id":"gtc-25-0","text":"Tanzania"},{"id":"gtc-25-1","text":"Kenya"},{"id":"gtc-25-2","text":"Uganda"},{"id":"gtc-25-3","text":"Zambia"},{"id":"gtc-25-4","text":"Mozambique"},{"id":"gtc-25-5","text":"Ethiopia"}]'::jsonb,
     'gtc-25-0'),
    ('medium',
     'I''m known for Vikings, fjords, and the Northern Lights.
I''m one of the happiest countries in the world, year after year.
My capital is Oslo.',
     '[{"id":"gtc-26-0","text":"Norway"},{"id":"gtc-26-1","text":"Sweden"},{"id":"gtc-26-2","text":"Finland"},{"id":"gtc-26-3","text":"Denmark"},{"id":"gtc-26-4","text":"Iceland"},{"id":"gtc-26-5","text":"Greenland"}]'::jsonb,
     'gtc-26-0'),
    ('medium',
     'I''m split almost exactly in half by a famous wall that came down in 1989.
I''m known for sausages, beer, and precision engineering.
My capital is Berlin.',
     '[{"id":"gtc-27-0","text":"Germany"},{"id":"gtc-27-1","text":"Austria"},{"id":"gtc-27-2","text":"Poland"},{"id":"gtc-27-3","text":"Czech Republic"},{"id":"gtc-27-4","text":"Switzerland"},{"id":"gtc-27-5","text":"Netherlands"}]'::jsonb,
     'gtc-27-0'),
    ('hard',
     'I''m home to the world''s driest non-polar desert.
I''m an incredibly long, narrow country running down South America''s west coast.
My capital is Santiago.',
     '[{"id":"gtc-28-0","text":"Chile"},{"id":"gtc-28-1","text":"Peru"},{"id":"gtc-28-2","text":"Argentina"},{"id":"gtc-28-3","text":"Bolivia"},{"id":"gtc-28-4","text":"Ecuador"},{"id":"gtc-28-5","text":"Uruguay"}]'::jsonb,
     'gtc-28-0'),
    ('hard',
     'I''m a small country entirely surrounded by South Africa.
My name is almost a common English word.
My capital is Maseru.',
     '[{"id":"gtc-29-0","text":"Lesotho"},{"id":"gtc-29-1","text":"Eswatini"},{"id":"gtc-29-2","text":"Botswana"},{"id":"gtc-29-3","text":"Namibia"},{"id":"gtc-29-4","text":"Zimbabwe"},{"id":"gtc-29-5","text":"Malawi"}]'::jsonb,
     'gtc-29-0'),
    ('medium',
     'I''m famous for the Northern Lights, hot dogs, and being one of the happiest places on Earth.
I''m not actually that icy despite my name.
My capital is Reykjavik.',
     '[{"id":"gtc-30-0","text":"Iceland"},{"id":"gtc-30-1","text":"Greenland"},{"id":"gtc-30-2","text":"Norway"},{"id":"gtc-30-3","text":"Finland"},{"id":"gtc-30-4","text":"Denmark"},{"id":"gtc-30-5","text":"Sweden"}]'::jsonb,
     'gtc-30-0')
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'mythical-creatures-legends'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('medium',
     'Which creature is said to turn people to stone with its gaze?',
     '[{"id":"myth-1-0","text":"Basilisk"},{"id":"myth-1-1","text":"Griffin"},{"id":"myth-1-2","text":"Chimera"},{"id":"myth-1-3","text":"Sphinx"},{"id":"myth-1-4","text":"Kraken"},{"id":"myth-1-5","text":"Cerberus"}]'::jsonb,
     'myth-1-0'),
    ('easy',
     'In Greek mythology, what is the three-headed dog guarding the underworld?',
     '[{"id":"myth-2-0","text":"Cerberus"},{"id":"myth-2-1","text":"Hydra"},{"id":"myth-2-2","text":"Chimera"},{"id":"myth-2-3","text":"Minotaur"},{"id":"myth-2-4","text":"Cyclops"},{"id":"myth-2-5","text":"Pegasus"}]'::jsonb,
     'myth-2-0'),
    ('easy',
     'What legendary creature is half-man, half-horse?',
     '[{"id":"myth-3-0","text":"Centaur"},{"id":"myth-3-1","text":"Minotaur"},{"id":"myth-3-2","text":"Satyr"},{"id":"myth-3-3","text":"Faun"},{"id":"myth-3-4","text":"Griffin"},{"id":"myth-3-5","text":"Sphinx"}]'::jsonb,
     'myth-3-0'),
    ('easy',
     'What flying horse sprang from Medusa''s blood?',
     '[{"id":"myth-4-0","text":"Pegasus"},{"id":"myth-4-1","text":"Chiron"},{"id":"myth-4-2","text":"Bucephalus"},{"id":"myth-4-3","text":"Sleipnir"},{"id":"myth-4-4","text":"Unicorn"},{"id":"myth-4-5","text":"Griffin"}]'::jsonb,
     'myth-4-0'),
    ('easy',
     'Which legendary creature is said to live in Loch Ness?',
     '[{"id":"myth-5-0","text":"The Loch Ness Monster"},{"id":"myth-5-1","text":"The Kraken"},{"id":"myth-5-2","text":"Leviathan"},{"id":"myth-5-3","text":"Jörmungandr"},{"id":"myth-5-4","text":"Bunyip"},{"id":"myth-5-5","text":"Mokele-mbembe"}]'::jsonb,
     'myth-5-0'),
    ('medium',
     'What giant sea monster attacks ships in Scandinavian folklore?',
     '[{"id":"myth-6-0","text":"The Kraken"},{"id":"myth-6-1","text":"Leviathan"},{"id":"myth-6-2","text":"Jörmungandr"},{"id":"myth-6-3","text":"Charybdis"},{"id":"myth-6-4","text":"Scylla"},{"id":"myth-6-5","text":"Cthulhu"}]'::jsonb,
     'myth-6-0'),
    ('easy',
     'In Egyptian mythology, what creature has a lion''s body and human head?',
     '[{"id":"myth-7-0","text":"Sphinx"},{"id":"myth-7-1","text":"Griffin"},{"id":"myth-7-2","text":"Chimera"},{"id":"myth-7-3","text":"Anubis"},{"id":"myth-7-4","text":"Ammit"},{"id":"myth-7-5","text":"Bastet"}]'::jsonb,
     'myth-7-0'),
    ('easy',
     'What mythical bird bursts into flames and is reborn from its ashes?',
     '[{"id":"myth-8-0","text":"Phoenix"},{"id":"myth-8-1","text":"Roc"},{"id":"myth-8-2","text":"Thunderbird"},{"id":"myth-8-3","text":"Griffin"},{"id":"myth-8-4","text":"Simurgh"},{"id":"myth-8-5","text":"Harpy"}]'::jsonb,
     'myth-8-0'),
    ('hard',
     'In Norse mythology, what giant wolf is destined to kill Odin?',
     '[{"id":"myth-9-0","text":"Fenrir"},{"id":"myth-9-1","text":"Jörmungandr"},{"id":"myth-9-2","text":"Sleipnir"},{"id":"myth-9-3","text":"Garm"},{"id":"myth-9-4","text":"Hati"},{"id":"myth-9-5","text":"Skoll"}]'::jsonb,
     'myth-9-0'),
    ('hard',
     'What shape-shifting Scottish water horse lures people into lakes?',
     '[{"id":"myth-10-0","text":"Kelpie"},{"id":"myth-10-1","text":"Selkie"},{"id":"myth-10-2","text":"Banshee"},{"id":"myth-10-3","text":"Nix"},{"id":"myth-10-4","text":"Bunyip"},{"id":"myth-10-5","text":"Naiad"}]'::jsonb,
     'myth-10-0'),
    ('easy',
     'What legendary giant ape is said to live in the Himalayas?',
     '[{"id":"myth-11-0","text":"Yeti"},{"id":"myth-11-1","text":"Sasquatch"},{"id":"myth-11-2","text":"Bigfoot"},{"id":"myth-11-3","text":"Wendigo"},{"id":"myth-11-4","text":"Chupacabra"},{"id":"myth-11-5","text":"Skunk Ape"}]'::jsonb,
     'myth-11-0'),
    ('easy',
     'What''s the North American legendary creature also known as Bigfoot?',
     '[{"id":"myth-12-0","text":"Sasquatch"},{"id":"myth-12-1","text":"Yeti"},{"id":"myth-12-2","text":"Wendigo"},{"id":"myth-12-3","text":"Jackalope"},{"id":"myth-12-4","text":"Chupacabra"},{"id":"myth-12-5","text":"Mothman"}]'::jsonb,
     'myth-12-0'),
    ('medium',
     'In Greek mythology, what creature is part lion, part goat, part serpent?',
     '[{"id":"myth-13-0","text":"Chimera"},{"id":"myth-13-1","text":"Sphinx"},{"id":"myth-13-2","text":"Hydra"},{"id":"myth-13-3","text":"Griffin"},{"id":"myth-13-4","text":"Cerberus"},{"id":"myth-13-5","text":"Minotaur"}]'::jsonb,
     'myth-13-0'),
    ('easy',
     'What creature has a lion''s body and an eagle''s head and wings?',
     '[{"id":"myth-14-0","text":"Griffin"},{"id":"myth-14-1","text":"Sphinx"},{"id":"myth-14-2","text":"Chimera"},{"id":"myth-14-3","text":"Phoenix"},{"id":"myth-14-4","text":"Hippogriff"},{"id":"myth-14-5","text":"Roc"}]'::jsonb,
     'myth-14-0'),
    ('easy',
     'Which horned horse-like creature is a symbol of purity in legend?',
     '[{"id":"myth-15-0","text":"Unicorn"},{"id":"myth-15-1","text":"Pegasus"},{"id":"myth-15-2","text":"Kirin"},{"id":"myth-15-3","text":"Centaur"},{"id":"myth-15-4","text":"Hippocampus"},{"id":"myth-15-5","text":"Alicorn"}]'::jsonb,
     'myth-15-0'),
    ('easy',
     'What man-eating half-bull, half-man creature is trapped in a labyrinth?',
     '[{"id":"myth-16-0","text":"Minotaur"},{"id":"myth-16-1","text":"Centaur"},{"id":"myth-16-2","text":"Satyr"},{"id":"myth-16-3","text":"Chimera"},{"id":"myth-16-4","text":"Cyclops"},{"id":"myth-16-5","text":"Cerberus"}]'::jsonb,
     'myth-16-0'),
    ('easy',
     'What legendary sea creatures lure sailors with their songs?',
     '[{"id":"myth-17-0","text":"Sirens"},{"id":"myth-17-1","text":"Mermaids"},{"id":"myth-17-2","text":"Nymphs"},{"id":"myth-17-3","text":"Naiads"},{"id":"myth-17-4","text":"Selkies"},{"id":"myth-17-5","text":"Nereids"}]'::jsonb,
     'myth-17-0'),
    ('medium',
     'What multi-headed serpent grows two heads for every one cut off?',
     '[{"id":"myth-18-0","text":"The Hydra"},{"id":"myth-18-1","text":"The Chimera"},{"id":"myth-18-2","text":"Jörmungandr"},{"id":"myth-18-3","text":"The Basilisk"},{"id":"myth-18-4","text":"Typhon"},{"id":"myth-18-5","text":"Ladon"}]'::jsonb,
     'myth-18-0'),
    ('medium',
     'In Japanese folklore, what fox spirit has shapeshifting powers?',
     '[{"id":"myth-19-0","text":"Kitsune"},{"id":"myth-19-1","text":"Tanuki"},{"id":"myth-19-2","text":"Oni"},{"id":"myth-19-3","text":"Tengu"},{"id":"myth-19-4","text":"Yokai"},{"id":"myth-19-5","text":"Kappa"}]'::jsonb,
     'myth-19-0'),
    ('hard',
     'What trickster water spirit in Japanese folklore lures people into rivers?',
     '[{"id":"myth-20-0","text":"Kappa"},{"id":"myth-20-1","text":"Kitsune"},{"id":"myth-20-2","text":"Oni"},{"id":"myth-20-3","text":"Tengu"},{"id":"myth-20-4","text":"Yurei"},{"id":"myth-20-5","text":"Baku"}]'::jsonb,
     'myth-20-0'),
    ('easy',
     'In Slavic folklore, what undead being rises from the grave to drink blood?',
     '[{"id":"myth-21-0","text":"Vampire"},{"id":"myth-21-1","text":"Ghoul"},{"id":"myth-21-2","text":"Wraith"},{"id":"myth-21-3","text":"Banshee"},{"id":"myth-21-4","text":"Lich"},{"id":"myth-21-5","text":"Zombie"}]'::jsonb,
     'myth-21-0'),
    ('medium',
     'What Irish fairy woman''s wailing is said to predict death?',
     '[{"id":"myth-22-0","text":"Banshee"},{"id":"myth-22-1","text":"Leprechaun"},{"id":"myth-22-2","text":"Pooka"},{"id":"myth-22-3","text":"Selkie"},{"id":"myth-22-4","text":"Kelpie"},{"id":"myth-22-5","text":"Changeling"}]'::jsonb,
     'myth-22-0'),
    ('easy',
     'What small, treasure-hoarding fairy is tied to Irish folklore and rainbows?',
     '[{"id":"myth-23-0","text":"Leprechaun"},{"id":"myth-23-1","text":"Banshee"},{"id":"myth-23-2","text":"Pixie"},{"id":"myth-23-3","text":"Gnome"},{"id":"myth-23-4","text":"Brownie"},{"id":"myth-23-5","text":"Sprite"}]'::jsonb,
     'myth-23-0'),
    ('hard',
     'What creature is a seal that can shed its skin to become human?',
     '[{"id":"myth-24-0","text":"Selkie"},{"id":"myth-24-1","text":"Kelpie"},{"id":"myth-24-2","text":"Mermaid"},{"id":"myth-24-3","text":"Naiad"},{"id":"myth-24-4","text":"Siren"},{"id":"myth-24-5","text":"Nix"}]'::jsonb,
     'myth-24-0'),
    ('easy',
     'In Chinese mythology, what powerful creature symbolizes luck and the emperor?',
     '[{"id":"myth-25-0","text":"The Dragon"},{"id":"myth-25-1","text":"The Phoenix"},{"id":"myth-25-2","text":"The Qilin"},{"id":"myth-25-3","text":"The Kirin"},{"id":"myth-25-4","text":"The Tiger"},{"id":"myth-25-5","text":"The Turtle"}]'::jsonb,
     'myth-25-0'),
    ('hard',
     'What single-horned creature appears only during times of peace in Chinese/Japanese myth?',
     '[{"id":"myth-26-0","text":"Qilin"},{"id":"myth-26-1","text":"Kirin"},{"id":"myth-26-2","text":"Dragon"},{"id":"myth-26-3","text":"Phoenix"},{"id":"myth-26-4","text":"Unicorn"},{"id":"myth-26-5","text":"Kitsune"}]'::jsonb,
     'myth-26-0'),
    ('hard',
     'What giant bird in Middle Eastern folklore can carry off elephants?',
     '[{"id":"myth-27-0","text":"Roc"},{"id":"myth-27-1","text":"Simurgh"},{"id":"myth-27-2","text":"Phoenix"},{"id":"myth-27-3","text":"Thunderbird"},{"id":"myth-27-4","text":"Griffin"},{"id":"myth-27-5","text":"Harpy"}]'::jsonb,
     'myth-27-0'),
    ('medium',
     'What creature has a woman''s upper body and a bird''s lower body?',
     '[{"id":"myth-28-0","text":"Harpy"},{"id":"myth-28-1","text":"Siren"},{"id":"myth-28-2","text":"Sphinx"},{"id":"myth-28-3","text":"Sphinx-bird"},{"id":"myth-28-4","text":"Valkyrie"},{"id":"myth-28-5","text":"Fury"}]'::jsonb,
     'myth-28-0'),
    ('hard',
     'What''s Canada''s version of the Loch Ness Monster?',
     '[{"id":"myth-29-0","text":"Ogopogo"},{"id":"myth-29-1","text":"Champ"},{"id":"myth-29-2","text":"Cadborosaurus"},{"id":"myth-29-3","text":"Nessie"},{"id":"myth-29-4","text":"Bessie"},{"id":"myth-29-5","text":"Memphre"}]'::jsonb,
     'myth-29-0'),
    ('medium',
     'In Mexican folklore, what creature drains livestock blood, especially goats?',
     '[{"id":"myth-30-0","text":"Chupacabra"},{"id":"myth-30-1","text":"Wendigo"},{"id":"myth-30-2","text":"La Llorona"},{"id":"myth-30-3","text":"Nagual"},{"id":"myth-30-4","text":"Duende"},{"id":"myth-30-5","text":"El Cucuy"}]'::jsonb,
     'myth-30-0')
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'random-acts-of-weird-facts'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'Which animal sleeps up to 22 hours a day?',
     '[{"id":"weird-1-0","text":"Koala"},{"id":"weird-1-1","text":"Sloth"},{"id":"weird-1-2","text":"Cat"},{"id":"weird-1-3","text":"Panda"},{"id":"weird-1-4","text":"Hedgehog"},{"id":"weird-1-5","text":"Bat"}]'::jsonb,
     'weird-1-0'),
    ('medium',
     'What''s the only mammal capable of true flight?',
     '[{"id":"weird-2-0","text":"Bat"},{"id":"weird-2-1","text":"Flying squirrel"},{"id":"weird-2-2","text":"Sugar glider"},{"id":"weird-2-3","text":"Colugo"},{"id":"weird-2-4","text":"Flying fox"},{"id":"weird-2-5","text":"Pterosaur"}]'::jsonb,
     'weird-2-0'),
    ('medium',
     'Which planet spins on its side compared to the others?',
     '[{"id":"weird-3-0","text":"Uranus"},{"id":"weird-3-1","text":"Venus"},{"id":"weird-3-2","text":"Neptune"},{"id":"weird-3-3","text":"Saturn"},{"id":"weird-3-4","text":"Mars"},{"id":"weird-3-5","text":"Jupiter"}]'::jsonb,
     'weird-3-0'),
    ('easy',
     'What''s the fastest land animal in the world?',
     '[{"id":"weird-4-0","text":"Cheetah"},{"id":"weird-4-1","text":"Lion"},{"id":"weird-4-2","text":"Pronghorn"},{"id":"weird-4-3","text":"Greyhound"},{"id":"weird-4-4","text":"Ostrich"},{"id":"weird-4-5","text":"Gazelle"}]'::jsonb,
     'weird-4-0'),
    ('hard',
     'Which country has the most time zones?',
     '[{"id":"weird-5-0","text":"France"},{"id":"weird-5-1","text":"Russia"},{"id":"weird-5-2","text":"United States"},{"id":"weird-5-3","text":"China"},{"id":"weird-5-4","text":"Canada"},{"id":"weird-5-5","text":"Australia"}]'::jsonb,
     'weird-5-0'),
    ('medium',
     'What is a group of flamingos called?',
     '[{"id":"weird-6-0","text":"A flamboyance"},{"id":"weird-6-1","text":"A flock"},{"id":"weird-6-2","text":"A gaggle"},{"id":"weird-6-3","text":"A pod"},{"id":"weird-6-4","text":"A parliament"},{"id":"weird-6-5","text":"A murder"}]'::jsonb,
     'weird-6-0'),
    ('medium',
     'How many hearts does an octopus have?',
     '[{"id":"weird-7-0","text":"Three"},{"id":"weird-7-1","text":"One"},{"id":"weird-7-2","text":"Two"},{"id":"weird-7-3","text":"Four"},{"id":"weird-7-4","text":"Five"},{"id":"weird-7-5","text":"Eight"}]'::jsonb,
     'weird-7-0'),
    ('medium',
     'What color is a polar bear''s skin under its fur?',
     '[{"id":"weird-8-0","text":"Black"},{"id":"weird-8-1","text":"White"},{"id":"weird-8-2","text":"Pink"},{"id":"weird-8-3","text":"Brown"},{"id":"weird-8-4","text":"Gray"},{"id":"weird-8-5","text":"Blue"}]'::jsonb,
     'weird-8-0'),
    ('medium',
     'What food never spoils if stored properly?',
     '[{"id":"weird-9-0","text":"Honey"},{"id":"weird-9-1","text":"Rice"},{"id":"weird-9-2","text":"Salt"},{"id":"weird-9-3","text":"Sugar"},{"id":"weird-9-4","text":"Vinegar"},{"id":"weird-9-5","text":"Maple syrup"}]'::jsonb,
     'weird-9-0'),
    ('hard',
     'Which country invented modern bungee jumping?',
     '[{"id":"weird-10-0","text":"New Zealand"},{"id":"weird-10-1","text":"Australia"},{"id":"weird-10-2","text":"United States"},{"id":"weird-10-3","text":"United Kingdom"},{"id":"weird-10-4","text":"France"},{"id":"weird-10-5","text":"South Africa"}]'::jsonb,
     'weird-10-0'),
    ('medium',
     'What''s the tallest species of grass in the world?',
     '[{"id":"weird-11-0","text":"Bamboo"},{"id":"weird-11-1","text":"Wheat"},{"id":"weird-11-2","text":"Sugarcane"},{"id":"weird-11-3","text":"Papyrus"},{"id":"weird-11-4","text":"Corn"},{"id":"weird-11-5","text":"Elephant grass"}]'::jsonb,
     'weird-11-0'),
    ('hard',
     'How many bones does a shark have?',
     '[{"id":"weird-12-0","text":"Zero — sharks are cartilage"},{"id":"weird-12-1","text":"100"},{"id":"weird-12-2","text":"206"},{"id":"weird-12-3","text":"300"},{"id":"weird-12-4","text":"50"},{"id":"weird-12-5","text":"1,000"}]'::jsonb,
     'weird-12-0'),
    ('hard',
     'What''s the loudest animal on Earth relative to its size?',
     '[{"id":"weird-13-0","text":"The pistol shrimp"},{"id":"weird-13-1","text":"The blue whale"},{"id":"weird-13-2","text":"The howler monkey"},{"id":"weird-13-3","text":"The elephant"},{"id":"weird-13-4","text":"The lion"},{"id":"weird-13-5","text":"The cicada"}]'::jsonb,
     'weird-13-0'),
    ('medium',
     'Which US state has the most lakes?',
     '[{"id":"weird-14-0","text":"Alaska"},{"id":"weird-14-1","text":"Minnesota"},{"id":"weird-14-2","text":"Michigan"},{"id":"weird-14-3","text":"Wisconsin"},{"id":"weird-14-4","text":"Florida"},{"id":"weird-14-5","text":"Maine"}]'::jsonb,
     'weird-14-0'),
    ('medium',
     'What''s widely credited as the first video game?',
     '[{"id":"weird-15-0","text":"Pong"},{"id":"weird-15-1","text":"Tetris"},{"id":"weird-15-2","text":"Pac-Man"},{"id":"weird-15-3","text":"Space Invaders"},{"id":"weird-15-4","text":"Asteroids"},{"id":"weird-15-5","text":"Spacewar!"}]'::jsonb,
     'weird-15-0'),
    ('hard',
     'Which animal has the strongest bite force of any land animal?',
     '[{"id":"weird-16-0","text":"Saltwater crocodile"},{"id":"weird-16-1","text":"Hippopotamus"},{"id":"weird-16-2","text":"Grizzly bear"},{"id":"weird-16-3","text":"Lion"},{"id":"weird-16-4","text":"Gorilla"},{"id":"weird-16-5","text":"Hyena"}]'::jsonb,
     'weird-16-0'),
    ('medium',
     'What''s the only continent with no active volcanoes?',
     '[{"id":"weird-17-0","text":"Australia"},{"id":"weird-17-1","text":"Antarctica"},{"id":"weird-17-2","text":"Europe"},{"id":"weird-17-3","text":"Asia"},{"id":"weird-17-4","text":"Africa"},{"id":"weird-17-5","text":"South America"}]'::jsonb,
     'weird-17-0'),
    ('hard',
     'How long can a snail sleep in one stretch?',
     '[{"id":"weird-18-0","text":"Up to 3 years"},{"id":"weird-18-1","text":"A few hours"},{"id":"weird-18-2","text":"One week"},{"id":"weird-18-3","text":"One month"},{"id":"weird-18-4","text":"6 months"},{"id":"weird-18-5","text":"A full year"}]'::jsonb,
     'weird-18-0'),
    ('hard',
     'Which fruit is technically a berry, but strawberries aren''t?',
     '[{"id":"weird-19-0","text":"Bananas"},{"id":"weird-19-1","text":"Apples"},{"id":"weird-19-2","text":"Watermelons"},{"id":"weird-19-3","text":"Oranges"},{"id":"weird-19-4","text":"Grapes"},{"id":"weird-19-5","text":"Pineapples"}]'::jsonb,
     'weird-19-0'),
    ('medium',
     'What''s the most consumed beverage in the world after water?',
     '[{"id":"weird-20-0","text":"Tea"},{"id":"weird-20-1","text":"Coffee"},{"id":"weird-20-2","text":"Soda"},{"id":"weird-20-3","text":"Juice"},{"id":"weird-20-4","text":"Milk"},{"id":"weird-20-5","text":"Beer"}]'::jsonb,
     'weird-20-0'),
    ('medium',
     'Which animal can rotate its head almost 270 degrees?',
     '[{"id":"weird-21-0","text":"Owl"},{"id":"weird-21-1","text":"Cat"},{"id":"weird-21-2","text":"Snake"},{"id":"weird-21-3","text":"Chameleon"},{"id":"weird-21-4","text":"Falcon"},{"id":"weird-21-5","text":"Parrot"}]'::jsonb,
     'weird-21-0'),
    ('hard',
     'Roughly what percentage of Earth''s oxygen comes from the ocean?',
     '[{"id":"weird-22-0","text":"Around 50%"},{"id":"weird-22-1","text":"Around 5%"},{"id":"weird-22-2","text":"Around 20%"},{"id":"weird-22-3","text":"Around 80%"},{"id":"weird-22-4","text":"Around 35%"},{"id":"weird-22-5","text":"Around 65%"}]'::jsonb,
     'weird-22-0'),
    ('hard',
     'Which mammal can''t jump at all?',
     '[{"id":"weird-23-0","text":"Elephant"},{"id":"weird-23-1","text":"Rhinoceros"},{"id":"weird-23-2","text":"Hippopotamus"},{"id":"weird-23-3","text":"Sloth"},{"id":"weird-23-4","text":"Whale"},{"id":"weird-23-5","text":"Giraffe"}]'::jsonb,
     'weird-23-0'),
    ('hard',
     'What''s the smallest bone in the human body?',
     '[{"id":"weird-24-0","text":"The stapes (in the ear)"},{"id":"weird-24-1","text":"The femur"},{"id":"weird-24-2","text":"The radius"},{"id":"weird-24-3","text":"The patella"},{"id":"weird-24-4","text":"The clavicle"},{"id":"weird-24-5","text":"The malleus"}]'::jsonb,
     'weird-24-0'),
    ('hard',
     'Which US president appeared on a Wheaties box despite not being an athlete?',
     '[{"id":"weird-25-0","text":"Ronald Reagan"},{"id":"weird-25-1","text":"George Washington"},{"id":"weird-25-2","text":"Abraham Lincoln"},{"id":"weird-25-3","text":"John F. Kennedy"},{"id":"weird-25-4","text":"Theodore Roosevelt"},{"id":"weird-25-5","text":"Dwight Eisenhower"}]'::jsonb,
     'weird-25-0'),
    ('medium',
     'What''s the only letter that doesn''t appear in any US state name?',
     '[{"id":"weird-26-0","text":"Q"},{"id":"weird-26-1","text":"X"},{"id":"weird-26-2","text":"Z"},{"id":"weird-26-3","text":"J"},{"id":"weird-26-4","text":"W"},{"id":"weird-26-5","text":"V"}]'::jsonb,
     'weird-26-0'),
    ('medium',
     'Which animal reportedly never forgets a face?',
     '[{"id":"weird-27-0","text":"Elephant"},{"id":"weird-27-1","text":"Dolphin"},{"id":"weird-27-2","text":"Crow"},{"id":"weird-27-3","text":"Dog"},{"id":"weird-27-4","text":"Horse"},{"id":"weird-27-5","text":"Parrot"}]'::jsonb,
     'weird-27-0'),
    ('hard',
     'What''s the world''s largest desert by area (hint: it''s cold)?',
     '[{"id":"weird-28-0","text":"Antarctica"},{"id":"weird-28-1","text":"Sahara"},{"id":"weird-28-2","text":"Arabian Desert"},{"id":"weird-28-3","text":"Gobi Desert"},{"id":"weird-28-4","text":"Kalahari"},{"id":"weird-28-5","text":"Sonoran Desert"}]'::jsonb,
     'weird-28-0'),
    ('hard',
     'Which toy was originally invented as a wallpaper cleaner?',
     '[{"id":"weird-29-0","text":"Play-Doh"},{"id":"weird-29-1","text":"Silly Putty"},{"id":"weird-29-2","text":"Slinky"},{"id":"weird-29-3","text":"Etch A Sketch"},{"id":"weird-29-4","text":"Legos"},{"id":"weird-29-5","text":"Rubik''s Cube"}]'::jsonb,
     'weird-29-0'),
    ('hard',
     'What''s the loudest thing an octopus can''t do (trick question flavor: pick the true weird fact)?',
     '[{"id":"weird-30-0","text":"Octopuses have blue blood"},{"id":"weird-30-1","text":"Octopuses have red blood"},{"id":"weird-30-2","text":"Octopuses can''t change color"},{"id":"weird-30-3","text":"Octopuses have bones"},{"id":"weird-30-4","text":"Octopuses sleep standing up"},{"id":"weird-30-5","text":"Octopuses live over 50 years"}]'::jsonb,
     'weird-30-0')
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'superlative-showdown'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'What''s the tallest mountain in the world?',
     '[{"id":"super-1-0","text":"Mount Everest"},{"id":"super-1-1","text":"K2"},{"id":"super-1-2","text":"Kilimanjaro"},{"id":"super-1-3","text":"Denali"},{"id":"super-1-4","text":"Mont Blanc"},{"id":"super-1-5","text":"Matterhorn"}]'::jsonb,
     'super-1-0'),
    ('easy',
     'What''s the longest river in the world?',
     '[{"id":"super-2-0","text":"The Nile"},{"id":"super-2-1","text":"The Amazon"},{"id":"super-2-2","text":"The Yangtze"},{"id":"super-2-3","text":"The Mississippi"},{"id":"super-2-4","text":"The Congo"},{"id":"super-2-5","text":"The Danube"}]'::jsonb,
     'super-2-0'),
    ('easy',
     'What''s the largest ocean on Earth?',
     '[{"id":"super-3-0","text":"The Pacific"},{"id":"super-3-1","text":"The Atlantic"},{"id":"super-3-2","text":"The Indian"},{"id":"super-3-3","text":"The Arctic"},{"id":"super-3-4","text":"The Southern"},{"id":"super-3-5","text":"The Mediterranean"}]'::jsonb,
     'super-3-0'),
    ('medium',
     'What''s the smallest country in the world by area?',
     '[{"id":"super-4-0","text":"Vatican City"},{"id":"super-4-1","text":"Monaco"},{"id":"super-4-2","text":"San Marino"},{"id":"super-4-3","text":"Liechtenstein"},{"id":"super-4-4","text":"Malta"},{"id":"super-4-5","text":"Nauru"}]'::jsonb,
     'super-4-0'),
    ('easy',
     'What''s the largest land animal on Earth?',
     '[{"id":"super-5-0","text":"African elephant"},{"id":"super-5-1","text":"Blue whale"},{"id":"super-5-2","text":"Giraffe"},{"id":"super-5-3","text":"Rhinoceros"},{"id":"super-5-4","text":"Hippopotamus"},{"id":"super-5-5","text":"Polar bear"}]'::jsonb,
     'super-5-0'),
    ('medium',
     'What''s the largest animal to have ever lived?',
     '[{"id":"super-6-0","text":"The blue whale"},{"id":"super-6-1","text":"The African elephant"},{"id":"super-6-2","text":"The T. rex"},{"id":"super-6-3","text":"The giant squid"},{"id":"super-6-4","text":"The sperm whale"},{"id":"super-6-5","text":"The Argentinosaurus"}]'::jsonb,
     'super-6-0'),
    ('medium',
     'What''s the fastest bird in the world (in a dive)?',
     '[{"id":"super-7-0","text":"Peregrine falcon"},{"id":"super-7-1","text":"Golden eagle"},{"id":"super-7-2","text":"Ostrich"},{"id":"super-7-3","text":"Hummingbird"},{"id":"super-7-4","text":"Swift"},{"id":"super-7-5","text":"Albatross"}]'::jsonb,
     'super-7-0'),
    ('hard',
     'What''s the largest desert in the world overall?',
     '[{"id":"super-8-0","text":"Antarctic Desert"},{"id":"super-8-1","text":"Sahara Desert"},{"id":"super-8-2","text":"Arabian Desert"},{"id":"super-8-3","text":"Gobi Desert"},{"id":"super-8-4","text":"Kalahari Desert"},{"id":"super-8-5","text":"Sonoran Desert"}]'::jsonb,
     'super-8-0'),
    ('medium',
     'What''s the deepest point in all of Earth''s oceans?',
     '[{"id":"super-9-0","text":"The Mariana Trench"},{"id":"super-9-1","text":"The Puerto Rico Trench"},{"id":"super-9-2","text":"The Java Trench"},{"id":"super-9-3","text":"The Tonga Trench"},{"id":"super-9-4","text":"The Sunda Trench"},{"id":"super-9-5","text":"The Kermadec Trench"}]'::jsonb,
     'super-9-0'),
    ('easy',
     'What''s the largest country in the world by area?',
     '[{"id":"super-10-0","text":"Russia"},{"id":"super-10-1","text":"Canada"},{"id":"super-10-2","text":"China"},{"id":"super-10-3","text":"United States"},{"id":"super-10-4","text":"Brazil"},{"id":"super-10-5","text":"Australia"}]'::jsonb,
     'super-10-0'),
    ('medium',
     'What''s the hottest planet in our solar system?',
     '[{"id":"super-11-0","text":"Venus"},{"id":"super-11-1","text":"Mercury"},{"id":"super-11-2","text":"Mars"},{"id":"super-11-3","text":"Jupiter"},{"id":"super-11-4","text":"Saturn"},{"id":"super-11-5","text":"Earth"}]'::jsonb,
     'super-11-0'),
    ('easy',
     'What''s the largest planet in our solar system?',
     '[{"id":"super-12-0","text":"Jupiter"},{"id":"super-12-1","text":"Saturn"},{"id":"super-12-2","text":"Neptune"},{"id":"super-12-3","text":"Uranus"},{"id":"super-12-4","text":"Earth"},{"id":"super-12-5","text":"Mars"}]'::jsonb,
     'super-12-0'),
    ('easy',
     'What''s the smallest planet in our solar system?',
     '[{"id":"super-13-0","text":"Mercury"},{"id":"super-13-1","text":"Mars"},{"id":"super-13-2","text":"Venus"},{"id":"super-13-3","text":"Pluto"},{"id":"super-13-4","text":"Earth"},{"id":"super-13-5","text":"Neptune"}]'::jsonb,
     'super-13-0'),
    ('hard',
     'What''s the largest lake in the world by surface area?',
     '[{"id":"super-14-0","text":"The Caspian Sea"},{"id":"super-14-1","text":"Lake Superior"},{"id":"super-14-2","text":"Lake Victoria"},{"id":"super-14-3","text":"Lake Baikal"},{"id":"super-14-4","text":"Lake Michigan"},{"id":"super-14-5","text":"The Dead Sea"}]'::jsonb,
     'super-14-0'),
    ('hard',
     'What''s the tallest waterfall in the world?',
     '[{"id":"super-15-0","text":"Angel Falls"},{"id":"super-15-1","text":"Niagara Falls"},{"id":"super-15-2","text":"Victoria Falls"},{"id":"super-15-3","text":"Yosemite Falls"},{"id":"super-15-4","text":"Iguazu Falls"},{"id":"super-15-5","text":"Tugela Falls"}]'::jsonb,
     'super-15-0'),
    ('medium',
     'What''s the largest species of shark in the world?',
     '[{"id":"super-16-0","text":"Whale shark"},{"id":"super-16-1","text":"Great white shark"},{"id":"super-16-2","text":"Tiger shark"},{"id":"super-16-3","text":"Hammerhead shark"},{"id":"super-16-4","text":"Megalodon"},{"id":"super-16-5","text":"Basking shark"}]'::jsonb,
     'super-16-0'),
    ('medium',
     'What''s the smallest bird in the world?',
     '[{"id":"super-17-0","text":"Bee hummingbird"},{"id":"super-17-1","text":"Goldfinch"},{"id":"super-17-2","text":"Wren"},{"id":"super-17-3","text":"Sparrow"},{"id":"super-17-4","text":"Kinglet"},{"id":"super-17-5","text":"Chickadee"}]'::jsonb,
     'super-17-0'),
    ('medium',
     'What''s the largest rodent in the world?',
     '[{"id":"super-18-0","text":"Capybara"},{"id":"super-18-1","text":"Beaver"},{"id":"super-18-2","text":"Groundhog"},{"id":"super-18-3","text":"Porcupine"},{"id":"super-18-4","text":"Muskrat"},{"id":"super-18-5","text":"Nutria"}]'::jsonb,
     'super-18-0'),
    ('easy',
     'What''s the tallest animal in the world?',
     '[{"id":"super-19-0","text":"Giraffe"},{"id":"super-19-1","text":"African elephant"},{"id":"super-19-2","text":"Ostrich"},{"id":"super-19-3","text":"Camel"},{"id":"super-19-4","text":"Moose"},{"id":"super-19-5","text":"Polar bear"}]'::jsonb,
     'super-19-0'),
    ('medium',
     'What''s the coldest place ever recorded on Earth?',
     '[{"id":"super-20-0","text":"Antarctica"},{"id":"super-20-1","text":"Siberia"},{"id":"super-20-2","text":"Greenland"},{"id":"super-20-3","text":"Alaska"},{"id":"super-20-4","text":"Northern Canada"},{"id":"super-20-5","text":"Mount Everest"}]'::jsonb,
     'super-20-0'),
    ('medium',
     'What''s the largest island in the world (not counting continents)?',
     '[{"id":"super-21-0","text":"Greenland"},{"id":"super-21-1","text":"Madagascar"},{"id":"super-21-2","text":"Borneo"},{"id":"super-21-3","text":"New Guinea"},{"id":"super-21-4","text":"Iceland"},{"id":"super-21-5","text":"Great Britain"}]'::jsonb,
     'super-21-0'),
    ('easy',
     'What''s the largest coral reef system in the world?',
     '[{"id":"super-22-0","text":"The Great Barrier Reef"},{"id":"super-22-1","text":"The Belize Barrier Reef"},{"id":"super-22-2","text":"The Red Sea Coral Reef"},{"id":"super-22-3","text":"The Florida Reef"},{"id":"super-22-4","text":"The New Caledonia Barrier Reef"},{"id":"super-22-5","text":"The Mesoamerican Reef"}]'::jsonb,
     'super-22-0'),
    ('easy',
     'What''s the longest wall ever built by humans?',
     '[{"id":"super-23-0","text":"The Great Wall of China"},{"id":"super-23-1","text":"Hadrian''s Wall"},{"id":"super-23-2","text":"The Berlin Wall"},{"id":"super-23-3","text":"The Great Zimbabwe Wall"},{"id":"super-23-4","text":"The Western Wall"},{"id":"super-23-5","text":"The Great Green Wall"}]'::jsonb,
     'super-23-0'),
    ('easy',
     'What''s the largest rainforest in the world?',
     '[{"id":"super-24-0","text":"The Amazon Rainforest"},{"id":"super-24-1","text":"The Congo Rainforest"},{"id":"super-24-2","text":"The Daintree Rainforest"},{"id":"super-24-3","text":"The Southeast Asian Rainforest"},{"id":"super-24-4","text":"The Valdivian Rainforest"},{"id":"super-24-5","text":"The Sundarbans"}]'::jsonb,
     'super-24-0'),
    ('hard',
     'What''s the most venomous animal in the world by toxicity?',
     '[{"id":"super-25-0","text":"The box jellyfish"},{"id":"super-25-1","text":"The king cobra"},{"id":"super-25-2","text":"The black mamba"},{"id":"super-25-3","text":"The inland taipan"},{"id":"super-25-4","text":"The poison dart frog"},{"id":"super-25-5","text":"The stonefish"}]'::jsonb,
     'super-25-0'),
    ('medium',
     'What''s the largest species of penguin?',
     '[{"id":"super-26-0","text":"Emperor penguin"},{"id":"super-26-1","text":"King penguin"},{"id":"super-26-2","text":"Gentoo penguin"},{"id":"super-26-3","text":"Adelie penguin"},{"id":"super-26-4","text":"Chinstrap penguin"},{"id":"super-26-5","text":"Rockhopper penguin"}]'::jsonb,
     'super-26-0'),
    ('hard',
     'What''s the busiest airport in the world by passenger traffic?',
     '[{"id":"super-27-0","text":"Hartsfield-Jackson Atlanta"},{"id":"super-27-1","text":"Beijing Capital"},{"id":"super-27-2","text":"Dubai International"},{"id":"super-27-3","text":"LAX"},{"id":"super-27-4","text":"Heathrow"},{"id":"super-27-5","text":"O''Hare"}]'::jsonb,
     'super-27-0'),
    ('hard',
     'What''s the largest freshwater lake in the world by volume?',
     '[{"id":"super-28-0","text":"Lake Baikal"},{"id":"super-28-1","text":"Lake Superior"},{"id":"super-28-2","text":"Lake Victoria"},{"id":"super-28-3","text":"Lake Tanganyika"},{"id":"super-28-4","text":"The Caspian Sea"},{"id":"super-28-5","text":"Lake Michigan"}]'::jsonb,
     'super-28-0'),
    ('medium',
     'What''s the most populous country in the world?',
     '[{"id":"super-29-0","text":"India"},{"id":"super-29-1","text":"China"},{"id":"super-29-2","text":"United States"},{"id":"super-29-3","text":"Indonesia"},{"id":"super-29-4","text":"Pakistan"},{"id":"super-29-5","text":"Brazil"}]'::jsonb,
     'super-29-0'),
    ('medium',
     'What''s the tallest building in the world?',
     '[{"id":"super-30-0","text":"Burj Khalifa"},{"id":"super-30-1","text":"Shanghai Tower"},{"id":"super-30-2","text":"Empire State Building"},{"id":"super-30-3","text":"Willis Tower"},{"id":"super-30-4","text":"Taipei 101"},{"id":"super-30-5","text":"Petronas Towers"}]'::jsonb,
     'super-30-0')
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'time-machine'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'In which decade did the first iPhone release?',
     '[{"id":"time-1-0","text":"2000s"},{"id":"time-1-1","text":"1990s"},{"id":"time-1-2","text":"2010s"},{"id":"time-1-3","text":"1980s"},{"id":"time-1-4","text":"2020s"},{"id":"time-1-5","text":"1970s"}]'::jsonb,
     'time-1-0'),
    ('medium',
     'In which decade did the Titanic sink?',
     '[{"id":"time-2-0","text":"1910s"},{"id":"time-2-1","text":"1900s"},{"id":"time-2-2","text":"1920s"},{"id":"time-2-3","text":"1890s"},{"id":"time-2-4","text":"1930s"},{"id":"time-2-5","text":"1880s"}]'::jsonb,
     'time-2-0'),
    ('easy',
     'In which decade did the first man walk on the moon?',
     '[{"id":"time-3-0","text":"1960s"},{"id":"time-3-1","text":"1950s"},{"id":"time-3-2","text":"1970s"},{"id":"time-3-3","text":"1940s"},{"id":"time-3-4","text":"1980s"},{"id":"time-3-5","text":"1990s"}]'::jsonb,
     'time-3-0'),
    ('medium',
     'In which decade did the World Wide Web become publicly available?',
     '[{"id":"time-4-0","text":"1990s"},{"id":"time-4-1","text":"1980s"},{"id":"time-4-2","text":"2000s"},{"id":"time-4-3","text":"1970s"},{"id":"time-4-4","text":"2010s"},{"id":"time-4-5","text":"1960s"}]'::jsonb,
     'time-4-0'),
    ('medium',
     'In which decade did Walt Disney World open?',
     '[{"id":"time-5-0","text":"1970s"},{"id":"time-5-1","text":"1960s"},{"id":"time-5-2","text":"1980s"},{"id":"time-5-3","text":"1950s"},{"id":"time-5-4","text":"1990s"},{"id":"time-5-5","text":"2000s"}]'::jsonb,
     'time-5-0'),
    ('medium',
     'In which decade did the Berlin Wall fall?',
     '[{"id":"time-6-0","text":"1980s"},{"id":"time-6-1","text":"1970s"},{"id":"time-6-2","text":"1990s"},{"id":"time-6-3","text":"1960s"},{"id":"time-6-4","text":"2000s"},{"id":"time-6-5","text":"1950s"}]'::jsonb,
     'time-6-0'),
    ('medium',
     'In which decade did home video game consoles first go on sale?',
     '[{"id":"time-7-0","text":"1970s"},{"id":"time-7-1","text":"1960s"},{"id":"time-7-2","text":"1980s"},{"id":"time-7-3","text":"1950s"},{"id":"time-7-4","text":"1990s"},{"id":"time-7-5","text":"2000s"}]'::jsonb,
     'time-7-0'),
    ('hard',
     'In which decade did color television become common in American homes?',
     '[{"id":"time-8-0","text":"1960s"},{"id":"time-8-1","text":"1950s"},{"id":"time-8-2","text":"1970s"},{"id":"time-8-3","text":"1940s"},{"id":"time-8-4","text":"1980s"},{"id":"time-8-5","text":"1930s"}]'::jsonb,
     'time-8-0'),
    ('medium',
     'In which decade did the first Star Wars movie release?',
     '[{"id":"time-9-0","text":"1970s"},{"id":"time-9-1","text":"1960s"},{"id":"time-9-2","text":"1980s"},{"id":"time-9-3","text":"1990s"},{"id":"time-9-4","text":"1950s"},{"id":"time-9-5","text":"2000s"}]'::jsonb,
     'time-9-0'),
    ('medium',
     'In which decade did the Wright brothers achieve powered flight?',
     '[{"id":"time-10-0","text":"1900s"},{"id":"time-10-1","text":"1890s"},{"id":"time-10-2","text":"1910s"},{"id":"time-10-3","text":"1880s"},{"id":"time-10-4","text":"1920s"},{"id":"time-10-5","text":"1870s"}]'::jsonb,
     'time-10-0'),
    ('easy',
     'In which decade did Disney release "The Lion King"?',
     '[{"id":"time-11-0","text":"1990s"},{"id":"time-11-1","text":"1980s"},{"id":"time-11-2","text":"2000s"},{"id":"time-11-3","text":"1970s"},{"id":"time-11-4","text":"2010s"},{"id":"time-11-5","text":"1960s"}]'::jsonb,
     'time-11-0'),
    ('medium',
     'In which decade did the first Harry Potter book publish?',
     '[{"id":"time-12-0","text":"1990s"},{"id":"time-12-1","text":"1980s"},{"id":"time-12-2","text":"2000s"},{"id":"time-12-3","text":"1970s"},{"id":"time-12-4","text":"2010s"},{"id":"time-12-5","text":"2020s"}]'::jsonb,
     'time-12-0'),
    ('medium',
     'In which decade did the Great Depression begin?',
     '[{"id":"time-13-0","text":"1920s"},{"id":"time-13-1","text":"1910s"},{"id":"time-13-2","text":"1930s"},{"id":"time-13-3","text":"1900s"},{"id":"time-13-4","text":"1940s"},{"id":"time-13-5","text":"1890s"}]'::jsonb,
     'time-13-0'),
    ('medium',
     'In which decade did rock and roll first become popular?',
     '[{"id":"time-14-0","text":"1950s"},{"id":"time-14-1","text":"1940s"},{"id":"time-14-2","text":"1960s"},{"id":"time-14-3","text":"1930s"},{"id":"time-14-4","text":"1970s"},{"id":"time-14-5","text":"1920s"}]'::jsonb,
     'time-14-0'),
    ('medium',
     'In which decade did the first Super Mario Bros. release?',
     '[{"id":"time-15-0","text":"1980s"},{"id":"time-15-1","text":"1970s"},{"id":"time-15-2","text":"1990s"},{"id":"time-15-3","text":"1960s"},{"id":"time-15-4","text":"2000s"},{"id":"time-15-5","text":"1950s"}]'::jsonb,
     'time-15-0'),
    ('medium',
     'In which decade did the Cold War officially end?',
     '[{"id":"time-16-0","text":"1990s"},{"id":"time-16-1","text":"1980s"},{"id":"time-16-2","text":"2000s"},{"id":"time-16-3","text":"1970s"},{"id":"time-16-4","text":"1960s"},{"id":"time-16-5","text":"2010s"}]'::jsonb,
     'time-16-0'),
    ('easy',
     'In which decade did the first Pixar movie ("Toy Story") release?',
     '[{"id":"time-17-0","text":"1990s"},{"id":"time-17-1","text":"1980s"},{"id":"time-17-2","text":"2000s"},{"id":"time-17-3","text":"1970s"},{"id":"time-17-4","text":"2010s"},{"id":"time-17-5","text":"1960s"}]'::jsonb,
     'time-17-0'),
    ('medium',
     'In which decade did the internet become a household word?',
     '[{"id":"time-18-0","text":"1990s"},{"id":"time-18-1","text":"1980s"},{"id":"time-18-2","text":"2000s"},{"id":"time-18-3","text":"1970s"},{"id":"time-18-4","text":"2010s"},{"id":"time-18-5","text":"1960s"}]'::jsonb,
     'time-18-0'),
    ('hard',
     'In which decade was the first email ever sent?',
     '[{"id":"time-19-0","text":"1970s"},{"id":"time-19-1","text":"1960s"},{"id":"time-19-2","text":"1980s"},{"id":"time-19-3","text":"1950s"},{"id":"time-19-4","text":"1990s"},{"id":"time-19-5","text":"2000s"}]'::jsonb,
     'time-19-0'),
    ('hard',
     'In which decade did seatbelt laws first become widespread in the US?',
     '[{"id":"time-20-0","text":"1980s"},{"id":"time-20-1","text":"1970s"},{"id":"time-20-2","text":"1990s"},{"id":"time-20-3","text":"1960s"},{"id":"time-20-4","text":"2000s"},{"id":"time-20-5","text":"1950s"}]'::jsonb,
     'time-20-0'),
    ('hard',
     'In which decade did the first Toyota Prius go on sale?',
     '[{"id":"time-21-0","text":"1990s"},{"id":"time-21-1","text":"1980s"},{"id":"time-21-2","text":"2000s"},{"id":"time-21-3","text":"1970s"},{"id":"time-21-4","text":"2010s"},{"id":"time-21-5","text":"1960s"}]'::jsonb,
     'time-21-0'),
    ('hard',
     'In which decade did the first McDonald''s restaurant open?',
     '[{"id":"time-22-0","text":"1940s"},{"id":"time-22-1","text":"1930s"},{"id":"time-22-2","text":"1950s"},{"id":"time-22-3","text":"1920s"},{"id":"time-22-4","text":"1960s"},{"id":"time-22-5","text":"1970s"}]'::jsonb,
     'time-22-0'),
    ('medium',
     'In which decade did Elvis Presley become famous?',
     '[{"id":"time-23-0","text":"1950s"},{"id":"time-23-1","text":"1940s"},{"id":"time-23-2","text":"1960s"},{"id":"time-23-3","text":"1930s"},{"id":"time-23-4","text":"1970s"},{"id":"time-23-5","text":"1920s"}]'::jsonb,
     'time-23-0'),
    ('medium',
     'In which decade did the first Nintendo Game Boy release?',
     '[{"id":"time-24-0","text":"1980s"},{"id":"time-24-1","text":"1970s"},{"id":"time-24-2","text":"1990s"},{"id":"time-24-3","text":"1960s"},{"id":"time-24-4","text":"2000s"},{"id":"time-24-5","text":"1950s"}]'::jsonb,
     'time-24-0'),
    ('medium',
     'In which decade did the real Apollo 13 mission take place?',
     '[{"id":"time-25-0","text":"1970s"},{"id":"time-25-1","text":"1960s"},{"id":"time-25-2","text":"1980s"},{"id":"time-25-3","text":"1950s"},{"id":"time-25-4","text":"1990s"},{"id":"time-25-5","text":"2000s"}]'::jsonb,
     'time-25-0'),
    ('hard',
     'In which decade did drive-in movie theaters peak in the US?',
     '[{"id":"time-26-0","text":"1950s"},{"id":"time-26-1","text":"1940s"},{"id":"time-26-2","text":"1960s"},{"id":"time-26-3","text":"1930s"},{"id":"time-26-4","text":"1970s"},{"id":"time-26-5","text":"1920s"}]'::jsonb,
     'time-26-0'),
    ('hard',
     'In which decade did the first Ford Model T roll off the line?',
     '[{"id":"time-27-0","text":"1900s"},{"id":"time-27-1","text":"1890s"},{"id":"time-27-2","text":"1910s"},{"id":"time-27-3","text":"1880s"},{"id":"time-27-4","text":"1920s"},{"id":"time-27-5","text":"1870s"}]'::jsonb,
     'time-27-0'),
    ('medium',
     'In which decade did the first Star Trek series premiere?',
     '[{"id":"time-28-0","text":"1960s"},{"id":"time-28-1","text":"1950s"},{"id":"time-28-2","text":"1970s"},{"id":"time-28-3","text":"1940s"},{"id":"time-28-4","text":"1980s"},{"id":"time-28-5","text":"1990s"}]'::jsonb,
     'time-28-0'),
    ('hard',
     'In which decade did commercial airline flights begin?',
     '[{"id":"time-29-0","text":"1910s"},{"id":"time-29-1","text":"1900s"},{"id":"time-29-2","text":"1920s"},{"id":"time-29-3","text":"1890s"},{"id":"time-29-4","text":"1930s"},{"id":"time-29-5","text":"1880s"}]'::jsonb,
     'time-29-0'),
    ('medium',
     'In which decade did DVDs overtake VHS in popularity?',
     '[{"id":"time-30-0","text":"2000s"},{"id":"time-30-1","text":"1990s"},{"id":"time-30-2","text":"2010s"},{"id":"time-30-3","text":"1980s"},{"id":"time-30-4","text":"1970s"},{"id":"time-30-5","text":"2020s"}]'::jsonb,
     'time-30-0')
) as q (difficulty, prompt, options, correct_option_id);

with genre as (
    select id from public.genres where slug = 'pop-culture-time-capsule'
)
insert into public.questions (genre_id, difficulty, prompt, options, correct_option_id, source)
select genre.id, q.difficulty, q.prompt, q.options, q.correct_option_id, 'generated'
from genre, (values
    ('easy',
     'What was the digital pet toy of the 1990s you had to feed and care for?',
     '[{"id":"pop-1-0","text":"Tamagotchi"},{"id":"pop-1-1","text":"Furby"},{"id":"pop-1-2","text":"Beanie Babies"},{"id":"pop-1-3","text":"Pokémon cards"},{"id":"pop-1-4","text":"Polly Pocket"},{"id":"pop-1-5","text":"Nintendo Game Boy"}]'::jsonb,
     'pop-1-0'),
    ('medium',
     'Which boy band sang "I Want It That Way"?',
     '[{"id":"pop-2-0","text":"Backstreet Boys"},{"id":"pop-2-1","text":"NSYNC"},{"id":"pop-2-2","text":"Boyz II Men"},{"id":"pop-2-3","text":"New Kids on the Block"},{"id":"pop-2-4","text":"Jonas Brothers"},{"id":"pop-2-5","text":"One Direction"}]'::jsonb,
     'pop-2-0'),
    ('easy',
     'What''s the fictional coffee shop the "Friends" characters hang out at?',
     '[{"id":"pop-3-0","text":"Central Perk"},{"id":"pop-3-1","text":"The Grind"},{"id":"pop-3-2","text":"Java Joe''s"},{"id":"pop-3-3","text":"Cheers"},{"id":"pop-3-4","text":"MacLaren''s"},{"id":"pop-3-5","text":"The Bean"}]'::jsonb,
     'pop-3-0'),
    ('easy',
     'What toy line features small dolls living in tiny compact cases?',
     '[{"id":"pop-4-0","text":"Polly Pocket"},{"id":"pop-4-1","text":"Barbie"},{"id":"pop-4-2","text":"Bratz"},{"id":"pop-4-3","text":"American Girl"},{"id":"pop-4-4","text":"My Little Pony"},{"id":"pop-4-5","text":"Littlest Pet Shop"}]'::jsonb,
     'pop-4-0'),
    ('easy',
     'What 2016 dance craze involves a floss-like arm motion?',
     '[{"id":"pop-5-0","text":"The Floss"},{"id":"pop-5-1","text":"The Dab"},{"id":"pop-5-2","text":"The Whip"},{"id":"pop-5-3","text":"The Nae Nae"},{"id":"pop-5-4","text":"The Renegade"},{"id":"pop-5-5","text":"The Cha Cha Slide"}]'::jsonb,
     'pop-5-0'),
    ('easy',
     'Which video game plumber rescues a princess from a turtle-like villain?',
     '[{"id":"pop-6-0","text":"Super Mario"},{"id":"pop-6-1","text":"Sonic the Hedgehog"},{"id":"pop-6-2","text":"Donkey Kong"},{"id":"pop-6-3","text":"Zelda"},{"id":"pop-6-4","text":"Kirby"},{"id":"pop-6-5","text":"Mega Man"}]'::jsonb,
     'pop-6-0'),
    ('easy',
     'What handheld toy spins between your fingers, huge in the late 2010s?',
     '[{"id":"pop-7-0","text":"Fidget spinner"},{"id":"pop-7-1","text":"Yo-yo"},{"id":"pop-7-2","text":"Pog"},{"id":"pop-7-3","text":"Tamagotchi"},{"id":"pop-7-4","text":"Slap bracelet"},{"id":"pop-7-5","text":"Silly Putty"}]'::jsonb,
     'pop-7-0'),
    ('medium',
     'Which show is known for the phrase "Winter is Coming"?',
     '[{"id":"pop-8-0","text":"Game of Thrones"},{"id":"pop-8-1","text":"The Witcher"},{"id":"pop-8-2","text":"Lord of the Rings"},{"id":"pop-8-3","text":"Vikings"},{"id":"pop-8-4","text":"House of the Dragon"},{"id":"pop-8-5","text":"Outlander"}]'::jsonb,
     'pop-8-0'),
    ('easy',
     'What collectible card game features Pikachu and Charizard?',
     '[{"id":"pop-9-0","text":"Pokémon"},{"id":"pop-9-1","text":"Yu-Gi-Oh!"},{"id":"pop-9-2","text":"Magic: The Gathering"},{"id":"pop-9-3","text":"Digimon"},{"id":"pop-9-4","text":"Bakugan"},{"id":"pop-9-5","text":"Skylanders"}]'::jsonb,
     'pop-9-0'),
    ('medium',
     'Which singing competition launched Kelly Clarkson and Carrie Underwood?',
     '[{"id":"pop-10-0","text":"American Idol"},{"id":"pop-10-1","text":"The Voice"},{"id":"pop-10-2","text":"America''s Got Talent"},{"id":"pop-10-3","text":"X Factor"},{"id":"pop-10-4","text":"The Masked Singer"},{"id":"pop-10-5","text":"So You Think You Can Dance"}]'::jsonb,
     'pop-10-0'),
    ('easy',
     'What battle royale game took over school playgrounds in 2018?',
     '[{"id":"pop-11-0","text":"Fortnite"},{"id":"pop-11-1","text":"Minecraft"},{"id":"pop-11-2","text":"Roblox"},{"id":"pop-11-3","text":"Call of Duty"},{"id":"pop-11-4","text":"Apex Legends"},{"id":"pop-11-5","text":"PUBG"}]'::jsonb,
     'pop-11-0'),
    ('medium',
     'What six-second looping video app shut down in 2017?',
     '[{"id":"pop-12-0","text":"Vine"},{"id":"pop-12-1","text":"Musical.ly"},{"id":"pop-12-2","text":"TikTok"},{"id":"pop-12-3","text":"Snapchat"},{"id":"pop-12-4","text":"Instagram"},{"id":"pop-12-5","text":"YouTube Shorts"}]'::jsonb,
     'pop-12-0'),
    ('easy',
     'Which classic board game involves buying properties like Boardwalk?',
     '[{"id":"pop-13-0","text":"Monopoly"},{"id":"pop-13-1","text":"The Game of Life"},{"id":"pop-13-2","text":"Clue"},{"id":"pop-13-3","text":"Risk"},{"id":"pop-13-4","text":"Sorry!"},{"id":"pop-13-5","text":"Trouble"}]'::jsonb,
     'pop-13-0'),
    ('medium',
     'What egg-shaped-container putty toy became a classic?',
     '[{"id":"pop-14-0","text":"Silly Putty"},{"id":"pop-14-1","text":"Slime"},{"id":"pop-14-2","text":"Gak"},{"id":"pop-14-3","text":"Flarp"},{"id":"pop-14-4","text":"Play-Doh"},{"id":"pop-14-5","text":"Moon Sand"}]'::jsonb,
     'pop-14-0'),
    ('easy',
     'Which cartoon sponge works at the Krusty Krab in Bikini Bottom?',
     '[{"id":"pop-15-0","text":"SpongeBob SquarePants"},{"id":"pop-15-1","text":"The Fairly OddParents"},{"id":"pop-15-2","text":"Rugrats"},{"id":"pop-15-3","text":"CatDog"},{"id":"pop-15-4","text":"Hey Arnold"},{"id":"pop-15-5","text":"Doug"}]'::jsonb,
     'pop-15-0'),
    ('medium',
     'What rubber bracelet trend of the mid-2000s came shaped like animals or words?',
     '[{"id":"pop-16-0","text":"Silly Bandz"},{"id":"pop-16-1","text":"Jelly bracelets"},{"id":"pop-16-2","text":"Livestrong bracelets"},{"id":"pop-16-3","text":"Friendship bracelets"},{"id":"pop-16-4","text":"Slap bracelets"},{"id":"pop-16-5","text":"Pura Vida"}]'::jsonb,
     'pop-16-0'),
    ('easy',
     'Which app made disappearing photo messages popular in the early 2010s?',
     '[{"id":"pop-17-0","text":"Snapchat"},{"id":"pop-17-1","text":"Instagram"},{"id":"pop-17-2","text":"WhatsApp"},{"id":"pop-17-3","text":"TikTok"},{"id":"pop-17-4","text":"BeReal"},{"id":"pop-17-5","text":"Facebook Messenger"}]'::jsonb,
     'pop-17-0'),
    ('medium',
     'What dance/exercise game series used a plastic remote-shaped controller?',
     '[{"id":"pop-18-0","text":"Wii Sports"},{"id":"pop-18-1","text":"Dance Dance Revolution"},{"id":"pop-18-2","text":"Just Dance"},{"id":"pop-18-3","text":"Guitar Hero"},{"id":"pop-18-4","text":"Kinect Sports"},{"id":"pop-18-5","text":"Ring Fit Adventure"}]'::jsonb,
     'pop-18-0'),
    ('easy',
     'Which animated movie about a lost clownfish became a massive hit?',
     '[{"id":"pop-19-0","text":"Finding Nemo"},{"id":"pop-19-1","text":"Finding Dory"},{"id":"pop-19-2","text":"The Little Mermaid"},{"id":"pop-19-3","text":"Shark Tale"},{"id":"pop-19-4","text":"Moana"},{"id":"pop-19-5","text":"Luca"}]'::jsonb,
     'pop-19-0'),
    ('easy',
     'What building/survival game lets players build whole worlds out of blocks?',
     '[{"id":"pop-20-0","text":"Minecraft"},{"id":"pop-20-1","text":"Roblox"},{"id":"pop-20-2","text":"Fortnite"},{"id":"pop-20-3","text":"Terraria"},{"id":"pop-20-4","text":"Lego Worlds"},{"id":"pop-20-5","text":"Animal Crossing"}]'::jsonb,
     'pop-20-0'),
    ('medium',
     'What toy craze wove tiny rubber bands into bracelets on a small loom?',
     '[{"id":"pop-21-0","text":"Rainbow Loom"},{"id":"pop-21-1","text":"Silly Bandz"},{"id":"pop-21-2","text":"Friendship bracelets"},{"id":"pop-21-3","text":"Perler beads"},{"id":"pop-21-4","text":"Pony beads"},{"id":"pop-21-5","text":"Shrinky Dinks"}]'::jsonb,
     'pop-21-0'),
    ('easy',
     'Which life-simulation game lets players build a virtual family''s house and life?',
     '[{"id":"pop-22-0","text":"The Sims"},{"id":"pop-22-1","text":"Animal Crossing"},{"id":"pop-22-2","text":"Stardew Valley"},{"id":"pop-22-3","text":"Second Life"},{"id":"pop-22-4","text":"RollerCoaster Tycoon"},{"id":"pop-22-5","text":"Harvest Moon"}]'::jsonb,
     'pop-22-0'),
    ('medium',
     'What smart speaker device became a common "ask it anything" household gadget?',
     '[{"id":"pop-23-0","text":"Amazon Echo (Alexa)"},{"id":"pop-23-1","text":"Google Home"},{"id":"pop-23-2","text":"Apple HomePod"},{"id":"pop-23-3","text":"Siri"},{"id":"pop-23-4","text":"Cortana"},{"id":"pop-23-5","text":"Bixby"}]'::jsonb,
     'pop-23-0'),
    ('easy',
     'Which app applies silly AR face filters, popular for "stories"?',
     '[{"id":"pop-24-0","text":"Snapchat"},{"id":"pop-24-1","text":"Instagram"},{"id":"pop-24-2","text":"TikTok"},{"id":"pop-24-3","text":"Facebook"},{"id":"pop-24-4","text":"BeReal"},{"id":"pop-24-5","text":"VSCO"}]'::jsonb,
     'pop-24-0'),
    ('medium',
     'What blind-box collectible fad involves "hatching" or unboxing a surprise figure?',
     '[{"id":"pop-25-0","text":"L.O.L. Surprise! dolls"},{"id":"pop-25-1","text":"Beanie Babies"},{"id":"pop-25-2","text":"Squishmallows"},{"id":"pop-25-3","text":"Shopkins"},{"id":"pop-25-4","text":"Hatchimals"},{"id":"pop-25-5","text":"Funko Pops"}]'::jsonb,
     'pop-25-0'),
    ('easy',
     'Which mobile game involves flinging birds at pig-fortified structures?',
     '[{"id":"pop-26-0","text":"Angry Birds"},{"id":"pop-26-1","text":"Candy Crush"},{"id":"pop-26-2","text":"Fruit Ninja"},{"id":"pop-26-3","text":"Temple Run"},{"id":"pop-26-4","text":"Subway Surfers"},{"id":"pop-26-5","text":"Cut the Rope"}]'::jsonb,
     'pop-26-0'),
    ('medium',
     'What 2014 viral fundraiser challenge involved dumping ice water on yourself?',
     '[{"id":"pop-27-0","text":"The Ice Bucket Challenge"},{"id":"pop-27-1","text":"The Cinnamon Challenge"},{"id":"pop-27-2","text":"The Mannequin Challenge"},{"id":"pop-27-3","text":"The Harlem Shake"},{"id":"pop-27-4","text":"The Tide Pod Challenge"},{"id":"pop-27-5","text":"The Bottle Cap Challenge"}]'::jsonb,
     'pop-27-0'),
    ('easy',
     'What early-2020s squishy toy trend features soft, oversized plush animals?',
     '[{"id":"pop-28-0","text":"Squishmallows"},{"id":"pop-28-1","text":"Beanie Babies"},{"id":"pop-28-2","text":"Webkinz"},{"id":"pop-28-3","text":"Jellycats"},{"id":"pop-28-4","text":"Build-A-Bear"},{"id":"pop-28-5","text":"Pillow Pets"}]'::jsonb,
     'pop-28-0'),
    ('medium',
     'What YouTube channel became famous for unboxing/reviewing toys for a huge young audience?',
     '[{"id":"pop-29-0","text":"Ryan''s World"},{"id":"pop-29-1","text":"Cocomelon"},{"id":"pop-29-2","text":"PewDiePie"},{"id":"pop-29-3","text":"MrBeast"},{"id":"pop-29-4","text":"Blippi"},{"id":"pop-29-5","text":"SpongeBob"}]'::jsonb,
     'pop-29-0'),
    ('hard',
     'What app turned 15-second lip-sync videos into a trend before TikTok took over?',
     '[{"id":"pop-30-0","text":"Musical.ly"},{"id":"pop-30-1","text":"Vine"},{"id":"pop-30-2","text":"Snapchat"},{"id":"pop-30-3","text":"Instagram"},{"id":"pop-30-4","text":"Dubsmash"},{"id":"pop-30-5","text":"YouTube Shorts"}]'::jsonb,
     'pop-30-0')
) as q (difficulty, prompt, options, correct_option_id);
